### ISSUE TITLE
Input onChange bug with type=number

### ISSUE THREAD

**Issue by isise100** [telus/tds-core#1005]
### Description
Input's onChange event does not trigger or trigger with invalid value when the input value is invalid.
### Reproduction Steps

- `<Input label="Latitude" name="latitude" value={coord.lat} onChange={onChange} type="number"/>`

- Enter value "5-" in the input.

- The onChange event will be trigger with the target's value equal to an empty string.

- Enter more character.

- No onChange event will be trigger.

### Meta
TDS version: "@tds/core-input": "^2.1.6"
Has workaround: No
High impact: Yes

**Comment by theetrain** [comment]
Thanks for the raising the issue! It appears you have identified a defect. Why did you close the issue?

**Comment by isise100** [comment]
It did the same thing with the native react component input.
