### ISSUE TITLE
Memory leak in ExpandCollapse component

### ISSUE THREAD

**Issue by smm-telus** [telus/tds-core#1028]
## Description

- Using the ExpandCollapse component for a mobile view and a styled list for desktop I have observed a possible memory leak when the ExpandCollapse is in transition (opening or closing) during an unmount.
- `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in TrackResponsiveWidth (created by AsyncComponent)
    in AsyncComponent (created by Connect(AsyncComponent))
    in Connect(AsyncComponent) (created by DataFetcherWrapper)
    in DataFetcherWrapper (created by Connect(DataFetcherWrapper))
    in Connect(DataFetcherWrapper) (created by RouterContext)`

## Reproduction Steps

1. View the BrandFilter component in our staging environment and local
2. Click on the ExpandCollapse BrandFilter to open and then change the screen orientation during the transition.
3. Observe the `console warning` mentioned above that describes a possible memory leak.

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: @tds/core-expand-collapse@1.2.13
- Willing to develop solution: Yes
- Has workaround: Yes 
    - Adding a conditional around setState() functions (See: [BrandFilter](https://github.com/telus/mob-ui-catalogue/blob/master/app/src/ui/components/Filters/Brands/index.jsx#L18))
- High impact: Yes & No

## Screenshots

![Apr-09-2019 14-37-44](https://user-images.githubusercontent.com/31409656/55826096-38dc3400-5ad5-11e9-87af-bf757bc21afa.gif)

**Comment by theetrain** [comment]
From a conversation I had with @smm-telus:

Sean will look into leveraging `componentWillUnmount()` to stop all events before unmounting their `BrandFilter` component. If there is no resolution, the TDS team will look into the same suggestion for ExpandCollapse.

**Comment by marcod1419** [comment]
@smm-telus Has said there will be a follow-up at a later date, so closing for now.
