### ISSUE TITLE
French Trademark Defect

### ISSUE THREAD

**Issue by y9huang** [telus/tds-core#1043]
Allow the "MC" symbol to be in uppercase to properly show it on the Mobility marketing campaign pages

![image](https://user-images.githubusercontent.com/49882384/56521866-dc850580-6513-11e9-8732-0fcf92cd8fb7.png)

**Comment by jraff** [comment]
@nikaukraine @rbrander Is this a Site Builder concern?

**Comment by y9huang** [comment]
yes SB is looking at it tomorrow

**Comment by theetrain** [comment]
For posterity, I'll mention that the TDS and CX teams will revisit our typography stack in Q4 2019. For now, we advise using the letters `MC` directly as a superscript. For example:

```jsx
<Paragraph>Option retcur<Text.Sup>MC</Text.Sup> en...</Paragraph>
```

**Comment by nikaukraine** [comment]
Site Builder will enable the option in RichText during the next sprint, so then we will be able to wrap it text in  <Text.Sup>MC</Text.Sup>

**Comment by marcod1419** [comment]
Closing as this will be addressed on Sitebuilder's end.
