### ISSUE TITLE
Text component not generating css code

### ISSUE THREAD

**Issue by heathervv** [telus/tds-core#1046]
## Description
Using @tds/core-text v 1.0.10 it seems to be ignoring some of it's props. Namely adding `bold` to it adds the correct class, but the class is missing from the CSS. Also, `size="large"` does the same thing. I haven't tested all props, but I assume it might be for all of them.

I expect that when adding a prop to the component, that in addition to the class name being applied, the css is generated correctly.

## Reproduction Steps
- Install @tds/core-text version 1.0.10 (although later versions seem to also cause it)
- Render `<Text bold>I'm a text component</Text>`
- Load in browser, and select element in console
- Notice the class `TDS_Typography-modules__boldFont___2YS3O` is being applied to the markup
- Notice that the element is not bolded visually
- If you search for `TDS_Typography-modules__boldFont___2YS3O`, you should see that it's not being rendered in any `<style />` tag.

Again, this seems to only be a problem I can produce in my application. It's a private repo, so if you'd like access to the codebase message me and I can share it with you.

## Reproduction Percentage (if applicable)

- 10/10 times in my application specifically. Seems to be fine in other cases?

## Meta

- TDS component version:@tds/core-text@1.0.10
- Willing to develop solution: More than happy to jam with the TDS core team! I can't seem to fix it myself.
- Has workaround: No
- High impact: No. Using core-paragraph instead.

## Screenshots
<img width="1552" alt="Screen Shot 2019-04-17 at 11 08 06 AM" src="https://user-images.githubusercontent.com/8507983/56668744-0fe3a380-667e-11e9-93ea-eac1947dfc58.png">

**Comment by theetrain** [comment]
Hello, here are some notes from our conversations outside GitHub.

Try checking your **package-lock.json** to find dependencies that depends on `@tds/core-text`. Make sure all those packages are on their latest version and build again. I tried locally and was able to see the bold text again.

Side note, you should prefer using the `<Strong />` component for bold text since it includes added emphasis for assistive technology.

**Comment by heathervv** [comment]
Thanks @theetrain! Really appreciate the thorough check into this. I'll update our application asap.
