### ISSUE TITLE
Duplicate ids in SVGIcon

### ISSUE THREAD

**Issue by jackdclark** [telus/tds-core#1054]
## Description

Many (maybe all?) of the `SVGIcon`s have a hard-coded `id` attribute which causes duplicate ids on the page when rendering more than one at a time, e.g. [Clipboard](https://github.com/telus/tds-core/blob/master/packages/DecorativeIcon/svgs/Clipboard.jsx#L19). This is raised as invalid HTML and as an accessibility issue by auditing tools such as [Lighthouse](https://developers.google.com/web/tools/lighthouse/) or [axe](https://www.deque.com/axe/)

Maybe the id could be randomly generated? Or perhaps the usage of the `<use>` with `xlinkHref` is unnecessary as these aren't actually reused between multiple components as far as I can see?

## Reproduction Steps

1. Render two  of the same `SVGIcon` (e.g. `Clipboard`) components on the same page
2. View the rendered HTML, run it through an HTML validator or run an accessibility audit such as [Lighthouse](https://developers.google.com/web/tools/lighthouse/)

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: @tds/core-decorative-icon@1.1.2
- Willing to develop solution: No
- Has workaround: No 
- High impact: No 

### From a Lighthouse audit
![Lighthouse audit](https://user-images.githubusercontent.com/1485654/56902126-84a94a00-6a91-11e9-946c-24ec54a3ca27.png)

**Comment by theetrain** [comment]
Hi Jack, thank you for raising this issue. We will look into removing the `id`s when they're not necessary, and if they are, we'll ensure they're unique as they're mounted.

**Comment by jackdclark** [comment]
@theetrain that's great, thank you

**Comment by jraff** [comment]
@jackdclark Fixed with [@tds/core-decorative-icon@2.1.3](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.1.3)
