### ISSUE TITLE
Allow sup element to replace DisplayHeading.Sup, Heading.Sup, and Text.Sup

### ISSUE THREAD

**Issue by rbrander** [telus/tds-core#1059]
## Description

In Site Builder we are using Contentful's RichText editor, and render the output of the syntax tree using TDS components.  The rendering is done via recursive functions that render chunks of text where attributes change. As a result of the recursive nature of the rendering, we do not have the ability to determine if the parent was a Heading, Text, or DisplayHeading; thus making it challenging to determine which .Sup component to use.

## Recommendation

I would like to recommend using CSS selectors on parent components (e.g. DisplayHeading, Heading, Text) to determine how to render a standard sup tag.  For example, Heading.Sup applies a font-size of 1.25rem and a top of -1.3em; this could be replaced with a CSS rule on Heading as 

`h1 > sup { font-size: 1.25rem, top: -1.3em }`

## Meta

- TDS component: @tds/core-display-heading, @tds/core-heading, @tds/core-text
- Willing to develop solution: Maybe
- Has workaround: No
- High impact: No
- Designer/Developer Pair: Rob Brander

**Comment by theetrain** [comment]
Hi Rob, this is a great suggestion! Though we are focused on refactoring our components, we can include this functionality when we get to those components that have a `.Sup` component.

If you wish to expedite the process, we welcome contributions to the following components:

- [ ] Display Heading
- [ ] Heading
- [ ] Paragraph
- [ ] Text

**Comment by marcod1419** [comment]
All relevant components (Heading, DisplayHeading, Text, Paragraph, Small, Strong), have been updated with official support for `<sup>`. The `Component.sup` variants have been deprecated where applicable. Thanks for reporting!
