### ISSUE TITLE
Expand Collapse To be Expanded in Print View.

### ISSUE THREAD

**Issue by invalidred** [telus/tds-core#1064]
## Description

In print view, ExpandCollapse's content is collapsed by default.

## Recommendation

It would be better for the content to be visible by default in print view which will allow users to see content valuable to them.

## Designs

Current print view

![Screen Shot 2019-05-06 at 3 25 58 PM](https://user-images.githubusercontent.com/5270458/57252474-298bd000-701a-11e9-9b41-90c1ba0ed224.png)

Expected print view

![Screen Shot 2019-05-06 at 3 26 16 PM](https://user-images.githubusercontent.com/5270458/57252492-36102880-701a-11e9-8540-0eb56691b51c.png)

## Meta

- TDS component: 
- Willing to develop solution: No
- Has workaround: Yes
- High impact: No
- Designer/Developer Pair: Your name, your design/dev pair's name

**Comment by theetrain** [comment]
Hi, given that print view is not a priority for the design system at this time. Currently, when printing an ExpandCollapse that's already expanded, it will print as expanded. In general, print view should display what they already see.

I'm not entirely sure what the xy problem is. Assuming the customer wants to download a statement for every month in one go, perhaps they should have a one-click solution for that? I recommend your designers look into the problem more closely, and find out what exactly the customer wants.

**Comment by theetrain** [comment]
Hi @invalidred, we will close this issue since there doesn't appear to be any urgent need. Feel free to reach out any time you would like to see movement on this again.
