### ISSUE TITLE
Updating Select box with an icon 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1065]
**## Description**
This is a new design of the new One Time Payment page:
- when the user wants to pay his bill,
        he needs to enter his card details
        and to choose whether to save (or not) his card for future payments.
- If the user saved several cards, the select box component will be visible  

**## Recommendation**
This select box component only shows text information. To recognize visually and more easily the different cards, it is needed to add an icon before the text in the component. 

**## Designs**
**- Links to Invision**
> Design with the current component 
https://telus.invisionapp.com/d/main#/console/17454526/361797878/preview
> Design with current component updated
 https://telus.invisionapp.com/d/main#/console/17454526/361797877/preview
**- Screenshots**
 ![Screen Shot 2019-05-06 at 4 28 35 PM](https://user-images.githubusercontent.com/44266628/57254030-3dd1cc00-701e-11e9-92a1-26fee3cfb705.png)

**## Meta**
- TDS component: Select box Version: 2.0.19
- Willing to develop a solution: Yes
- Has workaround: No
- High impact: No
- Designer/Developer Pair: Designer Marie Fuhrmann / Developer @Jeffrey-Chang, @invalidred

**Comment by Christina-Lo** [comment]
@Mariefhrmnn will take this to design direction to see if we want to move forward with design

**Comment by Christina-Lo** [comment]
@Mariefhrmnn CX is good with this design, is there a developer on your team who can take this on?

**Comment by Mariefhrmnn** [comment]
@Christina-Lo We have developers who could contribute but they don't know when, they are busy for our launch in June

**Comment by Mariefhrmnn** [comment]
@Christina-Lo Do you have any news about the ongoing development?

**Comment by Christina-Lo** [comment]
@Mariefhrmnn have you connected with @kittybourne with the design files? I think she had some questions for you in this https://telusdigital.atlassian.net/browse/TDS-1333. Other than that, this is on our backlog and we can look into prioritizing it.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
