### ISSUE TITLE
Varied alignment for forms (boxes)

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1066]
## Description
When a user goes to the page to pay his bill, he has the possibility to pay one or more bill of his account. 
The page shows:
     - the Bans links to their amounts
     - at the end the 'total amount due' in an editable box.
     - all the prices are right aligned (as on the billing page layout)

The problem is that with the current box component from TDS used for the design, the label + text inside the editable box are always left aligned.

## Recommendation
To have a layout less confusing / more logic and easy to understand.
I would need the flexibility of having right or left align options. 
For example on a check paper, you always have the prices aligned on the same column.

## Designs
- Link to Invision:
> Current design: https://telus.invisionapp.com/d/main#/console/17454526/362036919/preview
> Updated design: https://telus.invisionapp.com/d/main#/console/17454526/362036918/preview
- Screenshots
![Screen Shot 2019-05-07 at 3 19 58 PM](https://user-images.githubusercontent.com/44266628/57327158-32dd7100-70dc-11e9-8442-a9bc22fee3c2.png)

## Meta
- TDS component: TDS > Forms > Version 2.0.4
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No
- Designer/Developer Pair: Designer Marie Fuhrmann / Developer @Jebbie87 , Abdul Khan

**Comment by Christina-Lo** [comment]
Hello @Mariefhrmnn, since this is the one instance where the input form field would need to be right-aligned we will not be making this change at the time. If another use case arises, we can re-evaluate. As it sits right now, the in-put field is visually separated enough that leaving it left-aligned does not confuse users
