### ISSUE TITLE
Update for positioning of tooltip icon 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1069]
## Description

Currently, we have the select box/form with a tooltip icon right aligned.
When the box is too long, the tooltip is far from its label.

## Recommendation

In order to be less confusing for the user, it would be more useful to have the tooltip right beside the label of the box

## Designs

- Link to Invision
Current component: https://telus.invisionapp.com/d/main#/console/17454526/362211123/preview
Component updated: https://telus.invisionapp.com/d/main#/console/17454526/362211122/preview
- Screenshots
![Screen Shot 2019-05-08 at 10 44 18 AM](https://user-images.githubusercontent.com/44266628/57384640-f31b9580-717e-11e9-8588-55146e343310.png)

## Meta

- TDS component: TDS > Forms > Tooltip > Version 3.0.3
- Willing to develop solution: Yes
- Has workaround: Yes (keep the component as it is) 
- High impact: No
- Designer/Developer Pair: Designer Marie Fuhrmann / Developer @Jeffrey-Chang, @invalidred

**Comment by Christina-Lo** [comment]
@Mariefhrmnn will take this to design direction to confirm whether we want to move forward

**Comment by Christina-Lo** [comment]
@Mariefhrmnn CX is good with this design, is there a developer on your team who can take this on?

**Comment by Mariefhrmnn** [comment]
@Christina-Lo We have developers who could contribute but they don't know when, they are busy for our launch in June

**Comment by theetrain** [comment]
Sounds good, we'll connect again soon and work towards making this design change in code.

**Comment by agorovyi** [comment]
This enhancement has been released for [Input](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-input%403.0.16), [Select](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-select%403.1.6) and [TextArea](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-text-area%403.0.15)
