### ISSUE TITLE
Updated design for error state of form component

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1070]
## Description

Currently, when we create a form with fields to fill we use form components with a label outside and some text inside. 

These boxes can have an error message and that message is between the label and the box.

The problem is:
     - when you design a layout with two columns of forms
     - and that there is an error linked to a field,
     - then the two columns are not aligned anymore.

It decreases the visibility and understanding of the form.

## Recommendation

My recommendation to avoid that visual issue is to put the error message below the box. 
therefore there will be less visual shifts and therefore a better readability/understanding on the user side.

## Designs

- Link to Invision
Current component: https://telus.invisionapp.com/d/main#/console/17454526/362288542/preview
Updated component: https://telus.invisionapp.com/d/main#/console/17454526/362288541/preview
- Screenshots
![Screen Shot 2019-05-08 at 4 28 09 PM](https://user-images.githubusercontent.com/44266628/57406263-4f49de00-71ae-11e9-8a42-11de573cfae8.png)

## Meta

- TDS component: TDS > Form > Input > Feedback > Hintinline > Error 
Version: 2.1.15 > https://tds.telus.com/components/index.html#forms
- Willing to develop solution: No
- Has workaround: No
- High impact: No
- Designer/Developer Pair: Designer Marie Fuhrmann / Developer @Jebbie87, Abdul Khan

**Comment by Christina-Lo** [comment]
Hi @Mariefhrmnn the CX team is now updating designs for form fields. You can see the WIP here https://telus.invisionapp.com/d/main/#/console/17399610/360651312/comments...specifically there is a comment in the document made by Donna around accessibility and assistive technology when the field error/validation is below the input. 
"Recommend to maintain the pattern of keeping the field validation above the input for keeping content order and a11y. User is informed of the error before being presented with the input. Otherwise, more effort is required to make sure that the error is read before the input."

**Comment by Christina-Lo** [comment]
@Mariefhrmnn Update! TDS had an error form workshop with CX on Friday May 21st. We are still doing some exploring with error handling in all use cases. Will keep you updated!

**Comment by Mariefhrmnn** [comment]
Amazing! Thanks @Christina-Lo

**Comment by theetrain** [comment]
Hi @Mariefhrmnn here is an update:

We are working with CX on revamping all our form experiences, particularly when there are errors. We appreciate your patience and we are prioritizing this.

**Comment by theetrain** [comment]
Update:

On August 21, 2019, we will look into form validation in code with CX (@kittybourne) to consolidate best practices on form error validation and user flows.

**Comment by theetrain** [comment]
Hi @Mariefhrmnn, here's an update:

We have created several stories based on this ask and action items are prioritized at the top of our backlog. You can watch this story for up-to-date progress, and also see its linked stories for more details: https://telusdigital.atlassian.net/browse/TDS-1610

**Comment by Mariefhrmnn** [comment]
Hi! @theetrain @varunj90 
Do you have an update on this ticket?

**Comment by varunj90** [comment]
hey @Mariefhrmnn we're prioritizing the form EPIC starting this week, please expect an update in a week or two. 

EPIC: https://telusdigital.atlassian.net/browse/TDS-1404
Ticket: https://telusdigital.atlassian.net/browse/TDS-1610

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
