### ISSUE TITLE
Component level loading spinner

### ISSUE THREAD

**Issue by apurvray** [telus/tds-core#1072]
## Description

- When a user tries to change a setting which relies on a server call we have no standardized way of showing progress and success/failure states. We need to show adequate feedback to the users and our current implementation of loading spinners needs to be tweaked for an effective solution. 

## Recommendation

- Adding a smaller version of the spinner with 'white-out' on smaller components like links or check-boxes or toggle buttons with a size of 24x24 (that's the line height of our medium type used with these elements usually).

## Design intent 

- As a user , I would like to see if the action I performed on a component that sends a server side request was successful or failed , so that I can take an informed next step_

## Designs

![download-current-bill-spinner](https://user-images.githubusercontent.com/32710185/57463185-4d345d80-7248-11e9-8fa8-05b6797e0546.gif)

Reduce the minimum size of the spinner to 24px x 24px and scale the background (white-out) to teh parent element. 

## Meta

- TDS component: @tds/core-spinner
- Willing to develop solution: Yes
- Has workaround: No 
- High impact: Yes
- Designer/Developer Pair: @apurvray / Umair (B2B MyTELUS)

**Comment by donnavitan** [comment]
Hello @apurvray, we're currently working on a [related issue](https://github.com/telus/tds-core/issues/907) which addresses this particular concern. Just wanted to let you know that we're working on it and you can follow progress there. Otherwise, we'll update here as necessary.

**Comment by theetrain** [comment]
The Spinner component has been updated and now includes accessibility considerations within its documentation.

It covers use cases such as:

- overlaying buttons, links, or other interactive elements
- how to set up your project to announce loaded content
- covering purple or green buttons with higher contrast
- supplying a label to the Spinner using brief, relevant copy in any language

Learn more:

- [@tds/core-spinner@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-spinner%402.2.0)
- [Spinner documentation](https://tds.telus.com/components/index.html#spinner)
- DSM Library version: _TDS_core v.2.1.10
- [DSM Release notes](https://telus.invisionapp.com/dsm/telus/tds-core/releases)
