### ISSUE TITLE
ExpandCollapse Panel dividers disappear when zoomed out

### ISSUE THREAD

**Issue by mujtabahasni** [telus/tds-core#1085]
## Description
 When there are multiple panels in a `<ExpandCollapse />`, the dividers appear to dissapear when zoomed out in Chrome.

## Reproduction Steps

1. Go to the TDS doc site for [ExpandCollapse](https://tds.telus.com/components/index.html#expand-collapse) 
2. Paste this code in the `VIEW CODE` box: 
```
<ExpandCollapse tag="h2">
  <ExpandCollapse.Panel id="0" header="level 0" />
  <ExpandCollapse.Panel id="0" header="level 0" />
  <ExpandCollapse.Panel id="0" header="level 0" />
  <ExpandCollapse.Panel id="0" header="level 0" />
  <ExpandCollapse.Panel id="0" header="level 0" />
  <ExpandCollapse.Panel id="0" header="level 0" />
</ExpandCollapse>
```
3. In Chrome, click on the 3 dots and Zoom the view out until the dividers start disappearing.

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: 
- Willing to develop solution: No
- Has workaround: No
- High impact: No

## Screenshots
![image](https://user-images.githubusercontent.com/32303524/57866083-b417c080-77cc-11e9-9fbf-7eecf553d6f2.png)

**Comment by theetrain** [comment]
This has been resolved in the following packages:

- [@tds/core-expand-collapse@1.2.24](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%401.2.24)
- [@tds/core-hairline-divider@1.0.7](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-hairline-divider%401.0.7)

Please note, the issue with subpixel rendering persists in the Chromium project. That issue is being tracked in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=663304).

**Comment by theetrain** [comment]
This has also been patched in:

- `@telusdigital/tds@0.34.28`
- `@telusdigital/tds@1.0.29`

**Comment by mejsullivan** [comment]
@theetrain was this a zooming in to 200% issue on Chrome?

**Comment by theetrain** [comment]
@mejsullivan the issue reported involves the hairline divider disappearing on Chrome when zooming out at around the 75% or lower mark. When zooming in to 200%, the hairline divider is still visible. See attached screenshots for reference:

## Zoom level 75%, hairline divider visible

![image](https://user-images.githubusercontent.com/12798751/61163635-3d9df300-a4dd-11e9-8362-84a773f5ee4b.png)

## Zoom level 200%, hairline divider visible

![image](https://user-images.githubusercontent.com/12798751/61163624-2b23b980-a4dd-11e9-8a62-16e1b84db8aa.png)

**Comment by mejsullivan** [comment]
amazing - thank you
