### ISSUE TITLE
Button does not accept a ref

### ISSUE THREAD

**Issue by jackdclark** [telus/tds-core#1090]
## Description

`@tds/core-button` doesn't forward `ref`s to the `<button>`, meaning that the button cannot be programmatically focused

## Reproduction Steps

1. [Attempting to pass a ref to `Button` & focus on mount throws an error](https://codesandbox.io/s/small-forest-r8cto)
2. [Using `forwardRef` to pass the ref to a `StyledButton` resolves this issue](https://codesandbox.io/s/trusting-waterfall-81sbn)

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version @tds/core-button@2.0.7 
- Willing to develop solution: Yes
- Has workaround: Yes - passing a ref to a wrapping container & getting the button with `ref.current.getElementsByTagName`  
- High impact: No 

## Screenshots

- Include any relevant screenshots

**Comment by theetrain** [comment]
Hey Jack, this is a great idea! We plan on adding `forwardRef` to all interactive TDS components going forward. We may not get to Button right away, but we welcome a pull request if you have time.

**Comment by agorovyi** [comment]
This was fixed as part of the [2.1.0 release](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-button%402.1.0)
