### ISSUE TITLE
[ButtonGroupItem] Label not read on hover with screen reader

### ISSUE THREAD

**Issue by isise100** [telus/tds-core#1110]
## Description

When you hover a button in a button group the screen reader should read the button content but it does not except when you hover the top left corner because that is where the invisible radio input is located.

## Reproduction Steps

1.
``` 
import React from 'react'
import ButtonGroup from '@tds/core-button-group'

export default function Test() {

    const [value, setValue] = React.useState("option1");

    const onChange = (event) => {
        setValue(event.target.value)
    };

    return (
        <ButtonGroup name="test" value={value} label={"Chose an option:"} onChange={onChange}>
            <ButtonGroup.Item value="option1"> Option 1</ButtonGroup.Item>
            <ButtonGroup.Item value="option2"> Option 2</ButtonGroup.Item>
        </ButtonGroup>
    )
}
```
2. Activate screen reader software
3. Hover the middle of the 'Option 1' button
4. 'Option 1' is not read by the screen reader
5. Hover the top left corner of the 'Option 1' button
6. 'Option 1' is read by the screen reader

When hovering the button, the text should always be read by the screen reader.

## Reproduction Percentage 

- 100% 

## Meta

- TDS component version: "@tds/core-button-group": "^2.0.3",
- Willing to develop solution: No
- Has workaround: No
- High impact: No

## Screenshots

The radio input in the top left corner.
![image](https://user-images.githubusercontent.com/5930845/59293109-83506d00-8c4c-11e9-967e-b8860c45cb73.png)

**Comment by jraff** [comment]
Hello @isise100, thanks for bringing this issue to our attention, just a couple questions.

1. Which device and browser was used to produce this issue?
2. Which screenreader was used to produce this issue?

**Comment by isise100** [comment]
Chrome v74.0.3729.169
NVDA screen reader v2019.1.1

**Comment by theetrain** [comment]
We'll connect with @owestinTelus for further investigation.

**Comment by theetrain** [comment]
This needs to be tested using Windows + Firefox + NVDA. Keep in mind that NVDA is designed for Firefox.

**Comment by theetrain** [comment]
Hello again, after testing NVDA in Firefox and Chrome on Windows 10, it was able to read the radio button contents without issue. Are there specific reproduction steps I should account for?

Please let me know, and also try testing in Firefox to see if you can reproduce the error.

**Comment by isise100** [comment]
It seem to also work for me with Firefox but i'm not able to make it work with Chrome, but I was not aware that NVDA was design for Firefox.

**Comment by theetrain** [comment]
As per our accessibility tooling guidelines, NVDA is designed for Firefox. So long as it functions properly in Firefox, it's not necessary to test in Chrome. 

I'll consider this issue resolved. cc @owestinTelus

**Comment by owestinTelus** [comment]
Quick recommendation: If you test with NVDA in Chrome and identify a bug.
Verify that it works in FireFox. Then log a ticket. You can identify that
it works in FF and does not need to be resolved for Chrome.

*Oskar Westin *

Digital Accessibility Strategy Manager | 647-993-0054
Technical Operations | TELUS digital
