### ISSUE TITLE
Decorative Icons: Movies and Sports

### ISSUE THREAD

**Issue by twirlingsky** [telus/tds-core#1118]
## Description

On TV plan cards, we're updating to make use of the TDS benefit component, but it specifies that the icons have to be in TDS.  We need additional icons for movie and sports features on plans. 

## Recommendation

Add the movie ticket with a star icon and a soccer ball icons to TDS decorative icons

## Designs

![icon-benefit-sports@2x](https://user-images.githubusercontent.com/22402633/59626023-93a29500-90ef-11e9-9c52-fa3cc444ddb9.png)
![icon-benefit-movies@2x](https://user-images.githubusercontent.com/22402633/59626024-93a29500-90ef-11e9-941d-499bc6a661dc.png)

(Github won't let me add the .svgs here)

## Meta

- TDS decorative icons (for use with the benefit list component)
- Willing to develop solution: Yes
- Has workaround: No
(the benefit list component specifies that the icon must be in TDS)
- High impact: Yes
- Designer/Developer Pair: @twirlingsky / @johntwigg

**Comment by twirlingsky** [comment]
@gkychow Can you please review the icons above?

**Comment by twirlingsky** [comment]
Update to the Movies icon. (These icons can go under TV)

<img width="47" alt="Screen Shot 2019-06-19 at 11 09 47 AM" src="https://user-images.githubusercontent.com/22402633/59789460-c3ce6d00-9282-11e9-8286-0b3af5c90785.png">

**Comment by twirlingsky** [comment]
[TV-Icons.zip](https://github.com/telus/tds-core/files/3307405/TV-Icons.zip)

**Comment by agorovyi** [comment]
Hello @gkychow did you have a chance to review this?

**Comment by twirlingsky** [comment]
In context: https://telus.invisionapp.com/d/main#/console/17553495/366079414/preview

**Comment by gkychow** [comment]
@agorovyi - Looks good to me!

@twirlingsky will be helping simplify the movie eventually, but it works for now!

**Comment by johntwigg** [comment]
@gkychow Is the movies icon available yet?

**Comment by johntwigg** [comment]
@Franimal604 Did Laurel update you on this before leaving? We are going to Prod tomorrow with Basics + Crave and will need this icon available to test today. Thanks!

**Comment by Franimal604** [comment]
[Icons.zip](https://github.com/telus/tds-core/files/3322654/Icons.zip)

**Comment by johntwigg** [comment]
@gkychow Is there a version of TDS available now to import the Movies Decorative Icon? We're going to Prod tomorrow. Thanks!

**Comment by theetrain** [comment]
Update: this is being prioritized by the TDS team. You may use alternative icons provided by @Franimal604 for the interim.

**Comment by varunj90** [comment]
TDS Core DSM Library v2.2.1 released:
Addition to DecorativeIcon
• 2 new icons are now available in DecorativeIcon
• Movie  (General)
• Soccer (General)

Release notes: https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%401.3.0
Docs: https://tds.telus.com/components/index.html#decorativeicon

**Comment by mejsullivan** [comment]
@varunj90 - does your team deem this have been released and are accessible? I'd love to highlight that they are, if accessibility documentation and tests were complete by your team.
CC @owestinTelus @dewing9

**Comment by varunj90** [comment]
Hi Beth! Given these are decorative icons, we don't need to add the label.

https://tds.telus.com/components/index.html#decorativeicon

"Decorative icons do not perform a role beyond visual aesthetics and are hidden from screen readers using the aria-hidden attribute. Usually, the information being communicated with the icon is also conveyed in another manner."

We will be doing a workshop next month about icons and their usage
cc: @Christina-Lo
