### ISSUE TITLE
Input (type=email) cursor moves when prefixed with whitespace

### ISSUE THREAD

**Issue by rbrander** [telus/tds-core#1123]
## Description

I'm trying to use an Input component to capture email addresses.  When the type is set to 'email', the behaviour of the input changes (as compared to type='text'), specifically when the field value is prefaced with whitespace.  Once a character is added after the whitespace, the cursor moves to the beginning of the field and the value is changed to have only the new character (without whitespace).

## Reproduction Steps

1. Render an Input component with type="email"
2. Click on the Input component and type one or many spaces
3. Type 'a', 's'
4. Observe the field value is 'sa', with the cursor between the two characters

I expected to see 'as' with the cursor at the right of the 's'

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: @tds/core-input@3.0.2
- Willing to develop solution: No
- Has workaround: Yes, use a type="text"
- High impact: Yes, Form Builder requires an email specific field prior to launch

**Comment by jraff** [comment]
To add to this issue, it looks to only be an issue on WebKit based browsers (Chrome, Safari).

**Comment by agorovyi** [comment]
The fix has been released: https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-input%403.0.3
