### ISSUE TITLE
[Button] add a "disabled" state

### ISSUE THREAD

**Issue by DDBanh** [telus/tds-core#1124]
There seems to be a missing feature for a button state that is "disabled". The purpose of this button is to let the user know that they have the option to continue once all the proper requirements are met. Until then, the button is "disabled" and will turn green once they are ready to move forward.

![Screen Shot 2019-06-19 at 11 31 46 AM](https://user-images.githubusercontent.com/48996540/59779257-eca43180-9285-11e9-8de0-8622f39d07c2.png)

**Comment by varunj90** [comment]
TDS core team will be revisiting all of our button designs along with this ask in August. Let us know if that works for you

**Comment by DDBanh** [comment]
Yep, that works. Thanks Varun.

**Comment by theetrain** [comment]
Thanks for the suggestion; we understand this is a very popular ask for the design system.

To help expedite the process, we would appreciate the following:

- A use case for needing disabled buttons
- What alternatives were considered to make the experience more informative and accessible to the customer. For example, "why is the button disabled? How will the customer be informed to remedy the situation? What actions would the customer want to take in that moment?"

**Comment by DDBanh** [comment]
Hey Enrico,

The disabled button is need when the consumer has to make a selection when given multiple choices. But when the consumer does not make all the choice required, they can not continue. The actions will be informed by copy before the process of the choice selection.

An alternative we thought about was the current TDS method, which is to hide the continue button until the process have been met.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
