### ISSUE TITLE
[ButtonGroup] Allowing unselected button groups by default

### ISSUE THREAD

**Issue by DDBanh** [telus/tds-core#1125]
Using the current button group, there seems to be missing a feature where the first selection is unselected. Not all the time, do we know or want to predetermine the selection. We want the user to dictate their own selection and flow within the completion process. Having the first option selected can sometimes cause the page length to be unnecessarily long, causing the user to miss important information below the viewable area, especially in mobile.

![Screen Shot 2019-06-19 at 11 35 51 AM](https://user-images.githubusercontent.com/48996540/59779581-8370ee00-9286-11e9-8a2c-bd2b28a4eedc.png)

## ACs

- Allow the ButtonGroup to be unselected by default

**Comment by theetrain** [comment]
Thanks for opening this issue. We will follow up with design recommendations.

**Comment by Christina-Lo** [comment]
As per discussion with @DDBanh there is a need for both button group that changes the form AND a single input in an existing form. Designs for reference https://telus.invisionapp.com/share/XDSE9WGV2T3#/screens

Next steps: do some research or test whether having the same visual design to one component should allow 2 different behaviours or do we need to discover a new design pattern

**Comment by Christina-Lo** [comment]
@DDBanh Chatted with CX on this and the unselected button group as a default or state is approved

**Comment by DDBanh** [comment]
Ayyyy thank you

**Comment by agorovyi** [comment]
This has been added in [@tds/core-button-group](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-button-group%402.1.0)
