### ISSUE TITLE
[ExpandCollapse] being able to pass a component to header copy

### ISSUE THREAD

**Issue by hamedmam** [telus/tds-core#1128]
## Description

- The older TDS version on ExpandCollapse component allows passing a component (function) to header which is currently in use in Site-Builder. for us to migrate to split components we require to support the functionality

## Recommendation

- header copy is able to take a component 

## Screenshots

![Screen Shot 2019-06-19 at 4 44 13 PM](https://user-images.githubusercontent.com/24867760/59799132-bbd9f180-92b1-11e9-936a-1b3c59808e40.png)

## Meta

- TDS component: @tds/core-expand-collapse
- Willing to develop solution: No
- Has workaround: No
- High impact: Yes (Blocked to remove older TDS version from Site-Builder)

**Comment by theetrain** [comment]
I reached out to @CSukhu,

There may be an opportunity to have the legal text fully inline with the Panel's content, rather than a clickable superscript within the Panel heading. It may also be a UX faux pas to have clickable content within an already-clickable area (the ExpandCollapse heading is a button).

I'll also reach out to Home Solutions for more input.

**Comment by theetrain** [comment]
Follow up from Jess from Home Solutions:

It is important to be able to add legal footnotes within an ExpandCollapse heading. Next step is to determine whether we want Footnotes to be interactive while within already-clickable area; the ExpandCollapse heading area is a button.

Let's also research how we should best display multiple Footnotes in an ExpandCollapse's subtext and tertiary text.

![image](https://user-images.githubusercontent.com/12798751/59883085-ec895c00-9381-11e9-8c19-8e1b530b9820.png)

**Comment by donnavitan** [comment]
Briefly discussed with @kittybourne and @gary, tagging them in here for reference and context. Another consideration would be to discover what the legal implication is if the legal footnote is only available within a content panel, is the user informed of the additional information if they don't bother opening the panel? Is the legal superscript enough without the link legal footnote?

**Comment by Christina-Lo** [comment]
@hamedmam After chatting with the content team, legal may need to be contacted by the original team that wants this request change. We want to know whether the superscript legally needs to be right beside the header or whether it can live within the expand collapse. 

From previous conversations about footnoteLink being on PriceLockUp, the footLink legally only needed to be as close to what they were referring to as possible, and not mandatory to be right next to it. Therefore, they would appear after the whole price lock up and not sprinkled throughout

**Comment by gary** [comment]
Hey @donnavitan wanted to let you know you initially pinged the wrong Gary. Probably autocorrects fault 😄 but I am sure your collaborator is wondering. Thanks!

**Comment by hamedmam** [comment]
@Christina-Lo I verbally got a response from Nika regarding this and seems like adding withLegal sup to the header adds complexity since TDS implemented the new legal component and it is clickable, therefore I decided to remove withLegal from header and luckily not many pages were using it so we are good now.

**Comment by Christina-Lo** [comment]
Thanks @hamedmam for that update, we'll close this issue then :)
