### ISSUE TITLE
[core-select] add 'hintPosition' and allow 'below' as option

### ISSUE THREAD

**Issue by Nintendot** [telus/tds-core#1131]
## Description

Current [core-select] has prop `hint` but it's position is fixed as `inline`, we would like to have `below` as an option, similar to how [core-input] handles `hint`

## Recommendation

Enable `hintPosition` and have `below` as an option

## Designs

n/a

## Meta

- TDS component: [core-select] 
- Willing to develop solution: Yes/No
- Has workaround: Yes/No 
- High impact: Yes/No 
- Designer/Developer Pair: Your name, your design/dev pair's name

**Comment by Nintendot** [comment]
cc: @rbrander

**Comment by agorovyi** [comment]
This is done and [released in v3.1.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-select%403.1.0)

**Comment by mejsullivan** [comment]
Does this "hint below" associate with the input field properly to provide an error notification to the screen reader user and keyboard user at the correct times?
