### ISSUE TITLE
[A11yContent] provide support for React.Fragment in dependent components

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#1154]
Originally reported by @ah-arch 

## Description

When supplying text to a component that supports `A11yContent`, React will throw a PropType error.

## Reproduction Steps

Using the following snippet:

```jsx
const linkCopy = (
  <React.Fragment>
    Click here
    <A11yContent>To learn more about phones</A11yContent>
  </React.Fragment>
)

const App = () => (
  <ChevronLink>
    {linkCopy}
  </ChevronLink>
)
```

Rendering `App` would yield a propType error since `ChevronLink` does not allow `React.Fragment` as a child.

## Workaround details

Nest the children directly:

```jsx
const App = () => (
  <ChevronLink>
    Click here
    <A11yContent>To learn more about phones</A11yContent>
  </ChevronLink>
)
```

## Recommendation

Enhance our `util-prop-types` module to ignore use of React.Fragment, but don't allow empty nodes.

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: @tds/core-chevron-link, @tds/core-button, @tds/core-button-link, etc
- Willing to develop solution: Yes/No
- Has workaround: Yes
- High impact: No 

## Screenshots

- Include any relevant screenshots

**Comment by theetrain** [comment]
Given that the workaround is sufficient, this will remain a lower priority unless more people request it. We welcome pull requests.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
