### ISSUE TITLE
FAQ's and Terms and conditions are overlapping on ipad air2 and IE browser for plans page

### ISSUE THREAD

**Issue by lizblasi** [telus/tds-core#1171]
Related to this story: [redacted]

Impacts:
- Internet Explorer 11
- Microsoft Edge

**Steps to replicate**

1. Navigate to plans page on staging environment : [redacted]. Observe the FAQ's section.

Actual Result:FAQ's section and Terms and conditions modules are overlapping and not clickable:

![image (3)](https://user-images.githubusercontent.com/52458479/60830482-8cadf600-a174-11e9-955b-c6dcad056d01.png)

## Description

- Description of the defect, observations
- The result you were expecting

## Reproduction Steps

1. View the `x` component
2. Click on the `y` link
3. Observe `z`

## Recommendation

- Your recommendation here

## Meta

- TDS component version: 
- Willing to develop solution: Yes/No
- High impact: Yes/No 

## Screenshots

- Include any relevant screenshots

**Comment by agorovyi** [comment]
Closing this issue as this is being resolved on the application side with @DewaldoDev
