### ISSUE TITLE
Add 'Warning' type of notification

### ISSUE THREAD

**Issue by Stu-Brown** [telus/tds-core#1177]
## Description

- I'd like an additional notification type with more prominence than the default state but less extreme than the Error type. The user would still be able to proceed forward.

## Recommendation

- Modify the "Error" alert to use an alternate icon (a yield sign maybe) and use the default notification background colour for the container

## Designs

<img width="835" alt="Warning_Notification" src="https://user-images.githubusercontent.com/36419784/60920774-fdcdd600-a266-11e9-874a-8a729d154038.png">

## Meta

- TDS component: 
- Willing to develop solution: Yes/No
- Has workaround: Yes/No 
- High impact: Yes/No 
- Designer/Developer Pair: Your name, your design/dev pair's name

**Comment by theetrain** [comment]
Need confirm from designer:

- This may depend on the forthcoming Utility 'warning' icon (see below)
- Is the proposal to **remove** the error variant in Notification and **replace** it with the 'warning' design above, OR, is the proposal to **add** a 'warning' variant?

### References 

Warning icon
![image](https://user-images.githubusercontent.com/12798751/60994051-af2f4300-a31d-11e9-89e0-9d336a0bf753.png)

New colours
https://telus.invisionapp.com/d/main#/console/17061609/353678787/preview

**Comment by Christina-Lo** [comment]
To answer the questions above the ask is to add another state (warning) for notification feedback and not replacing error or default. 

Another note on the Invision link above, is that @gkychow will update the icons in that document (outlines) to the design approved icons above (filled). 

@Stu-Brown We will be moving forward with adding a **warning** state

**Comment by varunj90** [comment]
TDS team will work on this once the feedback icon component is released.
JIRA: https://telusdigital.atlassian.net/browse/TDS-1471

**Comment by Christina-Lo** [comment]
@Stu-Brown 
**Released TDS Core DSM Library v2.3.3
Notifications (new addition and updates to existing)**
- Added 2 new components: Warning and Dismissible Warning
- Warning and Dismissible Warning use the new Warning Feedback Icon, Close Interactive Icon, and Rajah Light (yellow) background
- Updated existing Dismissible Error/Success with the Close Interactive Icon
- https://tds.telus.com/components/index.html#notification 
- Coded Release: https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-notification%403.0.0
