### ISSUE TITLE
[InputFeedback] reveal animation

### ISSUE THREAD

**Issue by brianlam1** [telus/tds-core#1180]
## Description

In UPC Checkout, InputFeedback is used extensively to notify the customer when there are issues in validation. As of right now, there is no animation to signal to the customer that something is happening to the system. InputFeedback appears on the screen instantly and changes the UI around without the customer potentially understand what just happened.

## Recommendation

- Add motion to the InputFeedback
- Allow InputFeedback to float up from the InputField
- Add a fadeIn transition
- Add an easeIn motion

## Designs

Replicate what was showcased in Brand Resources: https://www.telus.com/en/brand-resources/design/motion-standards?linktype=ge-meganav#feedback

## Meta

- TDS component: '@tds/core-input-feedback'
- Willing to develop a solution: Yes
- Has workaround: No
- High impact: No
- Designer/Developer Pair: Brian Lam, Bo Xing

**Comment by theetrain** [comment]
Hi Brian,

Thanks for the suggestion and willingness to contribute. We encourage you to bring forward the following:

1. A proposed design and animation spec (it can be fully animated, or described as timings)
2. Some basic acceptance criteria (can be bullet point). Be sure to account for customers who set 'reduced motion' on their operating systems to not see the animations

Afterwards, we'll work together to get CX/TDS approval and then a pull request can be made.
cc @catherinetelus

**Comment by xingbo828** [comment]
@theetrain I actually found this on TDS doc
https://www.telus.com/en/brand-resources/design/motion-standards

Is this the design and animation spec?

**Comment by theetrain** [comment]
@xingbo828 correct, that is our official motion standards doc. It is also referenced from the TDS site: https://tds.telus.com/design/motion.html

**Comment by brianlam1** [comment]
@gkychow is preparing the design spec for us. I'll ask him to post here once he's done.

**Comment by gkychow** [comment]
![notifications](https://user-images.githubusercontent.com/16300159/61771661-4330ee00-ada5-11e9-972b-ff49ba387a39.gif)

Inputs (starts at 0 seconds)
- pushed down 50px (duration: 0.15 seconds, ease-both)

Notification Background (starts at 0.03 seconds)
- Height grows from 1px to 40px (from the centre, duration: 0.20 seconds, ease-both)

Notification text (starts at 0.10 seconds)
- Opacity changes from 0% opacity to 100% (duration: 0.20 seconds, ease-both)

**Comment by varunj90** [comment]
hey @brianlam1 what's the status on this? based on Gary's response, are you going ahead with the animation via PR?

**Comment by varunj90** [comment]
hey @brianlam1 what's the latest on this issue? is this already implemented by your team?

**Comment by varunj90** [comment]
reaching out to @brianlam1 on slack

**Comment by brianlam1** [comment]
No update at this time. Still in our backlog.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
