### ISSUE TITLE
Step tracker missing symbol and problematic step title treatment

### ISSUE THREAD

**Issue by jesssanson** [telus/tds-core#1181]
**Problem:** trying to use step tracker in TDS quickly and efficiently

**Description of issues:**

1. Can't swap the circles for the checkmark/completed symbol
2. The title text gets pushed down and bolded when its in focus, when the case size shouldn't change even when its in focus

**Screenshots:**

![Screen Shot 2019-07-12 at 11 02 59 AM](https://user-images.githubusercontent.com/49687236/61138403-7619de80-a495-11e9-8adf-3b456de02b7e.png)
![Screen Shot 2019-07-12 at 11 03 13 AM](https://user-images.githubusercontent.com/49687236/61138404-7619de80-a495-11e9-8009-b507ad2d2b2b.png)

TDS v 2.2.1

**Comment by donnavitan** [comment]
Hello @jesssanson,

Thanks for flagging an opportunity to improve the StepTracker component as used from the DSM library. We will review and prioritize accordingly.

If there's anything else, please let us know.

**Comment by serenechen-UX-Billing** [comment]
Hi guys, in Sketch can we have an option to simply adjust the stepper control to a customized number of steps and the layout will be adjusted accordingly? Thanks!

**Comment by donnavitan** [comment]
@jesssanson @serenechen-UX-Billing 

Updates to the StepTracker have resolved these requests. Please see the latest release of the TDS Core DSM library for the updated StepTracker component. Release notes: https://telus.invisionapp.com/dsm/telus/tds-core/releases

Thank you for sharing your feedback to help fix and enhance! Closing this issue.
