### ISSUE TITLE
Flex Grid component not responsive on mobile screens

### ISSUE THREAD

**Issue by Berjesty** [telus/tds-core#1185]
## Description

Flex Grid not responsive on mobile

- Description of the defect is that content on Billing page gets cut in half the screen and wraps to next line before reaches end of the line.  
- Expected result is for the content to reach the end of the line until right margin is reached then wrap to the next line. 

## Reproduction Steps

1. View the Billing page on mobile device

## Screenshots
![Screenshot_20190712-100332](https://user-images.githubusercontent.com/25160096/61242242-2e07ef80-a713-11e9-8839-1bb29139729e.png)
![Screenshot_20190712-100732](https://user-images.githubusercontent.com/25160096/61242267-424bec80-a713-11e9-9244-075ccbc30626.png)

![billing](https://user-images.githubusercontent.com/25160096/61242883-cc488500-a714-11e9-9a01-ecd6cbeda7e6.png)

**Comment by jraff** [comment]
Closing for now.

Their implementation uses an old "unresponsive" version of our `FlexGrid` combined with `Responsive`. They need to allocate some time to rewrite this page using the more recent responsive `FlexGrid`.'
@Jeffrey-Chang please circle back if you're unable to resolve on your end.

CC: @samcheam
