### ISSUE TITLE
[Tooltip][StandaloneIcon] Clicking on tooltip button submits the form

### ISSUE THREAD

**Issue by ah-arch** [telus/tds-core#1187]
## Description

- When the tooltip is used in a form, clicking on it submits the form
- The `button` is missing the `type` prop, and thus [defaults](https://www.w3schools.com/tags/tag_button.asp) to the browser's behaviour for buttons

## Reproduction Steps

1. `VIEW CODE` for the `Tooltip` [component](https://tds.telus.digital/components/index.html#tooltip)
2. Wrap the code with a `<form></form>`
3. Click on the tooltip icon
4. Observe that the form submits and the page reloads

<img width="825" alt="Form wrapper" src="https://user-images.githubusercontent.com/4450690/61391106-05563600-a88a-11e9-8e0d-f90437bdd868.png">

## Workaround

- Currently working around it by checking the submit event and preventing a submit when it is not from the known submit button

## Recommendation

- Add `type="button"` on the `StandaloneIcon` in [Tooltip](https://github.com/telus/tds-core/blob/a759942114e36b8cea38fd34fc09ec0ce4d2eca9/packages/Tooltip/Tooltip.jsx#L149-L157)

## Meta

- TDS component version: `@tds/core-tooltip@4.0.2`
- Willing to develop solution: Yes
- High impact: Yes

**Comment by jraff** [comment]
@ah-arch Fixed with `@tds/core-tooltip@4.0.3` https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-tooltip%404.0.3
