### ISSUE TITLE
TELUS Drive+ icons 

### ISSUE THREAD

**Issue by edilege** [telus/tds-core#1190]
## Description

- For the 3 features: Add multiple vehicles, roadside assistance and car battery there are not current icons that we can leverage on the page. 

## Recommendation

- Gary Chow designed the recommended icons. Please find the screenshot of the features component and the proposed new svgs for the missing icons. 

## Designs

 <img width="498" alt="Screen Shot 2019-07-19 at 2 13 30 PM" src="https://user-images.githubusercontent.com/48288654/61556591-2b1d3f80-aa30-11e9-96ef-ea62fd73c989.png">
Crain truck svg:file:///Users/x214643/Desktop/Crain%20Truck.svg
Battery svg: file:///Users/x214643/Desktop/Battery.svg
Add multiple vehicles svg: file:///Users/x214643/Desktop/Sedan.svg

## Meta

- TDS component: 
- Willing to develop solution: Yes
- Has workaround: Yes/No 
- High impact: Yes 
- Designer/Developer Pair: Ece Dilege, Gary Chow

**Comment by varunj90** [comment]
This is part of TDS backlog and will be done in 1st half of August: https://telusdigital.atlassian.net/browse/TDS-1406

**Comment by varunj90** [comment]
This has been released: https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.2.0
