### ISSUE TITLE
Icon addition - Diamond

### ISSUE THREAD

**Issue by k-grimsley** [telus/tds-core#1198]
## Description

Currently, there is no diamond icon available through the `<DecorativeIcon />` icons, but it is available through the larger TELUS icon set. It has been requested to be available to site builder sites. In order to use it with the site builder block `<BlockIcon />`, this icon must be available through the `<DecorativeIcon />`.

## Recommendation

Add the Diamond icon too the list of available `<DecorativeIcon />` icons.

## Designs

Proposed SVG:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="48" height="48" version="1.1" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
    <g transform="scale(1.6)">
        <path fill="#4B286D" d="M14.5,29.5c-0.169,0 -0.327,-0.086 -0.419,-0.228l-14,-21.5c-0.142,-0.217 -0.094,-0.506 0.11,-0.666l7.637,-6c0.088,-0.068 0.196,-0.106 0.309,-0.106h12.727c0.112,0 0.221,0.038 0.309,0.106l7.637,6c0.204,0.16 0.252,0.449 0.11,0.666l-14,21.5c-0.093,0.142 -0.251,0.228 -0.42,0.228Zm-13.331,-21.89l13.331,20.474l13.331,-20.474l-7.141,-5.61h-12.38l-7.141,5.61Z"></path>
        <path fill="#4B286D" d="M28.5,8h-28c-0.276,0 -0.5,-0.224 -0.5,-0.5c0,-0.276 0.224,-0.5 0.5,-0.5h28c0.276,0 0.5,0.224 0.5,0.5c0,0.276 -0.224,0.5 -0.5,0.5Z"></path>
        <path fill="#4B286D" d="M14.5,28.863c-0.22,0 -0.421,-0.146 -0.482,-0.367l-5.728,-20.863c-0.037,-0.139 -0.015,-0.286 0.064,-0.405l3.818,-5.863c0.151,-0.232 0.462,-0.295 0.691,-0.146c0.231,0.15 0.297,0.46 0.146,0.691l-3.695,5.674l5.668,20.646c0.073,0.267 -0.084,0.542 -0.35,0.615c-0.044,0.012 -0.088,0.018 -0.132,0.018Z"></path>
        <path fill="#4B286D" d="M14.5,28.863c-0.044,0 -0.088,-0.006 -0.133,-0.018c-0.266,-0.073 -0.423,-0.349 -0.35,-0.615l5.668,-20.646l-3.695,-5.675c-0.15,-0.231 -0.085,-0.541 0.146,-0.691c0.23,-0.149 0.541,-0.086 0.691,0.146l3.818,5.863c0.078,0.119 0.101,0.267 0.063,0.405l-5.728,20.863c-0.059,0.223 -0.26,0.368 -0.48,0.368Z"></path>
    </g>
</svg>
```

- Screenshots
- Sketch file
- Link to Invision

## Meta

- TDS component: @tds/core-decorative-icon
- Willing to develop solution: Yes
- Has workaround: No
- High impact: Yes
- Designer/Developer Pair: Michelle Wu/Kevin Grimsley

**Comment by theetrain** [comment]
Just a follow up: we added Diamond to the scope of our forthcoming DecorativeIcon enhancement: https://telusdigital.atlassian.net/browse/TDS-1406

**Comment by theetrain** [comment]
Update: we will be adding new icon requests in mid-August, 2019.

**Comment by jraff** [comment]
@k-grimsley Can you please provide the usage guidelines for the Diamond icon?

**Comment by grimsleyk** [comment]
Hi @jraff, for the Diamond Icon:

**Section**: Business
**Usage Guidelines**: Earning potential

**Comment by varunj90** [comment]
This has been released https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.2.0
