### ISSUE TITLE
New: Minor UI issues for tooltip

### ISSUE THREAD

**Issue by vkyt** [telus/tds-core#1214]
## Description

Small UI issues found while testing tooltip.  See attached screenshots for example.

1. Tooltip bubble dialog graphic is showing the square composition at the tip
2. IE and Edge has some border issues with the bubble dialog
3. See last attached image for edge alignment between the input box and the tooltip.

Original Jira story: https://telusdigital.atlassian.net/browse/CB-197

## Reproduction Steps
- Render tooltip component
- Click on the tooltip ( ? ) icon
- See attached screenshots for UI behavior

Same behaviours can be observed on https://tds.telus.com/components/index.html#tooltip 

## Meta

- TDS version (npm or DSM):    @tds/core-tooltip "4.0.3"
- Willing to develop solution: No
- Has workaround:  No
- High impact: No

## Screenshots

<img width="471" alt="Tooltip - Chrome" src="https://user-images.githubusercontent.com/5015168/62567013-470a4900-b858-11e9-9218-eaebeb44560e.png">

![Tooltip - Edge](https://user-images.githubusercontent.com/5015168/62567527-55a53000-b859-11e9-9af5-e44dae8590da.png)

<img width="1004" alt="Tooltip - Firefox" src="https://user-images.githubusercontent.com/5015168/62567015-470a4900-b858-11e9-9a72-628fcd04bcf8.png">

![Tooltip - IE](https://user-images.githubusercontent.com/5015168/62567566-66ee3c80-b859-11e9-9baa-a676f0032f01.png)

<img width="93" alt="Tooltip - Safari" src="https://user-images.githubusercontent.com/5015168/62567018-483b7600-b858-11e9-9bfd-4bd738e2e01a.png">

### Alignment Issue
<img width="680" alt="Tooltip - Alignment" src="https://user-images.githubusercontent.com/5015168/62568115-8afe4d80-b85a-11e9-9185-c653cbd14412.png">

**Comment by theetrain** [comment]
This is similar to #534

**Comment by theetrain** [comment]
Update; this is marked as low priority since the visual impact across browser was deemed as not a high impact on the customer experience. A solution could be replacing the CSS bubble with an SVG for more consistent shadows across all browsers.

We welcome any developers to contribute this fix given the Tooltip is already designed.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
