### ISSUE TITLE
[Tooltip] Documentation of use cases 

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-core#1229]
## Description

- With the upcoming changes to the way Standalone (now Interactive) icons work, we are implementing accessibility as one of our major considerations while designing for them. 
- as the tooltip can work as a stand alone icon used anywhere, with text or without, we want to be able to identify as many of the current use cases as possible since our touchpoint standard for these icons have expanded immensely (from 32px to 40px)

## Designs

![Screen Shot 2019-08-12 at 3 26 01 PM](https://user-images.githubusercontent.com/42220619/62892177-9ac3d900-bd15-11e9-90f3-b334b69f18b6.png)

## Next steps

- Once we have a collection of use cases, designs, screen captures, we can create an Interactive icon that can be encompasses all use cases

**Comment by theetrain** [comment]
This will be addressed in the forthcoming InteractiveIcon.
