### ISSUE TITLE
ExpandCollapse.Panel tertiaryText prop accepts only string and not node element.

### ISSUE THREAD

**Issue by kavya-kathi-reddy** [telus/tds-core#1240]
## Description

`tertiaryText` prop on`ExpandCollapse.Panel` is defined to only accept value of type `string`. Due to which we are unable to render any react `node element` on `ExpandCollapse.Panel` to the right that wraps properly with panel header on smaller resolutions on mobile/other devices. 

We want to render Notification component that contains `error notification message` on item level on `ExpandCollapse.Panel` to the right through `tertiaryText` prop.

Also if `tertiaryText` prop is given string `Product unavailable`, div holding this string is wrapping in two lines as shown in screenshot below (both in mobile and desktop view). It's because the ExpandCollapse `header` div element which is set to `width: 100%` is pushing `tertiaryText` prop to wrap in two lines.
![image](https://user-images.githubusercontent.com/52928227/63464291-f0426900-c42c-11e9-93a8-53b1545d6658.png)

## Recommendation

- `ExpandCollapse.Panel` component `tertiaryText` prop to accept a node instead of a string. This was once requested as part of issue https://github.com/telus/tds-core/issues/762 i . the past.
- Can you adjust width of ExpandCollapse `header` div element so that `tertiaryText` is displayed in one line to the right.
## Designs
Please refer to screen shots below for expected view on desktop and mobile (https://telus.invisionapp.com/share/NTS5H2KMYJC#/screens/378789084_Notification-_Price_Change_MOB).

https://telus.invisionapp.com/share/NTS5H2KMYJC#/375313021_NEW_03_Tallboy_Complex_FREE_-_Updated_Notifications_2

![image](https://user-images.githubusercontent.com/52928227/63400609-6b127200-c3a2-11e9-957e-8e9509cfc2b6.png)

We tried to add Notification component (with position set to `absolute`) to display error message as a sibling to ExpandCollapse component. It looks good on desktop view but doesn't wrap properly on mobile view as shown below.

![image](https://user-images.githubusercontent.com/52928227/63400634-82e9f600-c3a2-11e9-9804-80b735e900b0.png)

## Meta

- TDS component:@tds/core-expand-collapse
- Willing to develop solution: No
- Has workaround: Yes (Displaying error message as part of Panel header name temporarily)
- **High impact: Yes**

**Comment by Christina-Lo** [comment]
As per discussion with @catherinetelus, the designs have changed to utilize a different pattern similar to this [TDS-community issue](https://github.com/telus/tds-community/issues/258) so we will be closing this
