### ISSUE TITLE
TermsAndConditions returns error when a node is included in the indexedContent array

### ISSUE THREAD

**Issue by johntwigg** [telus/tds-core#1243]
TermsAndConditions returns error when a node is included in the indexedContent array.

Error received:
index.es.js:286 Uncaught TypeError: c.split is not a function
    at renderContent (index.es.js:286)
    at index.es.js:1001
    at Array.map (<anonymous>)
    at index.es.js:998
    at index.es.js:1965
    at Transition.render (index.es.js:734)
    at finishClassComponent (react-dom.development.js:17039)
    at updateClassComponent (react-dom.development.js:16994)
    at beginWork$1 (react-dom.development.js:18505)
    at HTMLUnknownElement.callCallback (react-dom.development.js:347)

The array for indexedContent has 1 Component:
<WithMarkdown content={content} />

WithMarkdown is our own component that returns a Markdown React component:
const Component = ({
  content, allowedTags, renderOverrides, scrollEvent, showChevron
}) => {
  return (
    <Markdown text={content} tags={{ html: 'box' }} onIterate={handleIterate(renderOverrides, allowedTags, scrollEvent, showChevron)} />
  )
}

It seems that the error is encountered even if I send a TDS component instead of our Markdown component. For verification I tried creating a TDS <Heading> component and passing it as the first element of an array into indexedContent and encountered the same error.

So I suspect the issue is when there are nodes (as opposed to just Strings) in the array passed in indexedContent.

From the TDS documentation (https://tds.telus.com/components/index.html#terms-and-conditions), the indexedContent should allow Strings or Nodes. ('An array of nodes, strings, or a combination to be displayed in an ordered list')

**Comment by theetrain** [comment]
This has been resolved in [@tds/core-terms-and-conditions@1.0.17](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-terms-and-conditions%401.0.17) and will be included in redux-contentful 6.0.5. Thanks for reporting!
