### ISSUE TITLE
Success notification isn't obvious enough for users

### ISSUE THREAD

**Issue by roannaca** [telus/tds-core#1253]
## Question

Is there a more prominent style available for the success message notification? I'm a UX consultant on Project Odyssey (TELUS business ordering & quoting), and we've been receiving feedback from usability testing that the success message pale green shade isn't very obvious. Testing has shown that up to 30-40% of users don't notice it. 

## Related components

- @tds/core-notification

## Screenshots

<img width="965" alt="Screen Shot 2019-09-06 at 8 34 22 AM" src="https://user-images.githubusercontent.com/54993646/64440984-d71ef680-d081-11e9-9291-72be19f5667e.png">

**Comment by kittybourne** [comment]
@roannaca can you share the testing results and page or invision designs used for the test?

**Comment by roannaca** [comment]
Hi Kitty, apologies for the delay in my response. Looking over usability testing cycles from the past year, we tested the success message twice and had the same results that some users didn't notice the message. When the message was pointed it, users commented that the shade of green was pale and didn't stand out. I should note that quoting/ ordering TELUS' business products can be a complex process, and some screens require the display of a lot of information, so it's important to us that the success message stands out. 

1. After adding multiple service locations (addresses) to an order, 2 out of 5 users didn't see the message. The user can check the checkboxes for one or more addresses and then click an "Add to order" button. The success message is displayed near the top of the screen:
https://telus.invisionapp.com/d/main#/console/14887657/310350648/preview
p/w: cr1tt3rs

2. After booking installation appointments, 2 out of 6 users didn't see the message. The user must select a date and click a "Book now" button to book. The success message is displayed at the top of the "appointments to reserve" section of the screen:
https://telus.invisionapp.com/d/main#/console/16916667/352897072/preview
p/w: Panther

Thanks so much for being open to our feedback and please let us know if you decide to update the styling.

**Comment by theetrain** [comment]
Update: TDS and CX will investigate improving the entire notification experience in the near future.

**Comment by theetrain** [comment]
This is potentially related to #1262. We will uncover ways to reveal information and capture sighted users' attention.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
