### ISSUE TITLE
Typography styles that are not in TDS yet

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-core#1254]
## Problem statement

Gathering text styles to be contributed back into TDS for other designers to use 

## Recommendation

- Description of the proposed solution

## Design intent

(This space is intentionally left blank. The motivation and design intent go here.)

## Designs

- Screenshots
- Sketch file
- InVision links

## Acceptance criteria

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes/No
- Willing to develop solution: Yes/No
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): Yes/No (link)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

**Comment by elenaverling** [comment]
![Typography XS @2x](https://user-images.githubusercontent.com/39060415/65145061-907db480-da10-11e9-97bd-b48695d9c150.jpg)
![Typography L @2x](https://user-images.githubusercontent.com/39060415/65145064-907db480-da10-11e9-9db3-d0cb210dfa79.jpg)

Mobile suggestion:
Font Size: 16
Line Height: 26
(Works best with average content width of 343px)

Desktop suggestion:
Font Size: 16
Line Height: 28
(Works best with average content width of 768px)

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
