### ISSUE TITLE
[FeedbackIcon] new icon set to represent other forms of feedback

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-core#1265]
## Description

As a user of TDS, there doesn't seem to be an icon or pattern of feedback icons that can be used outside of Notifications/input feedback

## Recommendation

- Creating a set of icons that aren't as "strong" as NotificationSuccess, NotificationError, NotificationWarning but have more visual prominence than Checkmark and Times

## Designs

- Screenshots
- Sketch file
- Link to Invision

## Meta

- TDS component: 
- Willing to develop solution: Yes/No
- Has workaround: Yes/No 
- High impact: Yes/No 
- Designer/Developer Pair: Your name, your design/dev pair's name

**Comment by catherinetelus** [comment]
![Screen Shot 2019-09-20 at 12 51 24 PM](https://user-images.githubusercontent.com/16903874/65348121-724dbb00-dbae-11e9-83f9-ac096fba525c.png)

We are looking into icons to accompany text labels indicating whether items are available in store or not. Prefer not to rely on colour variances in icon alone with consideration to accessibility. Also prefer not to use current triangle warning icon, for "limited stock" scenario as this will be a very popular scenario in most listed stores.

**Comment by theetrain** [comment]
Thanks for the direction, @catherinetelus. If you are able to provide icon designs, we can include them in the FeedbackIcon set to be used for more use cases.

cc @gkychow

**Comment by catherinetelus** [comment]
@theetrain I'm using existing TDS icons in the example above, but will wait for Gary's feedback. Is Gary on Github, I'm not seeing him when I look for names/people to flag?

**Comment by kittybourne** [comment]
radio button icon is confusing with another status icon above, recommendation is to just keep radio button and just use label to show "in stock" or "no stock" or "low stock"

other options for icons if necessary: orange triangle with exclamation mark, no entry sign but placement should be same indentation as store info, not with radio button

example with number of stock available:
<img width="870" alt="Screen Shot 2019-10-01 at 11 34 50 AM" src="https://user-images.githubusercontent.com/6434886/65989976-8eb7e600-e43f-11e9-8664-0c9e58cb9fa6.png">

**Comment by kittybourne** [comment]
another option to display inventory by bars:

<img width="311" alt="Screen Shot 2019-10-01 at 2 41 31 PM" src="https://user-images.githubusercontent.com/6434886/65990496-8e6c1a80-e440-11e9-9da6-a86eb74314e1.png">

**Comment by catherinetelus** [comment]
@kittybourne we were concerned about "no entry" icon's roundness being confusing with the radio button's circle. Also, "warning triangle" icon seem very severe for low stock, in particular for our scenario, most of the stores will have low stock (we were told there is only ever a max of 5 at each location). 

Kitty: "radio button icon is confusing with another status icon above"
Which status icon are you referring to, the checkmark, horizontal line, or "x"? 
We are unable to show inventory numbers due to fraud/security reasons.

**Comment by theetrain** [comment]
Update: @catherinetelus and @kittybourne will connect and consolidate the design requirements for representing 'low stock'.

**Comment by kittybourne** [comment]
-checkmark is slightly too big
-for "low stock" highlight text, talk to Thiveya/Lynne? they are looking at same statuses
-drop "Available in store" text size to 14px, same as rest of nested content

@catherinetelus

**Comment by Christina-Lo** [comment]
@catherinetelus Are you able to attach latest designs on this based on Kitty's feedback?

**Comment by catherinetelus** [comment]
Attached is the latest version of the store list with status icons. We restructured the content a tad and rebalanced (reduced the size of the icons a tad). Let me know if you still feel like the "Available" status needs to reduced to 14px @kittybourne (my miss).
![Screen Shot 2020-01-08 at 9 48 30 AM](https://user-images.githubusercontent.com/16903874/71990744-eebde580-3201-11ea-9815-f04c3042042d.png)

**Comment by Christina-Lo** [comment]
@catherinetelus thanks so much for updating with designs! As there is no longer a need for the new icon set I will close this issue. I will let you and CX work out the sizing of the label text. Please feel free to re-open the issue if you find a need to for the set again.
