### ISSUE TITLE
BRC icons

### ISSUE THREAD

**Issue by hamedmam** [telus/tds-core#1274]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
3. If your design lead has approved this change, please note their name: N/A
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: ... @elenaverling to provide details

Usage criteria: ...

![Screen Shot 2019-10-01 at 3 59 59 PM](https://user-images.githubusercontent.com/24867760/66003649-bc6b5200-e474-11e9-8b3f-2a7bee263445.png)

**Comment by hamedmam** [comment]
will need to get some help from @elenaverling to complete this ticket, for now, I opened the issue so we can kick off the conversations

**Comment by theetrain** [comment]
Sounds good Hamed. Next steps:

* [ ] Please have @gkychow comment on this issue when the icons are approved.
* [ ] Have your appointed designer provide SVGs to the TDS team (you can attach them here in a zip or tarball)

Once these items are fulfilled, we'll prioritize your request.
cc @elenaverling

**Comment by elenaverling** [comment]
Hello! On the BRC I have two pages that use icons as click through’s to the text beneath it:
https://www.telus.com/en/brand-resources/technology/reference-architecture
https://www.telus.com/en/brand-resources/content/grammar-mechanics

I added the grey circle for two reasons;
1. Easier to press on mobile
2. Has a UI differentiation from regular TELUS icons that are not used as links.

My initial request was to include a hover state for these SVGs. Not sure if we have a hover state standard, but I’d be happy to replicate the exact same hover state we use for Preview Cards (grey drop shadow, icon increases in size by 10%) 

Happy to take @gkychow or TDS's lead on this.

**Comment by gkychow** [comment]
@elenaverling @theetrain - icons look good to me!

**Comment by elenaverling** [comment]
Okay great! Next question is for TDS. Should I be using the same icons that already exist in TDS or should I make sure to use different ones? The icons I am using are 32px each in purple, surrounded by a 1px grey circle border at size 72 x 72px. Can you advise what the hover state you'd prefer me to use?

**Comment by elenaverling** [comment]
I've discussed my options with @Christina-Lo directly, and she's advised against using icons as links. For this reason, @hamedmam you don't need to action anything on this ticket. I'll go through the icons on both BRC pages and replace them with as many existing TDS icons (without grey border) and any icons I think we need, I will suggest them to TDS on this page: https://github.com/telus/tds-core/issues/new?template=icon_template.md

Thanks everyone!

**Comment by hamedmam** [comment]
Sounds good, thank you Elena for updates, closing

**Comment by hamedmam** [comment]
hey @varunj90 any update on this ?
