### ISSUE TITLE
@tds/core-colours issue

### ISSUE THREAD

**Issue by jarriaza-telus** [telus/tds-core#1278]
I am getting an issue trying to run npm install command, I have some libraries from @tds, and they have @tds/core-colours as dependency, the issue is that npm is indicating an issue with @tds/colours, so, I am not able to install and to compile.

`> @tds/core-colours@2.2.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\@tds\core-colours
> node ./deprecate.js; exit 0;

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Users\user\AppData\Roaming\npm\node_modules\@tds\core-colours\deprecate.js;'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tds/core-colours@2.2.0 postinstall: `node ./deprecate.js; exit 0;`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tds/core-colours@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-08T13_37_35_918Z-debug.log`

**Comment by agorovyi** [comment]
Hello @jarriaza-telus. Thanks for creating an issue.

Could you please provide what versions of `node` and `npm` you have installed?

Have you tried to run `npm ci` instead of `npm install` in your repository?

`npm install` will always try to upgrade packages to their latest caret `^` version and will modify your `package-lock.json` where `npm ci` will respect the lock file and install all dependencies according to it.

**Comment by jarriaza-telus** [comment]
> Hello @jarriaza-telus. Thanks for creating an issue.
> 
> Could you please provide what versions of `node` and `npm` you have installed?
> 
> Have you tried to run `npm ci` instead of `npm install` in your repository?
> 
> `npm install` will always try to upgrade packages to their latest caret `^` version and will modify your `package-lock.json` where `npm ci` will respect the lock file and install all dependencies according to it.

I have npm 6.4.1 and node 10.13.0
I am not able to run npm ci because I deleted node_modules and package-lock.json to try to install packages, and npm ci requires the package-lock.json

**Comment by agorovyi** [comment]
Are you able to revert back a deletion of `package-lock.json` file?

**Comment by jarriaza-telus** [comment]
> Are you able to revert back a deletion of `package-lock.json` file?

I reverted it, and I ran npm ci command, but I'm still getting the same issue.

**Comment by agorovyi** [comment]
Could you reach out to me on slack: `agorovyi` is my username

**Comment by agorovyi** [comment]
I've been trying to reproduce the issue but we have different development environments.

**Comment by jarriaza-telus** [comment]
> I've been trying to reproduce the issue but we have different development environments.
> 
> Could you reach out to me on slack? `agorovyi` is my username

Okay, I'll contact you, but, which channel should I use?

**Comment by eyning** [comment]
Looks like the bash shell we're using on windows doesn't like the console warning that was added: https://github.com/telus/tds-core/commit/7532318f591b37d4d9eedd1a73936674ba34b502

t896649@L094342 MINGW64 /
$ node -e "console.warn('[TDS] @tds/core-colours: The following colours have been deprecated, please see https://tds.telus.com/components/index.html#!/Colours for their alternatives:  colorShark,  colorShuttleGrey,  colorAthens,  colorGainsboro,  colorDarkRaja,  colorRaja  colorLightRaja')"
bash: !/Colours: event not found

Changing the string from ` to ' formatted and removing the exclamation mark seems to play better: 

t896649@L094342 MINGW64 /
$ node -e "console.warn('[TDS] @tds/core-colours: The following colours have been deprecated, please see https://tds.telus.com/components/index.html#/Colours for their alternatives:  colorShark,  colorShuttleGrey,  colorAthens,  colorGainsboro,  colorDarkRaja,  colorRaja  colorLightRaja')"
[TDS] @tds/core-colours: The following colours have been deprecated, please see
https://tds.telus.com/components/index.html#/Colours for their alternatives:  colorShark,  colorShuttleGrey,  colorAthens,  colorGainsboro,  colorDarkRaja,  colorRaja  colorLightRaja

**Comment by eyning** [comment]
Can we raise this issue to a higher priority? Currently blocking all windows users.

**Comment by jonathanpalma** [comment]
I don't think this error is related to the use of template literals. 

![image](https://user-images.githubusercontent.com/12414771/66419383-478e9f80-e9c1-11e9-85e8-456ad935888f.png)

**Comment by agorovyi** [comment]
The fix has been released in [core-colours v2.2.1](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-colours%402.2.1)
