### ISSUE TITLE
New icon for Billing roundup payment (emergency) 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1279]
## Description

The billing page and the mobile app will have soon **a new feature: a section for billing roundup donation.**
The design for desktop/app is already created and we would like to have a consistent design with a similar component. 
For this new feature, **we created a new icon** (mix of the current heart icon and hand icon we have in our DSM library).

## Recommendation

Since Telus app doesn't work with TDS, the app team will develop it design with that icon quickly (and very soon).
We have to develop that icon as well from our side (web) to be consistent for the user and between app/web.

## Designs

- Sketch file of web design:
https://telus.invisionapp.com/d/main#/console/18442210/386873135/preview
https://telus.invisionapp.com/d/main#/console/18442210/386873133/preview
https://telus.invisionapp.com/d/main#/console/18442210/386873132/preview
- Sketch file of app design:
https://telus.invisionapp.com/d/main#/console/18441110/383279317/preview
https://telus.invisionapp.com/d/main#/console/18441110/383273838/preview
https://telus.invisionapp.com/d/main#/console/18441110/383273833/preview
- Screenshots:
<img width="81" alt="Screen Shot 2019-10-08 at 12 38 54 PM" src="https://user-images.githubusercontent.com/44266628/66423007-c80cca80-e9d8-11e9-8c57-d335d4b50bb6.png">
<img width="541" alt="Screen Shot 2019-10-08 at 2 31 36 PM" src="https://user-images.githubusercontent.com/44266628/66423006-c7743400-e9d8-11e9-96d8-e61b1301a02f.png">

## Meta

- TDS version: v1.2.0
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: Yes

**Comment by varunj90** [comment]
hey @Mariefhrmnn please open an icon request using the template: https://github.com/telus/tds-core/issues/new?template=icon_template.md
