### ISSUE TITLE
New icon for Billing roundup payment (urgent)

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1280]
## Actions
1. Did you check to see if there are icons available in TDS that can be used instead? **Yes**
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? **Yes**
3. If your design lead has approved this change, please note their name: [design lead name]
4. If the art director (@Gary) has approved this change, please have them comment on this issue: **the heart and hand icons are in Gary's icon suite for Telus. Gary already saw this project**

## Guidelines

Icon name: 
**'Donation'** or **'Billing roundup donation'**

Usage criteria: 
**Used as a decorative icon or to symbolize the donation option**

Comments: 
The billing page and the mobile app will have soon **a new feature: a section for billing roundup donation.**
The design for desktop/app is already created and we would like to have a consistent design with a similar component.
For this new feature, we created a new icon (mix of the current heart icon and hand icon we have in our DSM library).
Since Telus app doesn't work with TDS, the app team will develop it design with that icon quickly (and very soon).
We have to develop that icon as well from our side (web) to be consistent for the user and between app/web.

Sketch file of web design:
https://telus.invisionapp.com/d/main#/console/18442210/386873135/preview
https://telus.invisionapp.com/d/main#/console/18442210/386873133/preview
https://telus.invisionapp.com/d/main#/console/18442210/386873132/preview
Sketch file of app design:
https://telus.invisionapp.com/d/main#/console/18441110/383279317/preview
https://telus.invisionapp.com/d/main#/console/18441110/383273838/preview
https://telus.invisionapp.com/d/main#/console/18441110/383273833/preview

**Comment by varunj90** [comment]
based on discussion with @gkychow @Mariefhrmnn and Cherry! we are going ahead with Hold Heart
<img width="1340" alt="Screen Shot 2019-10-08 at 3 35 06 PM" src="https://user-images.githubusercontent.com/3495961/66427578-45890880-e9e2-11e9-951c-576fe00c0738.png">

**Comment by varunj90** [comment]
hey @Mariefhrmnn we will release this tomorrow!

**Comment by jraff** [comment]
@Mariefhrmnn This has been implemented with [@tds/core-decorative-icon@2.4.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.4.0)
