### ISSUE TITLE
DecorativeIcons don't apply the size to width and height of svg 

### ISSUE THREAD

**Issue by hamedmam** [telus/tds-core#1284]
DecorativeIcons don't apply the size to width and height of svg.
I chatted with Jordan and Anatolii about this issue and we did not really figure out what causes this but this is definitely only happening on SSR using styled-components, as it works fine in TDS play ground.

The solution to this would be to explicitly apply size in `px` to the styled-component

- TDS component version: @tds/core-decorative-icon@2.3.2
- Willing to develop solution: Yes
- High impact: Yes

## Screenshots
<img width="847" alt="Screen Shot 2019-10-09 at 9 30 31 PM" src="https://user-images.githubusercontent.com/24867760/66532535-bbbe6580-eadd-11e9-8da9-706d1a1d2de5.png">

**Comment by jraff** [comment]
Fixed with [@tds/core-decorative-icon@2.4.1](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.4.1)
