### ISSUE TITLE
Update to decorative success icon

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-core#1288]
## Description

- The current decorative icon `Success` has visual conflicts with the `FeedbackSuccess` feedback icon
- the documentation for usage guideline also needs to be updated

## Workaround details

Can continue using icon as is, but will be confusing to users

## Recommendation

- Create a visually different decorative success icon 

## Meta

- TDS component version: DSM v2.3.6
- Willing to develop solution: Yes/No
- High impact: Yes/No 

## Screenshots

Brought up by @twirlingsky 
![Screen Shot 2019-10-16 at 1 09 20 PM](https://user-images.githubusercontent.com/42220619/66956272-1dc52080-f032-11e9-9631-e74577137285.png)
![image](https://user-images.githubusercontent.com/12798751/67421692-07bddf80-f59f-11e9-9708-e22b2fb492b7.png)

**Comment by theetrain** [comment]
Potential outcomes:

A) Deprecate `Success` and advise alternatives
B) Redesign `Success` and release a patch to DecorativeIcon

**Comment by Christina-Lo** [comment]
@twirlingsky can you please provide the use case example for this and attach designs here? thanks!

**Comment by Christina-Lo** [comment]
We will be deprecating the success decorative icon and suggesting our users to use "icons/Check" instead

**Comment by theetrain** [comment]
This update is available in:

- [@tds/core-decorative-icon@2.6.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.6.0)

Please use the `Check` Decorative Icon for this use case from now on.
