### ISSUE TITLE
Users Settings icon for My TELUS Overview + My Profile

### ISSUE THREAD

**Issue by cherryhung** [telus/tds-core#1293]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
3. If your design lead has approved this change, please note their name: *This icon is currently live on the Overview page but is not in the TDS library.
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: Users Settings (Same name in TELUS icon suite in Iconjar)

Usage criteria: A decorative icon used on My TELUS with a CTA to link additional accounts to the user's profile.

<img width="353" alt="Screen Shot 2019-10-21 at 2 54 58 PM" src="https://user-images.githubusercontent.com/40604656/67234281-dadcc180-f412-11e9-9d5e-4dfd706006ce.png">
<img width="1219" alt="Screen Shot 2019-10-21 at 2 54 21 PM" src="https://user-images.githubusercontent.com/40604656/67234304-e5975680-f412-11e9-9f32-5a2b4dc22c26.png">

**Comment by theetrain** [comment]
Would you kindly approve this, @gkychow?

**Comment by gkychow** [comment]
Approved! 
@cherryhung @Christina-Lo - maybe we can do some more explorations to see if there are any other options later. For now, I think it's ok

**Comment by theetrain** [comment]
This will be worked on. You may follow its progress here: https://telusdigital.atlassian.net/browse/TDS-1753

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
