### ISSUE TITLE
[Notification] does not unmount fully

### ISSUE THREAD

**Issue by jraff** [telus/tds-core#1298]
This issue is a followup to  #1295 

## Description

- The Notification component should completely unmount on dismissal. After dismissing a Notification it still remains in the DOM.

- TDS component version: `@tds/core-notification@3.0.4`
- Willing to develop solution: Yes
- High impact: No

**Comment by ah-arch** [comment]
Might be able to workaround by removing the Notification manually with the `onExit` prop.

**Comment by marcod1419** [comment]
This has been addressed in Notification 3.0.7: https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-notification%403.0.7
