### ISSUE TITLE
[Icons] Excessive deprecated icon warnings in console 

### ISSUE THREAD

**Issue by JordanToering** [telus/tds-core#1299]
Recently, my project team switched over to TDS core components for common functionality.  When inputting characters in a core input many deprecation warnings are thrown in the console, approx 5 per keystroke.  I also believe these warnings are thrown when using a core select component.

I see these deprecation warnings and experience the delays when using the live reload development server, but when I generated a production build of my react application I could not perceive any extraordinary delay.  My guess is because the production build of react applications are much more restrictive in what they log to the console.

Is this a problem related to how we use the components?  We have Windows development machines, and I have updated all of the core components that we use.  I attached screenshots of the console and the TDS core components that we have in our package.json.

![node_mods](https://user-images.githubusercontent.com/6356022/67536976-601fda80-f68e-11e9-965f-447a978e745d.PNG)
![Capture](https://user-images.githubusercontent.com/6356022/67536977-601fda80-f68e-11e9-98fc-674f0930c7a7.PNG)

If you want to follow up more immediately you can reach me on hangouts.

Thanks

**Comment by theetrain** [comment]
Hi Jordan, thanks for bringing this to our attention.

Those deprecation warnings are designed to only appear when the node environment isn't "production". While playing around, I noticed that even focusing and unfocusing on the Input will cause the warning to appear. We'll try refactoring our components to only call deprecation warnings on the first render.

I suspect Input's [`handleFocus`](https://github.com/telus/tds-core/blob/ba7d705eabbcef7556d6048523758ab1451a4e32/packages/Input/Input.jsx#L159-L164) is causing unnecessary re-renders as well.

**Comment by marcod1419** [comment]
This has been fixed in a recent release:

https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-standalone-icon%402.1.9
https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-input%403.0.30
https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.5.1

Thanks for reporting! More steps will be taken to remove deprecation warnings from core components in a soon to come future release.
