### ISSUE TITLE
Allow Card to match the height of its parent

### ISSUE THREAD

**Issue by jraff** [telus/tds-core#1305]
## Description

Originally reported by Byron Torres.

- When placing cards in a row the cards do not expand to fill the height of the parent.

## Recommendation

- Add a prop to allow cards to match the height of their parent.

## Designs

![image-card](https://user-images.githubusercontent.com/1036187/67979230-37e62d80-fbf2-11e9-9f4a-4b09783f277d.png)

The red space above is space that the Card does not occupy. With this new prop the cards would fill this space.

## Meta

- TDS component: @tds/core-card@2.1.3
- Willing to develop solution: Yes
- Has workaround: Yes - Create a container around the card and target the first child of that container, applying height 100%
- High impact: No
- Designer/Developer Pair: @jraff 
- Related story: https://telusdigital.atlassian.net/browse/TDS-1041

**Comment by theetrain** [comment]
This is now available in [@tds/core-card@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-card%402.2.0)
Documentation: https://tds.telus.com/components/index.html#!/Card (see `fullHeight` prop)
