### ISSUE TITLE
Update of H4 font color 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#1312]
## Description

- Description of the problem
A new feature for donation is developing on the Billing page and the same feature will be developed on the mobile app as well. 
The app design uses a layout with purple numbers and texts. 
**So to be aligned with the app, I would like to use a font size we have in DSM library (H4) with purple color. But the problem is: this font size just exist in black.**

## Recommendation

The proposed solution is to give the possibility **to use H4 in black or purple**.

## Designs
- Screenshot of the current app design: 
<img width="426" alt="Screen Shot 2019-11-04 at 3 16 16 PM" src="https://user-images.githubusercontent.com/44266628/68157010-d0deb680-ff1a-11e9-9b6a-6845ed142a88.png">

- Links to Invision 
**BEFORE:**https://telus.invisionapp.com/d/main#/console/17454526/391814203/preview
![Screen Shot 2019-11-04 at 3 54 49 PM](https://user-images.githubusercontent.com/44266628/68157389-8c9fe600-ff1b-11e9-9934-2c689eb4c760.png)
**AFTER:**https://telus.invisionapp.com/d/main#/console/17454526/391814204/preview
![Screen Shot 2019-11-04 at 3 54 58 PM](https://user-images.githubusercontent.com/44266628/68157409-96c1e480-ff1b-11e9-95a0-6dbe0a87ded0.png)

## Meta

- TDS component: @tds/core-heading
- Willing to develop a solution: Yes
- Has workaround: No 
- High impact: No 
- Designer/Developer Pair: @Marie Fuhrmann, @Jeffrey-Chang

**Comment by varunj90** [comment]
hey @Mariefhrmnn at this time, our brand direction will maintain the current colours for our various heading levels. Headings 3 and 4 will remain shark grey until the foreseeable future.

we will revisit typography with @gkychow in 2020
