### ISSUE TITLE
[BenefitWithHeading] Add legal support for heading component

### ISSUE THREAD

**Issue by mixenmp** [telus/tds-core#1315]
## Description

- In some context, we need to be able to have a legal note on the heading instead of the content below it.

## Recommendation

- Add WithLegal support `BenefitWithHeading.Item` component.

## Designs

![image](https://user-images.githubusercontent.com/42189240/68613260-5b2f9900-048c-11ea-8fcd-fcc950488b30.png)

## Meta

- TDS component: @tds/core-benefit
- Willing to develop solution: No
- Has workaround: No 
- High impact: No 
- Designer/Developer Pair: Michel Pen

**Comment by varunj90** [comment]
Based on my discussion with Paul on slack, "Not urgent right now as we found another solution to bypass it, so for now its a "nice to have".

TDS team will look into adding this feature in the near future.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
