### ISSUE TITLE
CMS and icon/ assets repository

### ISSUE THREAD

**Issue by roannaca** [telus/tds-core#1322]
## Question

Hi, 
I'm a UX consultant working on the Odyssey order and quoting systems for B2B sales. The Odyssey web applications are built on top of SalesForce with Vlocity as a partner for many of the user interface components. 

The icons in use in Odyssey today come from different sources (see list below) and this is causing complexity for our developers. Do you know whether TELUS Digital has a central CMS for icons that could be used to store our icons? Do you know a contact we could reach out to who might have more information about this?

1. Our primary resource is the Current TELUS Design System: http://cdn.telus-thorium-doc-production.s3-website-us-east-1.amazonaws.com/components/index.html#icons
2.  Legacy TELUS icons: http://standards.teluswebteam.com/component-library/iconography (This library is no longer maintained by TELUS Digital and we've been told we can't make changes to it. The icons were implemented about 3 years ago prior to my involvement on the project.)
3.  SalesForce Lightning Design System: https://lightningdesignsystem.com/icons/ This is a very well-supported icon library and is used for many of the Vlocity components. On occasion we've used these icons for some of our custom interfaces as well.
4. We have 2-3 custom icons that we've created for very specific circumstances, but avoid customization.

We'd very much appreciate any information you could provide.

## Related components

- Component 
- Component 

## Screenshots

- Include any relevant screenshots

**Comment by varunj90** [comment]
Hey @roannaca! Thank you for reaching out to us.

Icon docs and source of truth:  https://tds.telus.com/components/index.html#icons

We have an issue template to request a new icon: https://github.com/telus/tds-core/issues/new?template=icon_template.md

we highly suggest using these two resources for anything icon related.

**Comment by roannaca** [comment]
Hi, thanks for your response. 

The Odyssey project team is already aware of the resources above and they are sited in our project documentation.

What we're hoping to get assistance with is access to a central icon repository that our developers can link to for icon assets. Our application has been in use by TELUS sales teams for over 3 years, and we'd like to have the legacy TELUS icons moved to the same central location as the icons included in the TDS. Is there someone we can contact at TELUS Digital that could assist us with these concerns? Thanks!

**Comment by varunj90** [comment]
hey @roannaca!

We recommend consuming only what is available on the TDS Website. 

For coded components, their installation instructions are listed under each component https://tds.telus.com/components/index.html, for example, DecorativeIcon is available on npm as @tds/core-decorative-icon. If your product is using any legacy iconography, we recommend upgrading to the latest TDS Icons as soon as possible.

Designers can consume these components using InVision DSM here: https://telus.invisionapp.com/dsm/telus/tds-core
Setup instructions for designers and developers are available here: https://tds.telus.com/getting-started/getting-started.html

if you’re looking to add any legacy icons, please use the following template to request these: https://github.com/telus/tds-core/issues/new?template=icon_template.md, we need approval from our art director @gkychow  to add to the design system!

happy to chat in-person/remote to learn more about your project! If your product is using any legacy iconography, we recommend upgrading to the latest TDS Icons as soon as possible.

**Comment by roannaca** [comment]
Hi @varunj90,

Thank you so much for the details above. I appreciate your time to look into this for the Odyssey project team. I see that there are a bunch of shiny new icons to represent products, etc. in the TDS now and will take this update back to team leadership.

**Comment by roannaca** [comment]
Hi @varunj90 
My UX colleague and I have been having some trouble accessing the DSM outside the TELUS network. We're consultants and work with Sketch using our personal Mac laptops. I've been issued an HP laptop by TELUS for use for internal communications, and can access the DSM there. Do you know if anyone else has experienced this issue?

Many thanks,
- Roanna
<img width="1230" alt="Screen Shot 2019-12-16 at 11 39 18 AM" src="https://user-images.githubusercontent.com/54993646/70937982-2918d600-1ffa-11ea-9731-77979d98f05a.png">

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
