### ISSUE TITLE
Decorative "Add plans or services" 

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-core#1325]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
3. If your design lead has approved this change, please note their name:  submitting this on behalf of @apurvray 
4. If the art director has approved this change, please have them **comment on this issue**. 

## Guidelines

Icon name: Add product/services

Usage criteria: To represent the ability to add services

**Comment by Christina-Lo** [comment]
Ticket wont allow for attached file so here's one suggestion 
![Screen Shot 2019-11-25 at 4 39 42 PM](https://user-images.githubusercontent.com/42220619/69580736-26026b00-0fa3-11ea-90f8-2c161d5797f1.png)

**Comment by gkychow** [comment]
Other possibilities (though we'd have to create it):

![exceptional_reliability_blue_rgb](https://user-images.githubusercontent.com/16300159/69825387-f7afa600-11c3-11ea-96d1-e44ecbd7a030.png)
![value-icon-png-7](https://user-images.githubusercontent.com/16300159/69825389-f7afa600-11c3-11ea-88a2-d63a0f01e877.jpg)

**Comment by gkychow** [comment]
![add_service](https://user-images.githubusercontent.com/16300159/71697481-f6e2d480-2d6c-11ea-9ff4-fcb20c2d6a2b.png)

**Comment by Christina-Lo** [comment]
@apurvray Can we get the design attached for the specific use case? We want to get a bit more context before we finalize on a design. Thanks!

**Comment by theetrain** [comment]
This will be closed since an alternative was found.
