### ISSUE TITLE
[HairlineDivider] vertical hairline not displaying in long text

### ISSUE THREAD

**Issue by Nitin-TELUS** [telus/tds-core#1328]
## Description

 While trying to add a vertical horizontal line in the component horizontal line not showing when text wraps more than 2 lines.

- When line wraps in more than 2 lines then the width of the line is dynamically calculated. In CSS it displaying 1px but actually it's width is 0.42px.
- Width of the line should be 1px

## Reproduction Steps
Please use below code snippet to reproduce the issue

`<FlexGrid>
  <FlexGrid.Row>
    <FlexGrid.Col>
      <Box inline between={4}>
        <HairlineDivider vertical />
        <Box between={3}>
          <Heading level="h4">linkSectionHeading</Heading>
          <Box between={2}>
            <Text>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non placerat tellus, at tristique libero. Nullam sagittis nulla arcu, vehicula tristique diam lacinia id. Donec a ligula sit amet metus ullamcorper posuere. Cras luctus nisl at ligula sagittis molestie.
            </Text>
          </Box>
        </Box>
      </Box>
    </FlexGrid.Col>
  </FlexGrid.Row>
</FlexGrid>`

## Meta

- TDS component version:
@tds/core-hairline-divider@^2.0.8,
@tds/core-box@^2.0.1,
@tds/core-text@^2.0.0,
@tds/core-flex-grid@^3.0.0
- Willing to develop solution: No
- High impact: No

## Screenshots
<img width="951" alt="Screenshot 2019-11-26 at 3 48 41 PM" src="https://user-images.githubusercontent.com/50699231/69742588-103ba400-1163-11ea-89ca-bf6ae603c4aa.png">

- Desired output
<img width="397" alt="design" src="https://user-images.githubusercontent.com/50699231/69742704-34978080-1163-11ea-9c8c-9d771d132bf1.png">

**Comment by theetrain** [comment]
Note to developers: the hairline is rendering as below 0.5px width. Let's set `flex-shrink: 0;` so that it longer shrinks.

**Comment by Jeffrey-Chang** [comment]
I don't think you need a long text for it to _**not**_ render. Just putting it into a `<FlexGrid.Col>` will cause it to not render when adding the `vertical` prop to `<HairlineDivider />`

![Screen Shot 2019-11-28 at 3 31 21 PM](https://user-images.githubusercontent.com/30445300/69830777-57be4080-11f4-11ea-94e9-d2bd19478eea.png)

**Comment by Nitin-TELUS** [comment]
I've tried the same approach but to display the hairline divider inside col we need to add a box with vertical spacing.  

`<FlexGrid.Col>
      <Box inline between={1}>
         <HairlineDivider vertical/>
        <Box vertical={7} />
      </Box>
  </FlexGrid.Col>`

If text is dynamic than we can't specify the vertical spacing of the box.

**Comment by jraff** [comment]
@Nitin-TELUS Issue fixed with [@tds/core-hairline-divider@2.0.9](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-hairline-divider%402.0.9)
