### ISSUE TITLE
Link Components not accepting correct children

### ISSUE THREAD

**Issue by slawler-telus** [telus/tds-core#1333]
## Description
Button, Chevron and Link Components do not accept correct children. Example:
https://github.com/telus/tds-core/blob/master/packages/ChevronLink/ChevronLink.jsx#L111 
is only accepting a11y components, or strings.

- Description of the defect, observations: Warnings (Shown in red error text) in console
- The result you were expecting: No errors/warnings
![image](https://user-images.githubusercontent.com/42187593/70169676-17d9dc00-1680-11ea-8549-6d4c832e57c7.png)

## Reproduction Steps

```
import Box from '@tds/core-box'
import Text from '@tds/core-text'
import React from 'react'
import WithMarkdown from '../../components/WithMarkdown'
import MultiLink from '../../components/MultiLink' // Any link component. MultiLink is just our wrapper for said components.

const testRenderOverridesMultiLink = (params) => {
  const { theChildren, href } = params
  return (
    <MultiLink
      linkUrl={`${href}/hello!`}
      relative={false}
      linkTarget="New"
      linkType="Button"
    >
      {theChildren}
    </MultiLink>
  )
}

const renderOverridesTest = {
  a: testRenderOverridesMultiLink
}

const renderSomething = (items) => {
  return items.map((item) => {
    return (
      <Box vertical={3} key={`qa-${item.slug}`} between={3}>
        <Box id={item.slug}><Text bold>{item.entryTitle}</Text></Box>
        <WithMarkdown content={item.entryContent} renderOverrides={renderOverridesTest} />
      </Box>
    )
  })
}
export default renderSomething
```
https://github.com/telus/my-telus-rewards/tree/staging/app/src/ui/components/MultiLink - Our Link wrapper (Not related to this bug, but where we found it).

## Workaround details
Ignore the warnings/errors

## Recommendation

Change the PropTypes to: `children: PropTypes.node` or some subset of components that allows for this.

## Meta
This is probably related to https://github.com/telus/tds-core/issues/1154
This error is happening for us because we are using the TELUS link components inside the WithMarkdown compontent. The WithMarkdown component is passing children as an array.

**Comment by slawler-telus** [comment]
We are using:
```
"@tds/core-link": "^2.1.2",
"@tds/core-button-link": "^2.1.6",
"@tds/core-chevron-link": "^2.0.18"
```

If it's any help.

**Comment by theetrain** [comment]
Note to team: let's review the `WithMarkdown` component to see how children gets passed to our link components. The likely issue is our prop types do not accept React Fragments.

**Comment by slawler-telus** [comment]
Hello, we switched to versions:
```
"@tds/core-button-link": "^2.1.10"
"@tds/core-link": "^2.1.3"
"@tds/core-checkbox": "^2.0.25"
```

And that made the warnings go away. Closing the issue! Will reopen if these errors come again.

**Comment by varunj90** [comment]
noted! thanks @slawler-telus
