### ISSUE TITLE
Pause video icon

### ISSUE THREAD

**Issue by kimmorrice** [telus/tds-core#1334]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
3. If your design lead has approved this change, please note their name: [Laurel Terlesky]
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: PauseVideo 

Usage criteria: Interactive icon used in conjunction with PlayVideo (existing icon)

SVG is not supported so I attached a PNG:
![PauseVideo](https://user-images.githubusercontent.com/52254934/70191908-1e337c80-16af-11ea-8000-74a864d9dfdd.png)

**Comment by Christina-Lo** [comment]
@kimmorrice Can we get an update to see whether this play/pause button is still needed for the Image Carousel? Is there the latest update where this is used so we can get some more context

Cc: @gkychow

**Comment by kimmorrice** [comment]
@Christina-Lo Yes, we still need it for the carousel. The play button has been implemented, but we're using a placeholder svg for the pause button and it's not an elegant solution. -just temporary until the official pause button is ready. 
This is what Andre is working on (WIP) for context: http://b43d0f32.ngrok.io/en/andre

**Comment by theetrain** [comment]
Next steps:
- @gkychow to advise Kim on alternatives to autoplaying carousels with a pause option

**Comment by billtelus** [comment]
Hey @kimmorrice do you have the SVG file?

**Comment by kimmorrice** [comment]
> Hey @kimmorrice do you have the SVG file?

@billtelus I had to dig it up, but yes... here is the old pause icon to match the play video icon in TDS:
![Pause](https://user-images.githubusercontent.com/52254934/177429764-2fa51ee6-da82-4581-92f1-3922e712d5c2.svg)

**Comment by billtelus** [comment]
Thanks, I got it.
