### ISSUE TITLE
<HairlineDivider vertical /> does not show up when nested in <FlexGrid.Col>

### ISSUE THREAD

**Issue by Jeffrey-Chang** [telus/tds-core#1351]
## Description

When the `<HairlineDivider />` is nested inside a `<FlexGrid.Col>` it does _*NOT*_ show up. 

## Reproduction Steps

1. Create a `<FlexGrid.Col>` component and then nest a `<HairlineDivider vertical />` as the only child
2. Notice that nothing will be displayed

## Recommendation

There is kind of a workaround if you just so happen to have more than just a `<HairlineDivider />` as a child of `<FlexGrid.Col>`. You would be able to wrap it inside a `<Box inline between={1}>` and whatever other child you have/need.

## Meta

- TDS component version: @tds/core-flex-grid@3.0.3, @tds/core-hairline-divider@2.0.9
- Willing to develop solution: No
- High impact: No

## Screenshots

![Screen Shot 2020-01-08 at 1 53 58 PM](https://user-images.githubusercontent.com/30445300/72006818-6994f980-321e-11ea-827e-13176c48b13f.png)

**Comment by jraff** [comment]
@Jeffrey-Chang Fixed with https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-flex-grid%403.0.9
