### ISSUE TITLE
Nested <FlexGrid> in a <Box> will over ride the <FlexGrid> padding for limitWidth prop

### ISSUE THREAD

**Issue by Jeffrey-Chang** [telus/tds-core#1355]
## Description

Nesting a `<FlexGrid>`, with or without the `limitWidth` prop, under a `<Box>` component will over ride the padding

## Reproduction Steps

1. View the `Box` component
2. Nest `<FlexGrid>` under the `<Box>` component
3. Give `<FlexGrid>` the `limitWidth={false}` prop
4. Notice the `<Box>` component is overriding the padding

## Workaround details

N/A

## Recommendation

N/A

## Meta

- TDS component version: @tds/core-flex-grid@3.x
- Willing to develop solution: No
- High impact: Yes

## Screenshots
![Screen Shot 2020-01-10 at 1 18 18 PM](https://user-images.githubusercontent.com/30445300/72177239-44cf8c00-33ae-11ea-8660-a70df05faac4.png)

**Comment by jraff** [comment]
@Jeffrey-Chang Fixed with https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-flex-grid%403.0.8
