### ISSUE TITLE
Expand Collapse Component - Empty child property for some rows

### ISSUE THREAD

**Issue by dreaumeArchitech** [telus/tds-core#1356]
## Description

The Expand collapse component requires rows where the functionality to expand / collapse is turned off in cases where content for the expandable portion is not required.

## Recommendation

Have it so if the child property is empty, the functionality to expand / collapse is turned off.  Alternatively if the disabled state is not frequently used, we can remove the grey background from the disabled state and document how to satisfy this need.

## Designs

**Desired State**
The 'Monthly Mobility Bonus' row has no child content (eg. no need to expand)
The 'Home Service Billing' row has child content and we are showing the expanded and collapsed states.

![desiredState](https://user-images.githubusercontent.com/59748669/72188155-9cc6bc80-33c7-11ea-9d16-a0fee5026dd2.jpg)

**Current Undesired State**
The 'TFFF $10 DON Bonus - Free Contest Entry for Samsung TV' row has no child content and has been disabled.
![currentstate_showingDisabled](https://user-images.githubusercontent.com/59748669/72188182-ac460580-33c7-11ea-8ba4-0fda9f9693e7.jpg)

## Meta

- @tds/core-expand-collapse
- Willing to develop solution: Inquired to our development team, awaiting response.
- Has workaround: Yes: Currently making it disabled.  However it gives us a grey background with some less than ideal padding for left aligned text. (See current undersized state)
- High impact: No
- Designer/Developer Pair: Darcy Reaume (Design @ Architech)

**Comment by donnavitan** [comment]
Hello @dreaumeArchitech,

As per our initial conversation, I discussed this with the CX and TDS team as the requested enhancement may affect current use and functionality.


### Recommendations are as follows:
1. The immediate solution is to enhance the ExpandCollapse component to allow the heading to render as content (not disabled button) with a white background
2. The long-term solution is to reconsider that the ExpandCollapse component may not be the best way to present this content/information. It appears to be information that would be better rendered as a table, a complex table perhaps.


### :warning: Some caveats to the long-term solution: 
1. TDS doesn't currently have a table component available at this time. It's in our 2020 roadmap, so it's key to keep a use-case like this in mind
2. Further review/discussions with your designer and design lead/CX can provide more insight to find a better solution


✌🏽Cheerios,

**Comment by jraff** [comment]
Hey @dreaumeArchitech, this issue has been resolved with [@tds/core-expand-collapse@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%402.2.0)
