### ISSUE TITLE
<FlexGrid.Col> with mdOffset or higher offset will hide <HairlineDivider />

### ISSUE THREAD

**Issue by Jeffrey-Chang** [telus/tds-core#1373]
## Description

When using `mdOffset` prop or higher in `<FlexGrid.Col>`, it will hide the `<HairlineDivider />`

## Reproduction Steps

1. Create a base `<FlexGrid.Col>`
2. Nest a `<HairlineDivider />`
3. Add `mdOffset={1}` or any higher `offset` to `<FlexGrid.Col>`
4. Notice that `<HairlineDivider />` will disappear

## Workaround details

N/A

## Recommendation

N/A

## Meta

- TDS component version: @tds/core-flex-grid
- Willing to develop solution: No
- High impact: No

## Screenshots

![Screen Shot 2020-01-27 at 10 37 25 AM](https://user-images.githubusercontent.com/30445300/73188550-0d244c00-40f1-11ea-85c2-f64005393153.png)
![Screen Shot 2020-01-27 at 10 37 19 AM](https://user-images.githubusercontent.com/30445300/73188551-0d244c00-40f1-11ea-86e3-526c550b38db.png)

**Comment by jraff** [comment]
@Jeffrey-Chang Fixed with [@tds/core-flex-grid@3.0.9](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-flex-grid%403.0.9)
