### ISSUE TITLE
Breadcrumbs: Allow selective use of React Router <Link /> components

### ISSUE THREAD

**Issue by iamstuartwilson** [telus/tds-core#1414]
## Description

Right now, it is not possible to use both React Router `<Link />` components alongside standard `<a />` tags as `<Breadcrumb.Item />`s.

This is because you can only have an entire set of `<Breadcrumb>`s with or without React Router `<Link />` components, rather than a combination of the two.

We have a requirement to link our breadcrumbs back to a separate React application which means we want our base `<Breadcrumb.Item />` to use a standard `href` whilst the subsequent items should leverage the `reactRouterLinkComponent` prop in order to use internal routing in our React application. 

## Recommendation

Allow for the use of the `reactRouterLinkComponent` not just as an inherited prop to the `<Breadcrumb.Item />` from the `<Breadcrumb />` but as its own prop. Examples below:

### Current: Not using `reactRouterLinkComponent`

```jsx
<Breadcrumbs>
  <Breadcrumb.Item href="/some-link-1">Some link 1</Breadcrumb.Item>
  <Breadcrumb.Item href="/some-link-2">Some link 2</Breadcrumb.Item>
  <Breadcrumb.Item href="/some-link-3">Some link 3</Breadcrumb.Item>
</Breadcrumbs>
```
First and second item will be rendered as `<a />` tags.

### Current: Using `reactRouterLinkComponent` as inherited prop

```jsx
<Breadcrumbs reactRouterLinkComponent={ReactRouterLink}>
  <Breadcrumb.Item href="/some-link-1">Some link 1</Breadcrumb.Item>
  <Breadcrumb.Item href="/some-link-2">Some link 2</Breadcrumb.Item>
  <Breadcrumb.Item href="/some-link-3">Some link 3</Breadcrumb.Item>
</Breadcrumbs>
```
First and second item will be rendered as passed `<ReactRouterLink />` components

### 💡Proposed: Using `reactRouterLinkComponent` prop on Item

```jsx
<Breadcrumbs>
  <Breadcrumb.Item href="/some-link-1">Some link 1</Breadcrumb.Item>
  <Breadcrumb.Item href="/some-link-2" reactRouterLinkComponent={ReactRouterLink}>Some link 2</Breadcrumb.Item>
  <Breadcrumb.Item href="/some-link-3">Some link 3</Breadcrumb.Item>
</Breadcrumbs>
```
First item will be rendered as `<a />` tag while second item will be rendered as passed `<ReactRouterLink />` component

## Designs

N/A

## Meta

- TDS component: @tds/core-breadcrumbs
- Willing to develop solution: Yes
- Has workaround: Yes
  - Can use `window.location.replace` in component rendered as Route.
- High impact: No

**Comment by jraff** [comment]
@iamstuartwilson Thanks for your contribution! This issue has been fixed with [@tds/core-breadcrumbs@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-breadcrumbs%402.2.0)
