### ISSUE TITLE
[ExpandCollapse] render id attribute on panels

### ISSUE THREAD

**Issue by mburtch** [telus/tds-core#1415]
## Description
Currently `ExpandCollapse.Panel` expects an `id` prop, however, this ID is not rendered as an HTML [id] attribute. An example use case would be to deep-link or anchor to a specific panel. 

## Recommendation
Render the `id` prop as an HTML [id] attribute on the panel, preferably on or before the heading element.

## Meta
- TDS component: @tds/core-expand-collapse
- Willing to develop solution: Yes
- Has workaround: Yes – add an element into the panel's contents with the desired ID, and using CSS to vertically offset it, so anchoring to it will keep the panel heading in view.
- High impact: No

**Comment by theetrain** [comment]
Hi @mburtch, thanks for the suggestion. We welcome a pull request if you have the time.

**Comment by jraff** [comment]
Fixed with https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%402.1.0
