### ISSUE TITLE
TDS Video component - event tracking

### ISSUE THREAD

**Issue by mike-bunce** [telus/tds-core#1441]
## Description

We need to be able to track events, play event primarily so that we can have analytics tracking on videos with TDS Video component.

## Recommendation

Add a callback we can access which provides with access to the event object.

## Meta

- TDS component: @tds/core-video
- Willing to develop solution: Yes, if need be
- Has workaround: No
- High impact: Yes, we cannot track video analytics for our campaign, so we don't know the effectiveness of the video we have pubilshed.
- Designer/Developer Pair: Mike Bunce, no designer required.

**Comment by theetrain** [comment]
This enhancement sounds good to us and we welcome pull requests.

The idea is to add a new `eventCallback` prop that users of core-video could use to pass a handler function accepting an `customerEvents` object parameter that contains customer events such as when the play button is clicked, or how much time has elapsed from the video.

**Comment by jraff** [comment]
Thank you for the contribution @mike-bunce. This feature has been updated with [@tds/core-video@1.3.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-video%401.3.0)
