### ISSUE TITLE
TELUS tracker+ , new icon for TELUS drive

### ISSUE THREAD

**Issue by Franimal604** [telus/tds-core#1444]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
3. If your design lead has approved this change, please note their name: Francisco
4. If the art director has approved this change, please have them : He will approve

## Guidelines

Icon name: TELUS+ Drives

Usage criteria: ...

This will be for TELUS acquired company "TELUS+ Tracker" and will only be used for TELUS+ Drives application and no where else.

File to come soon once I have chatted with Gary

**Comment by varunj90** [comment]
hey @gkychow can you please look at this request and respond :)

**Comment by gkychow** [comment]
Chatted w/ @Franimal604 regarding this. Just waiting to see the new icon.

**Comment by Franimal604** [comment]
This is no longer needed as the business unit is no longer active
