### ISSUE TITLE
Delayed / Backordered Shipping Icon

### ISSUE THREAD

**Issue by Stu-Brown** [telus/tds-core#1448]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes/No
Yes - while there is a standard shipping icon there isn't something for delayed / backordered shipping
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
3. If your design lead has approved this change, please note their name: Brian Marchand
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: Delivery - Delayed

![Proposed_Delayed_ShippingIcon](https://user-images.githubusercontent.com/36419784/81594324-b6d0d580-938e-11ea-99fa-9081106131c5.png)

Usage criteria: When shipping is delayed beyond our regular commitment due to extenuating circumstances we can use the delayed shipping icon to visually indicate that change along with copy updates. Otherwise under normal circumstances we would continue to use the current TDS "Delivery" icon.

**Comment by varunj90** [comment]
hey @gkychow can you please look at this request and respond :)

**Comment by gkychow** [comment]
Hey @Stu-Brown , Have we tried a variation of our normal truck with the "!" in a circle on it? I'd prefer we stick w/ using the same base icon just to make sure it's consistent. The "clock" icon could be mistaken for "fast delivery" because it could go either way

**Comment by Stu-Brown** [comment]
Hey @gkychow I hadn't looked at customizing an icon, just pulling from the existing library. There is a version of the van with an exclamation mark instead of a clock though.

In the meantime I'll work up a custom one using the existing truck and exclamation mark so the truck icon is consistent.

![Van_Exclamation](https://user-images.githubusercontent.com/36419784/81849507-9aff3800-9524-11ea-949e-3cbf63c642e3.png)

**Comment by Stu-Brown** [comment]
Here's the current truck with the exclamation mark.

![Delivery Alert](https://user-images.githubusercontent.com/36419784/81850964-be2ae700-9526-11ea-98d1-671ef5d6e0be.png)

**Comment by gkychow** [comment]
Hey @Stu-Brown! I think the truck icon is already at the max-width of 24px so we wouldn't be able to add the "!" icon to the end of the truck without shrinking the width of the truck slightly. Can we also try having the icon vertically centered as well to the top piece of the truck?  Feel free to adjust the "!" and whatever you feel needs to be adjusted. Thanks!

**Comment by billtelus** [comment]
Hi @gkychow and @Stu-Brown, is there an update on this issue. If the final icon already exist, can I have access to the SVG file?

**Comment by nadaltelus** [comment]
If surfaced again, will consider as input for the new DS.
