### ISSUE TITLE
NavButton Icon Tooltip move to top

### ISSUE THREAD

**Issue by abansil** [telus/tds-core#1449]
## Description

To include NavButtons/Widgets in the mobile nav design, we need to account for the tooltip appearing above since some hints will be cut off. 

## Recommendation

Proposing alternate tooltip/hint placement to top of NavButton.

## Designs

Invision: 
![image](https://user-images.githubusercontent.com/37587197/81975610-4d9ecb80-95f5-11ea-8fc7-ebfe693617df.png)

## Meta

- TDS component: 
- Willing to develop solution: Yes/No
- Has workaround: Yes/No 
- High impact: Yes/No 
- Designer/Developer Pair: Your name, your design/dev pair's name

**Comment by nadaltelus** [comment]
Closing the issue, will consider as input for the new DS.
