### ISSUE TITLE
NavButtonHint Missing in DSM

### ISSUE THREAD

**Issue by abansil** [telus/tds-core#1450]
## Description

NavButton hints/tooltip symbols are missing when you drag them in from DSM

## Reproduction Steps

1. Open DSM
2. Go to Icons > NavButton > NavButton Hint
3. Drag into sketch artboard
4. You will see a red dotted line square instead of the symbol

## Workaround details
N/A

## Recommendation

- Include the symbol in symbol sheet/reupload something to DSM?

## Meta

- TDS component version: 
- Willing to develop solution: Yes/No
- High impact: Yes/No 

## Screenshots

![image](https://user-images.githubusercontent.com/37587197/81975945-caca4080-95f5-11ea-9ac3-cd7fe4340526.png)

**Comment by donnavitan** [comment]
Thanks for letting us know about this @abansil ! Fixed and released in TDS Core DSM v.2.4.1
