### ISSUE TITLE
Request for two new global icons or nav icons

### ISSUE THREAD

**Issue by preeti-saluja** [telus/tds-core#1452]
## Description

- The global icons have a different look and feel as compared to the purple line icons
- These two new icons to have the same look and feel as global icons.

## Reproduction Steps

1. View the `x` component
2. Click on the `y` link
3. Observe `z`

## Recommendation

- Your recommendation here

## Meta

- TDS component version: 
- Willing to develop solution: Yes/No
- High impact: Yes/No 

## Screenshots

- Include any relevant screenshots
<img width="673" alt="Screen Shot 2020-05-25 at 12 23 35 PM" src="https://user-images.githubusercontent.com/65372121/82839105-1b0d9200-9e83-11ea-8658-cf9b7e21f3ae.png">
<img width="679" alt="Screen Shot 2020-05-25 at 12 25 32 PM" src="https://user-images.githubusercontent.com/65372121/82839106-1ba62880-9e83-11ea-891d-2ecf1ac481aa.png">
<img width="423" alt="Screen Shot 2020-05-25 at 12 27 03 PM" src="https://user-images.githubusercontent.com/65372121/82839107-1ba62880-9e83-11ea-8ca5-d9ee1650c17e.png">

**Comment by varunj90** [comment]
@gkychow @philroberto icon request + CASA

**Comment by gkychow** [comment]
@preeti-saluja @varunj90 @Christina-Lo - Here's updated icons!
![icon](https://user-images.githubusercontent.com/16300159/83198505-274c5600-a0f4-11ea-8c66-d017080daeb9.png)

**Comment by preeti-saluja** [comment]
Thanks @gkychow These looks great. Will I be able to see them on DSM core icons now?
