### ISSUE TITLE
TV icon: Choice and flexibility

### ISSUE THREAD

**Issue by twirlingsky** [telus/tds-core#1491]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes 
3. If your design lead has approved this change, please note their name: @twirlingsky 
4. If the art director has approved this change, please have them **comment on this issue**. >  Approved by @gkychow (Can you comment?)

## Guidelines

Icon name: TV: Choice and Flexibility
![Screen Shot 2020-09-22 at 14 02 06](https://user-images.githubusercontent.com/22402633/93937247-45aa1300-fcdc-11ea-9491-fede0023c587.png)

[tablet-touch-options.svg.zip](https://github.com/telus/tds-core/files/5263999/tablet-touch-options.svg.zip)

Usage criteria:

For use in value prop statements
Example: https://telus.invisionapp.com/share/N4YR9RWG5ZQ#/431596113_XL_-_1200px_-_PikTV_-_New_Customer_V01

**Comment by twirlingsky** [comment]
@mike-bunce Jordan requested for a dev to make a pull request. Can figure out who can do this?

**Comment by mike-bunce** [comment]
> @mike-bunce Jordan requested for a dev to make a pull request. Can figure out who can do this?

A developer on the HS R+L team can do this, we'll create a Jira ticket so we can bring it in to our next sprint

**Comment by jraff** [comment]
Icon has been added with `@tds/core-decorative-icon@2.7.0`
