### ISSUE TITLE
No Contract

### ISSUE THREAD

**Issue by twirlingsky** [telus/tds-core#1492]
Actions
Did you check to see if there are icons available in TDS that can be used instead? Yes
Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes
If your design lead has approved this change, please note their name: @twirlingsky
If the art director has approved this change, please have them comment on this issue. > Approved by @gkychow (Can you comment?)

Guidelines
Icon name: No Contract
<img width="68" alt="Screen Shot 2020-09-23 at 14 50 07" src="https://user-images.githubusercontent.com/22402633/94073305-1c58b800-fdac-11ea-84bb-44a3e8240b40.png">

[Contract_slash.svg.zip](https://github.com/telus/tds-core/files/5272080/Contract_slash.svg.zip)

Usage criteria:

For use in value prop statements
Example: https://telus.invisionapp.com/share/N4YR9RWG5ZQ#/431596113_XL_-_1200px_-_PikTV_-_New_Customer_V01

**Comment by jraff** [comment]
Icon has been added with `@tds/core-decorative-icon@2.7.0`
