### ISSUE TITLE
Page scroll issue with ButtonGroup

### ISSUE THREAD

**Issue by gerry-wu** [telus/tds-core#1495]
## Description

- when user tabs onto the radio button group, the page doesn’t auto scroll to the radio button group.
- Ideally upon focus on radio button group, it should appear in browser’s view. Which is not happening

## Reproduction Steps

1. Start with the `ButtonGroup` not in page view.
2. Tab onto the button group on: https://tds.telus.digital/components/index.html#/Forms?id=buttongroup
3. See how the focus of the page does not move to the `ButtonGroup`

## Meta

- TDS component version: 
- Willing to develop solution: No
- High impact: No 

## Screenshots

![2020-10-05 11 36 33](https://user-images.githubusercontent.com/14336706/95129513-1c9c7000-0729-11eb-8b49-9fa0db76ee99.gif)

**Comment by jraff** [comment]
@gerry-wu Fixed with [@tds/core-button-group@3.1.3](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-button-group%403.1.3)
