### ISSUE TITLE
Radio + Checkbox: Improvement suggestion for accessibility

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-core#1499]
Consider updating radios and checkboxes to automatically incorporate grouping `legend` tags when there are 2 or more options to help improve the experience with assistive tech

## Designs

- no designs required, this is a code enhancement 

## Meta

- TDS component: radio/checkbox
- Willing to develop solution: No
- Has workaround: Yes, can manually use a `fieldset` tag with a `legend` tag to define a caption
- High impact: Depends on whether developers are doing the above ^^^
- Designer/Developer Pair: Christina, CC @mejsullivan

**Comment by billtelus** [comment]
Hi @Christina-Lo, does this require us to create a new component that will wrap the checkboxes or radio buttons?

**Comment by Christina-Lo** [comment]
@billtelus Honestly, not entirely sure as this was a note I had from an accessibility hour. Perhaps look into it for the Allium component as well

**Comment by nadaltelus** [comment]
hey @Christina-Lo, I'll take this as a requirement for Allium and close the issue here on TDS due to the maintenance mode.
