### ISSUE TITLE
[Select] displaying two dropdown arrows in Firefox

### ISSUE THREAD

**Issue by spuente** [telus/tds-core#1500]
## Description

`Select` component is displaying two dropdown arrows instead of one in Firefox. This visual issue does not occur in other browsers.

## Reproduction Steps

1. View `Select` component in Firefox (v82)
2. Observe there are two dropdown arrows in the component

## Workaround details

N/A

## Recommendation

Remove the following style: `'-moz-appearance': 'textfield'`

## Meta

- TDS component version: @tds/core-select@3.2.26
- Willing to develop solution: Yes
- High impact: No

## Screenshots

![image](https://user-images.githubusercontent.com/4050997/97237991-5c99c480-17b6-11eb-84ec-29d2f81d9e2c.png)

**Comment by jraff** [comment]
Fixed with https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-select%403.2.27
