### ISSUE TITLE
Strikethrough option in PriceLockup

### ISSUE THREAD

**Issue by elissa-matsushita** [telus/tds-core#1503]
## Description

- On the Optik TV package cards, we need to update the cards to have price lockup with strike-through - medium). 

## Recommendation

- Add strikethrough prop to PriceLockup

## Designs

- Screenshots:
<img width="282" alt="Screen Shot 2020-10-27 at 8 50 01 PM" src="https://user-images.githubusercontent.com/66031253/97388767-fe441300-1895-11eb-880f-10968bf63f23.png">

- Link to Invision: https://telus.invisionapp.com/d/main?origin=v7#/console/20296211/433873122/preview?scrollOffset=0

## Meta

- TDS component: PriceLockup 
- Willing to develop solution: Yes
- Has workaround: No 
- High impact: No 
- Dev: @elissa-matsushita , Designer: @twirlingsky

**Comment by twirlingsky** [comment]
additional requirements: 

- Will need the French version as well
- the strike-through is purely a visual solve, it MUST be accompanied by an aria tag.  "was $xx"

**Comment by twirlingsky** [comment]
DSM guidelines: https://telus.invisionapp.com/dsm/telus/tds-community/asset/components/5f8f75024d7a1163f43fc8ec

**Comment by jraff** [comment]
Fixed with https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-price-lockup%402.2.0
