### ISSUE TITLE
Create a line icon for the Casa Customer Story.

### ISSUE THREAD

**Issue by frances-so** [telus/tds-core#1506]
## Description
We have a story to filter our "Customer Story" list - a collection or orders, tasks, cases and trouble tickets that collectively support the story of a customer's record of interaction with Telus. We designed a single view to filter that can be toggled between interaction notes and Customer story items.
- 
![image](https://user-images.githubusercontent.com/65196974/99303959-946cb880-2806-11eb-8c61-a191d6c48362.png)

## Recommendation

- We would like a new icon consistent with the look of the TD line icon set, but specific to the customer story.

## Designs

![image](https://user-images.githubusercontent.com/65196974/99305188-4658b480-2808-11eb-87dd-d4e29f3b4136.png)

A rough vector drawing was done in Sketch, but needs to be a proper icon component with ability to change colours and resize in the same manner as other TD icon components. We need to select and unselect the icon.

Selected state
https://telus.invisionapp.com/share/YSY8IUSQPJ5#/436800154_CAM-1748_Customer_Story_Historic_View_EN_Copy

Not selected state

![image](https://user-images.githubusercontent.com/65196974/99305814-25dd2a00-2809-11eb-8ea0-e876e6626c40.png)

## Meta

- TDS version: vX.Y.Z
- Willing to develop solution: Yes - with coaching :)
- Has workaround: Yes - Can continue to use my makeshift 
- High impact: Yes, Development is planned to start in a week's time.

**Comment by frances-so** [comment]
PO has stated she would prefer if icon was more narrow / rectangular shaped - matching the dimensions for the clipboard for notes. 

![image](https://user-images.githubusercontent.com/65196974/99708215-67144a80-2a52-11eb-920f-e3286512adbb.png)

**Comment by Christina-Lo** [comment]
@frances-so I've asked @gkychow to look into getting IconJar access for a designer on CASA. Since we have limited support on TDS  and TDS technically doesn't support CASA right now, the CASA team will need to create this icon themselves
