### ISSUE TITLE
SEO enhancement to footnote annotations

### ISSUE THREAD

**Issue by mtoribi** [telus/tds-core#1526]
## Description

It appears that content hidden within a11yContent aren't truly hidden and that Google/search engines are still able to grab them when scraping content that surrounds it. Some examples on how it's impacting the search experience:

![image](https://user-images.githubusercontent.com/29639407/108432005-b284f300-7211-11eb-9eeb-085be064749f.png)

This leads to poor user search experience as SEO meta descriptions are big contributors to a page's CTR.

## Reproduction Steps

1. Fastest way to generate the experience above is by [searching for "telus read legal footnote" ](https://www.google.ca/search?ei=YdwuYMS-O4S-0PEP1LCU0AE&q=telus+read+legal+footnote&oq=telus+read+legal+footnote&gs_lcp=Cgdnd3Mtd2l6EAMyBwghEAoQoAE6EAguEMcBEKMCELADEEMQkwI6DQguEMcBEKMCELADEEM6BwgAELADEEM6DgguELEDEMcBEKMCEJMCOgcIABCxAxBDOgUIABCxAzoECAAQQzoFCAAQkQI6CAgAELEDEJECOgIIADoICC4QxwEQrwE6BAgAEAo6BggAEBYQHjoJCAAQyQMQFhAeOgUIABCGAzoFCCEQoAE6BQgAEM0COggIIRAWEB0QHlDUH1jJNmCyN2gBcAJ4AIABuwGIAYkVkgEEMC4yMJgBAKABAaoBB2d3cy13aXrIAQrAAQE&sclient=gws-wiz&ved=0ahUKEwiE85fSsPTuAhUEHzQIHVQYBRoQ4dUDCA0&uact=5)and you should be able to see that the "read legal footnotes" isn't hidden and is being grabbed by search engine bots. 

## Recommendation

Options: 

**Data-nosnippet attribution:**
- Google gives us the opportunity to block certain text from being used in search snippets without impacting its ability to crawl that content. This is through implementing the data-no snippet HTML attribute. We should be able to apply it around the entire footnote link, not just a11yContent component, so that "read legal footnote" or "1" from the example above doesn't get surfaced in search. 
- Reference: https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr

**Doc noteref(role)**
- Adding a role of doc-noteref would be a nice option, that way the semantics would allow any assistive technology to understand what was going on here and remove the need for the visually hidden content.
- Reference: https://www.w3.org/TR/dpub-aria-1.0/#doc-noteref

## Meta

- TDS component version: 
- Willing to develop solution: Yes/No
- High impact: Yes/No 

## Screenshots

- Search: 
![image](https://user-images.githubusercontent.com/29639407/108432530-8b7af100-7212-11eb-89ba-51333037dad1.png)
- a11yContent component on telus.com: 

![image](https://user-images.githubusercontent.com/29639407/108432587-a188b180-7212-11eb-9695-70180bcff1b1.png)

**Comment by mike-bunce** [comment]
Recommendation - update the Legal component in redux-contentful to include the data-nosnippet attribute, which will hide the accessibility content from search snippets. This will have no negative impact to accessibility. The data-nosnippet attribute looks like the way to go as it is specific to the problem (will inform Google and other search engines not to add the contained content in its search snippets). 

redux-contentful is not owned by a specific team, so the SEO team can implement this change themselves, and then it can be reviewed, merged and published by an admin. Individual teams and applications will need to then update to the latest version of redux-contentful to receive the change.

**Comment by mtoribi** [comment]
@danielcrough @vikramadityasingh7 FYI
