### ISSUE TITLE
[WebVideo] aspectRatio used as poster image source URL

### ISSUE THREAD

**Issue by mburtch** [telus/tds-core#1529]
## Description
The [AspectLimiter](https://github.com/telus/tds-core/blob/master/packages/WebVideo/WebVideo.jsx#L34) styled-component incorrectly uses the `aspectRatio` prop as a URL, resulting in an invalid request being sent to the host application.

## Reproduction Steps
1. Mount the component, with or without the `posterSrc` prop
2. Check network requests
3. Observe a request relative to the application, using the aspect ratio prop value, e.g. https://tds.telus.com/components/16:9

## Workaround details
No known workarounds.

## Recommendation
Remove the background-image CSS rule from the AspectLimiter component altogether. The layout is not sufficiently managed (e.g. missing background-size rules), and the [VideoSplash](https://github.com/telus/tds-core/blob/master/shared/components/VideoSplash/VideoSplash.jsx) component already loads the poster properly, making this redundant.

## Meta
- TDS component version: @tds/core-web-video@1.1.20
- Willing to develop solution: Yes
- High impact: No

## Screenshots

![image](https://user-images.githubusercontent.com/93336/111214305-2c599380-85a8-11eb-9755-d9a48e68790e.png)

![image](https://user-images.githubusercontent.com/93336/111214404-48f5cb80-85a8-11eb-8a56-071d7a3d5cd0.png)

**Comment by jraff** [comment]
Fixed with https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-web-video%401.1.21
