### ISSUE TITLE
The links to the Starter Kits are dead. 

### ISSUE THREAD

**Issue by hpreowned** [telus/tds-core#1542]
## Description

- The links to all the starter kits are dead.
- The documentation should be updated to correct the starter-kit links.

**Comment by hpreowned** [comment]
Can anyone look into this?

**Comment by nadaltelus** [comment]
@hpreowned can you provide more details for this item?
In which links are dead? Do you happen to know the proper urls to substitute?

Thanks!

**Comment by nadaltelus** [comment]
No feedback on this issue, closing it.

**Comment by hpreowned** [comment]
@nadaltelus I apologize for the delayed response. Actually, I lost hope to get this addressed as the issue was reported Last year :)

But, Anyways... 
The following links are dead.

https://github.com/telus/platform-web
https://github.com/telus/telus-isomorphic-starter-kit
https://github.com/telus/api-starter-kit
https://github.com/telus/starter-kit-starter-kit

These links are available under the "Development" section...
