### ISSUE TITLE
Card fullbleedimage has extra space around the image in Safari

### ISSUE THREAD

**Issue by kretzm** [telus/tds-core#1543]
## Description

The fullbleedimage in the card component has extra space above and below the image in Safari (see screenshot)

**The result you were expecting:**
It should not have extra space, and when aligned to the bottom of the card it should go right to the edge.

## Reproduction Steps
View the [TDS documentation for the card component](https://tds.telus.digital/components/index.html#/Content?id=card) in Safari

## Recommendation
This seems to fix the issue;
On the image component set the following CSS values;
- `margin: 0 auto;` (instead of `margin: 0`)
- `height: 100%`

## Screenshots
![Screen Shot 2021-03-30 at 12 00 36 PM](https://user-images.githubusercontent.com/900447/113019603-ca745e80-914f-11eb-818e-0c1c91c74cee.png)

**Comment by billtelus** [comment]
This issue is no more relevant and will be closed since the component does no more present the specified behavior.
