### ISSUE TITLE
Quick Links Icon

### ISSUE THREAD

**Issue by DanGenuardi** [telus/tds-core#1558]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes/No No
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes/No Yes
3. If your design lead has approved this change, please note their name: [design lead name] Yes Christina Lo & Gary Chow
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: ...  Quick Links icon

Usage criteria: ... 

 We plan on adding this icon next to the quick links cta on the new redesigned Overview page on My Telus

[Quick Links.svg.zip](https://github.com/telus/tds-core/files/6281175/Quick.Links.svg.zip)
<img width="200" alt="Screen Shot 2021-04-08 at 4 08 32 PM" src="https://user-images.githubusercontent.com/39997967/114089873-b1248e00-9884-11eb-8361-c3a44ed538c5.png">

**Comment by DanGenuardi** [comment]
Hello Donna,
Answers to your questions.

Is it necessary to include "Quick" in the icon name? No, it can be named "link icon"
Can this icon be used to indicate links in general or is this locked for the specific use of "Quick links"? No, we are only incorporating with a new CTA on the overview that will be called Quick Links.
Is this only for (text) Link? Or can it also be used for IconButton? It can be used as an icon button if someone else within digital wants to use it.
Do you have someone to develop this for you? It's an icon that has been taken from the TDS icon library. It's just an icon that hasn't been added to TDS.

**Comment by hpreowned** [comment]
@DanGenuardi Can get access to the isomorphic-starter-kit? The links for the same, given in the "reference architecture' documentations/repo/md are not working. I would appreciate your help. I have tried to find it for a month now.

**Comment by DanGenuardi** [comment]
@hpreowned I don't have access to the "isomorphic-starter-kit" @gkychow could you give @hpreowned access?

**Comment by hpreowned** [comment]
@gkychow, can you please provide access? It's been 4 weeks that I'm looking for someone who can share an access :)

**Comment by gkychow** [comment]
@hpreowned <https://github.com/hpreowned> - sorry, I don’t have access to it either.

**Comment by hpreowned** [comment]
@gkychow @DanGenuardi Any idea who is maintaining that repository?
