### ISSUE TITLE
Select component update to TDS style

### ISSUE THREAD

**Issue by rajanjangratelus** [telus/tds-core#1573]
## Description

The select/dropdown component is visually different from TDS style as it's not yet custom built.  

## Recommendation

The devs have found a react library that takes cares of the select functionality/a11y. All we have to do it take care of the different states visually to follow TDS.

## Designs

https://telus.invisionapp.com/share/4D10SQJ6TYSX#/451919008_Select_TDS_Style

## Meta

- TDS component: https://designsystem.telus.com/components/index.html#/Forms?id=select
- Willing to develop solution: Yes
- Has workaround: Yes, stick to native select 
- High impact: No 
- Designer/Developer Pair: Rajan Jangra (design), Charlie Hay (dev)

**Comment by billtelus** [comment]
@rajanjangratelus any update here? The design link no longer works

**Comment by nadaltelus** [comment]
Closing out this task since it represents an increment. If re-surfaced it can be assigned at the new DS.
