### ISSUE TITLE
7 icons for Casa operations (specific departments)

### ISSUE THREAD

**Issue by ceciliarose** [telus/tds-core#1574]
Please see 7 icons here 
https://telus.invisionapp.com/d/main#/console/21421885/452494885/preview

## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? **Yes**
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? **Yes**
3. If your design lead has approved this change, please note their name: Frances So
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: ... 
CSSActivations
CART
Sales
ProactiveAssurance
WebstoreTeam
Helpdesk
Escalations

Usage criteria: 
Casa applications needs to surface department-specific icons for whenever a note was left by one of these specialty teams.

https://telus.invisionapp.com/d/main#/console/21421885/452494885/preview

**Comment by gkychow** [comment]
Hey @ceciliarose, do we know what size the icons will show up in CASA? A few of them may be too detailed and hard to tell in smaller sizes (ie. Webstore and CART team).

**Comment by ceciliarose** [comment]
@gkychow - Yes they will be 20 X 20 px

**Comment by ceciliarose** [comment]
@gkychow We are looking at better options for Webstore + CART that might be better for the smaller format.
Will ping you again when we have some updates. :)

**Comment by ceciliarose** [comment]
@gkychow Updated request with the link to the icons - we made some changes to the 2: CART & Webstore team.
Let me know your thoughts

**Comment by gkychow** [comment]
@ceciliarose - Those work for me!
