### ISSUE TITLE
Microphone Icon

### ISSUE THREAD

**Issue by brendasinclair** [telus/tds-core#1575]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes, didn't find anything suitable
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? No
3. If your design lead has approved this change, please note their name: Gary/Fran
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: microphone

Usage criteria: For representing voice assistants

[microphone-icon.svg.zip](https://github.com/telus/tds-core/files/6550147/microphone-icon.svg.zip)

![Screen Shot 2021-05-26 at 4 34 20 PM](https://user-images.githubusercontent.com/81318406/119744400-cd828700-be40-11eb-8297-cdcaff71a201.png)

**Comment by billtelus** [comment]
@brendasinclair Is this still necessary?
