### ISSUE TITLE
Tree shaking improvements

### ISSUE THREAD

**Issue by kyletsang** [telus/tds-core#1594]
## Description

Currently, we aren't able to tree shake any of the components in TDS.  For example, importing a single icon, would bring in the whole library into our bundle.  

We were able to achieve proper tree shaking with our other libraries in home solutions by moving away from rollup and not compiling the packages into a single file.  Instead we compiled using babel only.  In addition, adding `sideEffects: false` to the package.json was needed to optimize tree shaking.

## Recommendation

- use babel only and migrate away from rollup and single file distributions
- add `sideEffects: false` into the package.json of each component

## Meta

- TDS component: All
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No

**Comment by nadaltelus** [comment]
Hey @kyletsang , we are keeping TDS on maintaining mode. New increments and features will not be considered. We can bring this suggestion to the new Design system. Thanks.
