### ISSUE TITLE
Hello, we have a requirement to show tree structure of nodes on left of the page and right page showing details etc, We needs a split pane which we should be able to drag to make tree wider or small as per data. It would be great if there is an idea to make draggable divider horizontally for that. 

### ISSUE THREAD

**Issue by ManveenKaur02** [telus/tds-core#1604]
## Description

- Description of the problem

## Recommendation

- Description of the proposed solution

## Designs

- Screenshots
- Sketch file
- Link to Invision

## Meta

- TDS component: 
- Willing to develop solution: Yes/No
- Has workaround: Yes/No 
- High impact: Yes/No 
- Designer/Developer Pair: Your name, your design/dev pair's name

**Comment by billtelus** [comment]
Hello, can you tell me more about this ?

**Comment by nadaltelus** [comment]
Hey @ManveenKaur02 , we are keeping TDS on maintaining mode. New increments and features will not be considered. We can bring this suggestion to the new Design system. Thanks.
