### ISSUE TITLE
Fix Tooltip button type

### ISSUE THREAD

**Issue by elissa-matsushita** [telus/tds-core#1627]
## Description

When the Tooltip is used inside a form, when it’s clicked it automatically tries to submit, which causes all of the validation errors to pop up. This can be fixed by adding type=button (vs. default which is submit) to the tooltip button.

## Reproduction Steps

Can only be reproduced when the Tooltip is consumed within a form.

## Recommendation

adding type=button (vs. default which is submit) to the tooltip button.

## Meta

- TDS component version: 
- Willing to develop solution: Yes/No
- High impact: Yes/No 

## Screenshots

<img width="845" alt="Screen Shot 2021-11-01 at 11 45 00 AM" src="https://user-images.githubusercontent.com/66031253/139724259-b3f70dc7-04ba-41cf-89e2-6f3c6c45a810.png">

**Comment by ah-arch** [comment]
Also relates to: https://github.com/telus/tds-core/issues/1606
