### ISSUE TITLE
CAN-US dedicated icon

### ISSUE THREAD

**Issue by nickamirkhani** [telus/tds-core#1713]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? **Yes**/No
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? **Yes**/No
3. If your design lead has approved this change, please note their name: **Stuart Brown**
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

**Icon name:** ... CAN-US ICON

Usage criteria: To be used when user must illustrate or represent CAN-US services (aka talk/text, data, travel etc.)

**Comment by donnavitan** [comment]
Closing this ticket as it is being addressed in [Allium](https://github.com/telus/universal-design-system/issues/1306).
