### ISSUE TITLE
Difficult to re-open the DatePicker Overlay

### ISSUE THREAD

**Issue by Trev-Allen** [telus/tds-core#1820]
## Description

I am reporting this issue based on the observed customer difficulty in this [Decibel session](https://portal.decibel.com/Player?id=ade4a116535ca2de7ef5fb6ba719bb0a&propertyId=20949[…]nId=574912549&api=d806-us.api.decibel.com&state=EventStream](https://portal.decibel.com/Player?id=ade4a116535ca2de7ef5fb6ba719bb0a&propertyId=209494&websiteId=209494&accountId=209493&sessionId=574912549&api=d806-us.api.decibel.com&state=EventStream)).

The customer tries to re-open the overlay multiple times after it closes when they scroll the browser window to make more of overlay visible in the viewport.

- The expected result is that the overlay re-appears after the customer clicks either the Input field or the Label for this component.

## Reproduction Steps

Start the playback at the 1:56 mark.
The customer opens the calendar overlay, scrolls the browser window down so they can see all the dates, the overlay closes, and they cannot get the overlay to open again by clicking inside the date field, they have to click the label above the field.
This continues to happen to them for 1.5 minutes.
This is in the authenticated My TELUS upgrade from copper to Fibre internet flow.
Windows 10
Chrome
Desktop

This can also be reproduced here: https://tds.telus.com/community/index.html#!/DatePicker
1. Click within the date picker field to invoke the DatePicker Overlay.
2. With the date picker open, mouse over to the browser scrollbar and scroll down by dragging the scrollbar. 
3. Upon releasing the scrollbar, the DatePicker Overlay disappears. 
4. Notice that the cursor is flashing within the DatePicker field. 
5. When the user clicks within the field again to invoke the DatePicker Overlay, nothing happens. It cannot be triggered because the cursor is already active within the field. There is no way to trigger the event again until an event occurs to remove focus from the field.

## Recommendation

- Your recommendation here

## Meta

- TDS component version: (https://tds.telus.com/community/index.html#!/DatePicker)
- Willing to develop solution: No
- High impact: Yes

## Screenshots

- Include any relevant screenshots

**Comment by billtelus** [comment]
Hi @Trev-Allen, can this issue be created in the [tds-community](https://github.com/telus/tds-community) repository instead since it is related to it?

**Comment by Trev-Allen** [comment]
Hi Bill,

I don't see why not. When I spoke to Donna Vitan about the issue she
mentioned that it should updated for Allium as well as Allium leverages the
same underlying functionality for the Allium datePicker.

**Comment by billtelus** [comment]
Ok Thanks @Trev-Allen,
