### ISSUE TITLE
LWC Migration - Umbrella Icon

### ISSUE THREAD

**Issue by samuel-sum** [telus/tds-core#1832]
## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? **Yes**/No
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? **Yes**/No
3. If your design lead has approved this change, please note their name: Adam Finley
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: umbrella 

Usage criteria: ...
- Use decorative icons for visual aesthetics only
- This needs to be in the UDS and the Allium library
- Context: for LWC migration / currently still in TDS

![Screen Shot 2022-06-29 at 11 43 20 AM](https://user-images.githubusercontent.com/103446253/176512624-3cdb5e9d-7bc5-4ab0-b6c8-4ecf36579f69.png)

**Comment by samuel-sum** [comment]
sorry - somehow it was not added
![Umbrella](https://user-images.githubusercontent.com/103446253/177183332-0f54cebc-934a-47e1-9fe1-f6cca97c3fc1.svg)

**Comment by billtelus** [comment]
Thanks
