### ISSUE TITLE
LWC Migration - Battery and Health Icon

### ISSUE THREAD

**Issue by samuel-sum** [telus/tds-core#1852]
> We're sunsetting the maintenance of TDS
> Make sure to verify if your bug has [not been fixed](https://github.com/telus/universal-design-system) yet in [UDS / Allium](https://sites.google.com/telus.com/thinkcontentxdesign/about-us-our-products/allium)
> We encourage everyone to switch to UDS / Allium
Either way, feel free to fix the issue if you can't switch / pick the corresponding component from Allium.

## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? **Yes**/No
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? **Yes**/No
3. If your design lead has approved this change, please note their name: [Adam Finley]
4. If the art director has approved this change, please have them **comment on this issue**.

## Guidelines

Icon name: Battery, Health 

Usage criteria: Decorative

![Screen Shot 2022-07-12 at 8 55 05 AM](https://user-images.githubusercontent.com/103446253/178539314-bc4f3c1e-535a-4cd6-b819-c88dcd3e14bf.png)
![Screen Shot 2022-07-12 at 8 54 41 AM](https://user-images.githubusercontent.com/103446253/178539317-3d1d5534-1718-49d1-9fe4-9b7e04a26375.png)

![Battery](https://user-images.githubusercontent.com/103446253/178539259-1f9a093b-a5fb-4d62-909d-ac76495ead6d.svg)
![Health](https://user-images.githubusercontent.com/103446253/178539262-1305dc98-1033-4bc3-8393-a961ba80ca13.svg)

p.s. sorry for excessive tickets.

**Comment by nadaltelus** [comment]
Hey @samuel-sum TDS is currently in maintenance mode. We are not adding new functionalities, the request can be considered for the new design system.

**Comment by samuel-sum** [comment]
Joao, thanks for your reply. @nadaltelus 

For context: this relates to a e-comm migration that is happening in TDS, which is the reason why I'm requesting to add new icons to this library. I would like to ask for an exception on this matter. I've spoken to one of the appointed designers - Adam Finely and gotten approval.

constraints:
- the effected pages are not scheduled to be changed to Allium this year.  

- The icons I'm proposing would ideally be added to both libraries, if possible. 

Happy to have a discussion about this. thank you!
