### ISSUE TITLE
Countdown timer options for both hero banners + tiles for the HP Redesign in SB 2.0

### ISSUE THREAD

**Issue by Phoebeuy** [telus/tds-core#1894]
> We're sunsetting the maintenance of TDS
> Make sure to verify if your bug has [not been fixed](https://github.com/telus/universal-design-system) yet in [UDS / Allium](https://sites.google.com/telus.com/thinkcontentxdesign/about-us-our-products/allium)
> We encourage everyone to switch to UDS / Allium
Either way, feel free to fix the issue if you can't switch / pick the corresponding component from Allium.

## Description

As per Stu, we require countdown timer options for the rebranded HP in SB 2.0 for hero banners + offer tiles - this is required for BF / CM by **mid-Nov** at the latest. 

## Recommendation

Joao advises to start with simple designs. 

## Designs

Last year's BF / CM designs:
![image (2)](https://user-images.githubusercontent.com/115580255/195844887-f5894d50-2bd3-4c05-97d0-b89adb878246.png)
![image (1)](https://user-images.githubusercontent.com/115580255/195844898-ba8c7ecd-9cfe-405c-aae2-4325dfa3c880.png)

-->

- Screenshots
- Sketch file
- Link to Invision

## Meta

- TDS component: 
- Willing to develop solution: Yes - currently in progress
- Has workaround: No 
- High impact: Yes 
- Designer/Developer Pair: Donna Vitan, Joao Nadal, Lynne DaCosta-Clark, Stu Brown

**Comment by donnavitan** [comment]
Closing this ticket as it will be addressed in an [existing UDS Github ticket](https://github.com/telus/universal-design-system/issues/2436).
