### ISSUE TITLE
[StepTracker] - Mobile view - "Step x of y" is hardcoded and displayed only in English

### ISSUE THREAD

**Issue by amelcharai** [telus/tds-core#407]
## Description
- On the step tracker for mobile view, copy "Step x of y" is displayed in English for French

## Reproduction Steps
 - https://www.wcstage.telus.com/my-account/payment/preauthorized/account/ye_rZFV2bLYlFedcXxDH5w/debit
 - Login: ssffh4@telusinternal.com / Passw0rd - BAN: 603163163s

## Reproduction Percentage (if applicable)
- 10/10 times

## Version Number of TDS
- [0.19] Include version of TDS this is occuring on

*note attach screenshots whenever possible*

![image](https://user-images.githubusercontent.com/16292379/29332477-27941d0c-81ce-11e7-92d6-e59daa18de1b.png)

**Comment by ryanoglesby08** [comment]
Reopening this until we actually fix the issue.

**Comment by theetrain** [comment]
This has been resolved in `@tds/core-step-tracker@2.0.0` https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-step-tracker%402.0.0
