### ISSUE TITLE
[Notification] Make them dismissable

### ISSUE THREAD

**Issue by johnny-hsiao** [telus/tds-core#423]
## Description
- Feature request: add dismissable notification. Notice the 'x' icon in the screenshot. On click of the icon, it will close the notification

## Version Number of TDS
0.23.0

## Screenshots
<img width="1092" alt="screen shot 2017-10-12 at 11 05 27 am" src="https://user-images.githubusercontent.com/9791724/31505028-ee5896e8-af41-11e7-9b1c-d65c9f4f320d.png">

**Comment by ryanoglesby08** [comment]
@saxtron Hi Mike! We heard you may have some time to help with a contribution here? Is that the case? Do you need anything from us to help make that happen?

**Comment by saxtron** [comment]
Hi Ryan.  I've moved on to another piece of work at the moment.  I believe our designs still call for a dismissible notification, I can let whoever works on it know there's an opportunity to contribute to TDS.

**Comment by marcod1419** [comment]
@saxtron Hey Michael! We were just sorting through some still open issues and were wondering if you were ever able to reach out to someone who could contribute to this.

Thanks! :)

**Comment by saxtron** [comment]
Hello!  We accomplished this by setting a piece of state in a wrapping component:
https://github.com/telus/my-account-usage/blob/master/ui/src/components/Usage/NotificationBanner/NotificationBanner.jsx#L54

Sorry I don't have cycles to contribute back to TDS at the moment, but please feel free to use our solution as an example.

**Comment by theetrain** [comment]
Update: @lucylist will investigate the general use of Dismissible Notifications to see whether TELUS should continue using this pattern.

**Comment by theetrain** [comment]
This is now available in [@tds/core-notification@1.2.10](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-notification%401.2.10).
