### ISSUE TITLE
[Box] Adjust values to be more comprehensive or flexible

### ISSUE THREAD

**Issue by ryanoglesby08** [telus/tds-core#430]
Currently, the spacing system (<https://tds.telus.com/#box>) has levels 1-8 and is based on rems. There may be levels that have been left out, such as a value in between 3 and 4. Also it may make sense to totally revamp the system to be mathematical based on a common multiplier. This should depend on the intended design principles of the system.

We can use this thread to discuss the spacing system in general, and put forth other potential solutions.

**Comment by theetrain** [comment]
As a follow-up, this is in our immediate backlog: https://telusdigital.atlassian.net/browse/TDS-965

**Comment by theetrain** [comment]
Update: we have lowered the priority for this enhancement until an identified use case for this enhancement emerges.

To bump the priority, we recommend sharing screenshots of designs that call for different spacing values at different viewport breakpoints.

**Comment by invalidred** [comment]
Speaking with Devs in my-telus, this seems like a must have. The sentiment I collected was that responsive props in `<Box />` is a no brainer. Furthermore I was able to find code used in `my-telus-bill-format` that had such a requirement. We think responsive props is something that will be needed in components other than `<Box />`. Pretty much everything in *Typography* section such as `<Text />`, `<Heading />` etc needs responsive props. Now that I think about it, pretty much every single component needs responsive props. It's a no brainer and we have very good use cases for these.

```
export const ResponsiveEmailCheckboxWrapper = ({ emailCheckbox, updateLink }) => {
  const smCheckbox = (
    <Box between={1}>
      {emailCheckbox}
      <Box horizontal={6}>{updateLink}</Box>
    </Box>
  )

  const mdCheckbox = (
    <Box inline between={4}>
      {emailCheckbox}
      {updateLink}
    </Box>
  )

  return (
    <Fragment>
      <Responsive maxWidth="md" render={() => smCheckbox} />
      <Responsive minWidth="md" render={() => mdCheckbox} />
    </Fragment>
  )
}
```

**Comment by agorovyi** [comment]
Here is a use-case where having 0 value passed to `vertical` prop of Box would be helpful.
Below are two examples using the same component where we want to conditionally change `vertical` prop like this: `<Box vertical={fullWidth ? 3 : undefined}>`

Examples of the above condition:
<img width="784" alt="screen shot 2019-01-18 at 10 50 08 am" src="https://user-images.githubusercontent.com/26413531/51398054-95e8cf00-1b10-11e9-9fb9-00a50b79a99c.png">

<img width="1194" alt="screen shot 2019-01-18 at 10 50 33 am" src="https://user-images.githubusercontent.com/26413531/51398062-997c5600-1b10-11e9-9c0f-87f0b21fbaff.png">

**Comment by invalidred** [comment]
Maybe we could accomplish the design mentioned in https://github.com/telus/tds-community/issues/182 through this feature?

**Comment by theetrain** [comment]
The core team will develop responsive props for core-box in the near future. If anyone is interested in contributing this feature, please leave a comment here.

**Comment by theetrain** [comment]
Update: this will get re-prioritized after core-box is refactored to use styled components.

**Comment by theetrain** [comment]
Update: we are currently looking to add responsive props to Box.

**Comment by marcod1419** [comment]
This feature has been added in Box 2.1.0! https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-box%402.1.0
