### ISSUE TITLE
[ChevronLink] link has extra line on it [IE browser ONLY]

### ISSUE THREAD

**Issue by mahamedidle** [telus/tds-core#432]
## Description
- This is a minor issue and it's ONLY IE browser "Back to Plans and Devices" arrow link has an extra line 
   on it

## Reproduction Steps
- On Device unlock step 2 page point the mouse pointer to "Back to Plans and Devices" arrow link
- Extra small line will display
- Observe extra line is in front of the arrow link

## Reproduction Percentage (if applicable)
- 10/10 times [IE Browser ONLY]

## Version Number of TDS
- Version 0.29.0
![arrow](https://user-images.githubusercontent.com/32342916/33277758-8026e130-d367-11e7-8d77-ecd8a61cb032.gif)

*note attach screenshots whenever possible*

**Comment by marcod1419** [comment]
Looks like this issue doesn't appear anymore on IE. If you're still seeing it on your end, feel free to comment if you're still seeing this.
