### ISSUE TITLE
[Spinner] negative values in animation flagged as a bug in SonarQube

### ISSUE THREAD

**Issue by kretzm** [telus/tds-core#433]
## Description
The negative values in the `stroke-dashoffset` is showing as a bug in SonarQube. I chatted with Darcy about it, and he noted that it seems like setting negatives here is an anti-pattern. More info: https://makerforce.io/css-negative-stroke-dashoffsets-inconsistencies/

Not sure why it's being flagged as 'Critical' in SonarQube, but it would be good to address.

## Version Number of TDS
0.29.0

<img width="823" alt="screen shot 2017-11-27 at 3 53 50 pm" src="https://user-images.githubusercontent.com/900447/33288777-6715348e-d38b-11e7-8cef-e06ab9c3f579.png">

**Comment by marcod1419** [comment]
@kretzm Hey Mike, is this issue still a problem for you? We're evaluating our open issues right now so it would be helpful to know. Thanks!

**Comment by kretzm** [comment]
Hey Marco, 
No I don't see this issue anymore in SonarQube, good to close
