### ISSUE TITLE
Responsive component children fail to transpile when using the callback syntax

### ISSUE THREAD

**Issue by aquirkles** [telus/tds-core#455]
## Description

- When using the callback syntaxt for my responsive component it looks like the children JSX fails to transpile to es5 code. When running the build command i see a parse error: 

## Reproduction Steps

Have attached screenshots and code samples

## Reproduction Percentage (if applicable)

- 10/10 times

## Screenshots

<img width="844" alt="screen shot 2018-01-18 at 9 35 40 am" src="https://user-images.githubusercontent.com/32460479/35103127-fe82abe2-fc32-11e7-89dd-9abc548a716a.png">

Problem code: https://gist.github.com/aquirkles/43155e56af125a12f700ba0ec3db08fd

Workaround here: https://gist.github.com/aquirkles/c91e909e25c4b173b348ea036764c95b

As you can see, when you just abstract the inner content to its own component and pass down isMobile as a prop, it works but its awkward

## Meta

- [ ] Currently using TDS version: v0.32.0
- [ ] Willing to develop solution - No bandwidth, sorry
- Has workaround? Yes, described above
- Impact: Pretty significant, but the simple workaround mitigates it

**Comment by theetrain** [comment]
After some more digging, I discovered this may be an issue with a certain babel plugin. I reached out to the babel team to find out more (see linked issue above).

**Comment by theetrain** [comment]
Update from Babel: by upgrading to Babel 7, this issue has been repaired.

Here is a sample project that breaks under babel 6, but transpiles on babel 7: https://github.com/theetrain/vanillareact/blob/bug/babel-plugin-transform-react-constant-elements/package.json 

My suggestion is to either use the workaround posted above, or upgrade your project to consume babel 7 (as of this writing is not yet stable).

**Comment by invalidred** [comment]
I believe it's the `react-optimize` plugin, if you remove the `react-optimize` plugin in .babelrc, you will not get this issue

**Comment by invalidred** [comment]
I just realized, but maybe this should be part of the `isomorphic-starter-kit` issues, please advice if it should be opened there. Also we keep seeing this issue re-occur over again in our production builds.

**Comment by theetrain** [comment]
@invalidred as confirmed above, this issue is not directly related to TDS, but with babel. Please see the issues posted above that are linked to Starter Kit configurations.
