### ISSUE TITLE
[Typography] Better word hyphenation

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#502]
## Why

On small screens such as the iPhone 5, long words in headings may exceed the width the screen. Since that is an unfavourable user experience, we should address text overflow within TDS while maintaining our content principles.

## What

It was previously brought to our attention that long words get cut off within headings (#442). To remedy this, we aggressively hyphenated _all_ words like so:

https://github.com/telusdigital/tds/blob/a81e985e58a5ec72e005e669a95c9a30e56456e2/src/components/Typography.modules.scss#L1-L4

There are some trade-offs to handling typography this way:

- Firefox does _not_ display hyphens 
![image](https://user-images.githubusercontent.com/12798751/36864143-d45812ba-1d59-11e8-922b-dd680dbc67e2.png)
- Body text displays hyphens even if it can sensibly break to a new line
  ![image](https://user-images.githubusercontent.com/12798751/36864246-264d8e24-1d5a-11e8-9bfe-89fb1b0ac93d.png)

## How

Let's gather more requirements in order to form a better solution. This leaves us with some open questions:

- What are our content standards regarding hyphens?
- Can we add hyphens only when a word exceeds the width of a single line?
- Can we find a solution that works with all the human languages we officially support?
- Should we expose wrapping settings from the Typography components for added control?

## References

Headings with long words get cut off - #442

**Comment by sean-saidmuradov** [comment]
IE11 doesn't handles hyphenation for Eligibility (LoopQual) page and brakes the same syllable to a new line no matter how big screen resolution is. An older version of FireFox (FF46) also brakes in to a new line but unlike IE11 does it more intelligently. Meaning it splits the word into different syllables based on widths of the screen.

**Comment by theetrain** [comment]
The recommendation moving forward is for copy writers to add hyphens manually or use `&shy;` to provide hyphenation hints for browsers. Learn more about [hyphens in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#suggesting-line-break-opportunities).

Hyphenation has been removed from tds-core components. See releases below.

Releases:

- [Split components (shared typography)](https://github.com/telus/tds-core/releases/tag/%40tds%2Fshared-typography%401.0.1)
- [v1.0.15 and v0.34.16](https://www.npmjs.com/package/@telusdigital/tds)
