### ISSUE TITLE
[Input] Standardize the appearance of number inputs across browsers

### ISSUE THREAD

**Issue by ryanoglesby08** [telus/tds-core#508]
## Description

`<input type="number" />` elements render differently across browsers, creating a divergent experience (most notably some browsers add a "spinner". [We have included styling tweaks for webkit based browsers only](https://github.com/telusdigital/tds/blob/master/packages/Input/Input.modules.scss#L3-L6). 

## Recommendation

There are some options here:

* Apply styling overrides to standardize the appearance/behaviour across browsers. This is non-trivial, requiring multiple customizations and is not guaranteed to work all the time.
* Apply styling overrides to hide the spinner across all browsers. Same caveat as above
* Allow the default browser styling to remain

I think this is a design/experience question. Customizing/removing the spinner may give a consistent experience for all users within the site, but changes how their browser behaves when compared to other sites, which may be worse overall.

## References

https://css-tricks.com/numeric-inputs-a-comparison-of-browser-defaults/

## Meta

* TDS version: 0.34, 1.0
* High impact: No

**Comment by lucylist** [comment]
we have decided not to prioritize this issue. the experience of having a 'spinner' on numeric input does not affect the users task at hand. they are still able to input the number via keyboard or other methods.
