### ISSUE TITLE
[Tooltip] box-shadow is off-centre in IE11 and Edge

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#534]
## Description

On Microsoft Edge and IE11, the Tooltip component's box-shadow effect differs from its appearance in other browsers as well as its respective Sketch symbol.

## Reproduction Steps

When browsing https://tds.telus.com/components/index.html#!/Tooltip/1 on IE Edge
* Click the tooltip icon
* Observe the box-shadow is misaligned

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: all
* Has workaround: No
* High impact: No

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/37794234-4ffa1d58-2de7-11e8-8cc9-53f93592f23c.png)

**Comment by marcod1419** [comment]
Tested on a real Windows 10 machine on IE 11. It appears that this is no longer an issue: 
![image](https://user-images.githubusercontent.com/10531523/71267743-6098c280-2319-11ea-93cb-39bc2ff02908.png)
