### ISSUE TITLE
Better Widow & Orphan control

### ISSUE THREAD

**Issue by hallaathrad** [telus/tds-core#610]
Our content, being presented in a responsive manner, wraps lines based on any screen size.
This usually leads to those pesky single words here and there at the last line of some paragraphs.

Those look dramatically not bueno, in terms of editorial design. And though far from perfect, CSS does offer some measures to mitigate the issue.
Here's an article I've found with a nice little compendium on vocabulary, and viable solutions, for those non-designey folks who may be interested in helping implement this into our famazing TDS.

http://thenewcode.com/946/CSS-last-line-Controlling-Widows-amp-Orphans

---
Willing to implement a solution myself, but surely could use some official time allocation for this task.
Alternatively, coming from a visual designer perspective, I can assist/review other devs who may want to contribute a solution throughout the platform.

**Comment by ryanoglesby08** [comment]
Thanks for bringing this up @hallaathrad.

I think we will want to engage with content strategy to figure out if and how to handle this.

**Comment by theetrain** [comment]
@alyciawilson @CSukhu do you have any insight on this topic? Perhaps this can lead to strategic documentation for teams to handle within their projects. The concern is by applying these rules globally, we may experience unintended consequences.

**Comment by alyciawilson** [comment]
We prefer no orphans. Please refrain if possible.

**Comment by theetrain** [comment]
We decided for now that this cannot be easily solved via code; outcome teams can handle orphan control depending on their content.

Feel free to comment on this issue if the need arises, along with a proposal.
