### ISSUE TITLE
[ChevronLink] Overflow on IE11

### ISSUE THREAD

**Issue by ah-arch** [telus/tds-core#642]
## Description

* The `a` tag has a nested `flex` element that is not wrapping on IE11.

## Reproduction Steps

* Open IE11
* Place `ChevronLink` in a parent with smaller width than its content, e.g. _Card_
* Observe that it overflows beyond its parent element:
<img width="343" alt="ie11 - chevronlink" src="https://user-images.githubusercontent.com/4450690/40444103-65179bfe-5e96-11e8-9bcf-09897eee3543.png">

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: [ChevronLink v1.0.2](https://github.com/telusdigital/tds-core/blob/0fc107436b29db6d7841e020c24eb45b3b6f2997/packages/ChevronLink/ChevronLink.modules.scss#L17)
* Willing to develop solution: Yes
* Has workaround: Yes
* High impact: Yes

## Suggestions
* Add `max-width: 100%` to `.link` in [ChevronLink.modules.scss](https://github.com/telusdigital/tds-core/blob/0fc107436b29db6d7841e020c24eb45b3b6f2997/packages/ChevronLink/ChevronLink.modules.scss#L17)

**Comment by jraff** [comment]
We must determine how to handle overflowing text in a `<ChrevronLink />`

**Comment by jraff** [comment]
@nicmak Will take this issue on once design is approved.

**Comment by nicmak** [comment]
@jraff  sure im down to take this issue

**Comment by marcod1419** [comment]
This will be fixed in an upcoming release. Thanks @nicmak for the contribution!

**Comment by jraff** [comment]
@ah-arch Fixed with @tds/core-chevron-link@1.1.1.

Thanks to @nicmak!
