### ISSUE TITLE
[Notification] Overflow on IE11

### ISSUE THREAD

**Issue by ah-arch** [telus/tds-core#643]
## Description

* The `p` tag is not wrapping on IE11.

## Reproduction Steps

* Open IE11
* Place the Notification with multi-line text that wraps, with a word longer than the width that requires a hyphen
* Observe that it overflows beyond the Notification background:
![ie11 - notification](https://user-images.githubusercontent.com/4450690/40492829-605664a2-5f3f-11e8-8570-ec69c9e9a1d2.png)

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: [Notification v1.1.1](https://github.com/telusdigital/tds-core/blob/5b09ab16755f663801ee44754f92258dcd15df5c/packages/Notification/Notification.jsx#L41)
* Willing to develop solution: Yes
* Has workaround: Yes
* High impact: No

## Suggestions

* `flex: 1` or `width: 100%` on the [Paragraph](https://github.com/telusdigital/tds-core/blob/5b09ab16755f663801ee44754f92258dcd15df5c/packages/Notification/Notification.jsx#L41) component in _Notification.jsx_

**Comment by theetrain** [comment]
Thank you for discovering this! I like the `width: 100%` approach. Though we may not attend this issue soon, feel free to submit a pull request if you have cycles 🚲.

**Comment by theetrain** [comment]
Resolved in `@tds/core-notification@1.1.8`, `@telusdigital/tds@1.0.20`
