### ISSUE TITLE
[ExpandCollapse] - Heading text does not wrap on IE11

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#655]
## Description

Large heading text on ExpandCollapse Panels do not wrap on IE11, causing overflow issues that flows through tertiaryText.

## Reproduction Steps

1. Open ExpandCollapse Example
2. Add a very long Panel heading
3. Add tertiaryText
4. Observe the Panel heading overflows outside the wrapper boundaries, and that tertiaryText gets covered

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: core-expand-collapse 1.0.2
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/41374188-7a6e79b0-6f20-11e8-96f5-620e63e14795.png)

**Comment by jraff** [comment]
Fixed with [@tds/core-expand-collapse@1.1.2](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%401.1.2)
