### ISSUE TITLE
[Checkbox+Radio] Allow boolean PropType for value

### ISSUE THREAD

**Issue by ah-arch** [telus/tds-core#657]
## Description

* The **value** for a `Checkbox` or `Radio` could be a _boolean_, but currently only a [string or number](https://github.com/telus/tds-core/blob/b5486cad0bff3419b14b6d2933fa336d58c40aea/shared/components/FormField/FormField.jsx#L173) is allowed
  * It currently displays the failed prop type console error, but works as intended as a boolean for storage and form submission
  * A unnecessary workaround to avoid the console error is to convert the store value to a string and then convert it back to a boolean if the string matches a boolean word when submitting

## Recommendation

* Update `value` to `PropTypes.oneOfType([PropTypes.string, PropTypes.number, PropTypes.bool])` in:
  * [Radio](https://github.com/telus/tds-core/blob/b937a2e88e0ba52892bc808a62370088038d0363/packages/Radio/Radio.jsx#L38)
  * [Checkbox](https://github.com/telus/tds-core/blob/b937a2e88e0ba52892bc808a62370088038d0363/packages/Checkbox/Checkbox.jsx#L32)
  * [Choice](https://github.com/telus/tds-core/blob/4e992b2ac235fcfd11fcbd3e58e16c03fc0ce5ca/shared/components/Choice/Choice.jsx#L179)

## Meta

* TDS version: v1.0.4
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

**Comment by theetrain** [comment]
Good catch! Let us know if you're able to contribute a fix for this and we'll assign this story to you. Otherwise, it will remain on our team backlog until the next maintenance cycle.
