### ISSUE TITLE
[ExpandCollapse] Disabled styles are being overwritten

### ISSUE THREAD

**Issue by gcrossfield** [telus/tds-core#658]
## Description

* When using ExpandCollapse and setting Panel to `disabled` the panel is losing it's light grey background and a pointer cursor shows on hover. This seems to be due to the clickable class being declared in the head after the disabled class.

## Reproduction Steps

* Load the shop/checkout/v2/customer page found in the telus/hs-checkout-v2 repo (dev environment)
* Hover over a disabled Panel (they should all be disabled aside from the first Panel)

## Reproduction Percentage (if applicable)

* 10/10 times in dev environment, haven't tested in staging or production.

## Meta

* Component version: v1.0.3
* Willing to develop solution: Yes
* Has workaround: No
* High impact: No (the functionality is fine, its purely css related)

## Screenshots

<img width="800" alt="screen shot 2018-06-19 at 1 13 56 pm" src="https://user-images.githubusercontent.com/729558/41672268-545b2d6a-746e-11e8-94cf-8e8c507fdda6.png">

## Possible solution

* Remove classes that contradict the disabled state. ie. clickable

**Comment by theetrain** [comment]
Hi Greg, thanks for contributing this issue. If you have cycles to contribute, let us know and we'll assign it to you. For now, it will remain on the team's backlog.

**Comment by gcrossfield** [comment]
@theetrain This issue has seemed to resolve itself within our app. We didn't change versions or make an intentional effort to fix.
