### ISSUE TITLE
[ExpandCollapse] Panel height not dynamic

### ISSUE THREAD

**Issue by gcrossfield** [telus/tds-core#671]
## Description

* This defect is to highlight when the height of a child is manipulated within the `ExpandCollapse.Panel`. Currently, the Panel does not resize if the height of any of it's children are altered, but seems to resolve itself after a render is emitted from one of the other components or if the `Panel` is closed and re-opened.

## Reproduction Steps

* Visit staging
* In the **Filter** Click **Internet (copper)**
* Select a **(mtm)** internet plan - ie. **Internet 15 (mtm)**
* Just below the TELUS Header is a button that says **Go to cart page**, click that
* Tab through all of the fields in the first form to make them invalid
* Notice that the purple button has disappeared due to the error validation heights of the 4 fields

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: v1.0.3
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

## Screenshots

![actual](https://user-images.githubusercontent.com/729558/42241887-fdb3977e-7ec0-11e8-9aff-10639238a3f3.png)
![expected](https://user-images.githubusercontent.com/729558/42241888-fdcdb71c-7ec0-11e8-8be0-d13986b3392e.png)

**Comment by varunj90** [comment]
as communicated by Maibel Rafferty (PO Checkout HS), they have a release 
July 19th and require TDS support to get this ticket resolved. @gcrossfield was willing to contribute but his bandwidth is required in other tasks. 

TDS to review this and add to backlog.

**Comment by theetrain** [comment]
This has been patched in [@tds/core-expand-collapse@1.0.5](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%401.0.5)

**Comment by gcrossfield** [comment]
Thanks guys!
