### ISSUE TITLE
Ordering of Columns in FlexGrid

### ISSUE THREAD

**Issue by Ryanschmied** [telus/tds-core#672]
## Description

* When using FlexGrid, there is no ability to modify the order of columns for different screen sizes.

## Recommendation

* Introduce flex-reverse attribute or something similar to allow for columns to be reorganized for different screen sizes.

## Designs
-FlexGrid on larger screens:
![image](https://user-images.githubusercontent.com/27220684/42244281-69da50a2-7ee2-11e8-9837-a5e2cdd59071.png)

-FlexGrid on smaller screens:
![image](https://user-images.githubusercontent.com/27220684/42244308-88eecd7e-7ee2-11e8-8ca7-ba7face6e464.png)

-Ideally would like the columns to be arranged like this on smaller screens:
![image](https://user-images.githubusercontent.com/27220684/42244330-9acb8eec-7ee2-11e8-9375-add57aa5c103.png)

## Meta

* TDS version: v 2.0
* Willing to develop solution: No
* Has workaround: Yes
* High impact: Yes

**Comment by jraff** [comment]
Feature added in [@tds/core-flex-grid@2.1.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-flex-grid%402.1.0)
