### ISSUE TITLE
[Select] Special disable state when only one option element exists.

### ISSUE THREAD

**Issue by mujtabahasni** [telus/tds-core#680]
## Description

* The My Telus team uses the Select component for switching/selecting billing accounts.  
* Often the customer only has one account or service address, so the user doesn't need to interact with the Select component. 
 * The default disabled state does not visually express the intent of displaying their current service account. (It looks like its disabled)

## Recommendation
The *single-option* state is a state where the down-carret icon is removed and input events are ignored but it does not appear "disabled".  

* If only one option element remains, render the component in the *single-option* state.  This behavior can be made as default, or enabled by a property.

* Any feedback or error state (including icon) will display as usual.  

* Clicking on the element in this state will not display a drop-down list or generate a change event.

## Designs

The Select component in the proposed *single-option* state will the appear as default, but without the down-carret:

![image](https://user-images.githubusercontent.com/32303524/42581288-655eb158-84fa-11e8-8bdd-f21ee0564168.png)

## Meta

* TDS version: v1.0.7
* Willing to develop solution: Yes
* Has workaround: Yes
* High impact: No

**Comment by theetrain** [comment]
cc @Berjesty please have a look at this UX pattern to see if it needs approval.

**Comment by Berjesty** [comment]
I will review this with design leads on friday. @theetrain

**Comment by Berjesty** [comment]
Update: we didnt have leads meeting since. We have one this this Friday, will review with design leads and provide feedback right after.

**Comment by Berjesty** [comment]
@mujtabahasni @varunj90  This was discussed in this week's design leads meeting and decision was made that this component may lead to cognitive confusion for users when determining if it's clickable or not, and do not support usability heuristics. If requires further discussion I will be happy to provide more insight, for now it can be closed.
