### ISSUE TITLE
[Input] Text is cut off at normal zoom level

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#688]
## Description

The Input component displaying hanging characters such as `g` get cut off at the bottom (see screenshot).

## Reproduction Steps

1. Visit the Input documentation at 100% zoom level
2. Enter a lowercase `g`
3. Observe the character being cut off at the bottom

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: core-input@1.0.8
* Willing to develop solution: Yes
* Has workaround: No
* High impact: No

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/42825057-3014c3d4-89af-11e8-969c-b5e8706a009d.png)

**Comment by jraff** [comment]
Fixed in [@tds/core-input@1.0.10](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-input%401.0.10)
