### ISSUE TITLE
[Select] Custom options

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#701]
## Description

The core-select component currently uses browser-specific 'option' interfaces for each `<option>`. There are two drawbacks:

1. Depending on the browser you are using, the options' aesthetic differs from the branded Select
2. Options can only have a single 

See #484 

## Recommendation

**Design review needed**
Provide a prop interface that accepts different types of content.

Potential use cases:

* Multi-line options
* Options with headings
* Filterable options

## Designs

**Design needed**

## Meta

* TDS version: all
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

**Comment by jraff** [comment]
@aneesh-datta @ah-arch and Apurv Do you already have this designed? If so, please work with us to have this added to core.

**Comment by ah-arch** [comment]
Our previous [design](https://telus.invisionapp.com/d/main/#/console/13656199/284766908/preview) looks different from the design in the screenshot: https://github.com/telus/tds-core/issues/484#issuecomment-367403345
(The closed state has two lines and the selected state has a checkmark)

**Comment by theetrain** [comment]
@Berjesty please include this new design for Select in an upcoming design review.

**Comment by lucylist** [comment]
design is yet to be resolved. the previous designs weren't accessible and we need align on the treatment. i think the consensus was that it'd be purple highlight with a bold text.
<img width="512" alt="screenshot 2018-08-14 14 20 02" src="https://user-images.githubusercontent.com/17018330/44162041-0f295500-a08d-11e8-9986-86fee93f0356.png">
<img width="503" alt="screenshot 2018-08-14 14 20 13" src="https://user-images.githubusercontent.com/17018330/44162042-0f295500-a08d-11e8-9e6f-73c641710c97.png">

**Comment by jraff** [comment]
@Berjesty and her team do not have cycles to design this.

**Comment by Christina-Lo** [comment]
@Berjesty is there anyone I can get the working file off of?

**Comment by lucylist** [comment]
@Christina-Lo .. @apurv has the design files

**Comment by theetrain** [comment]
@lucylist will take this to design review

**Comment by ah-arch** [comment]
This is the sample code from a previous project:
https://github.com/telus/business-requests/tree/master/ui/src/components/base/forms/Dropdown

It has been developed as a **[redux-form](https://github.com/telus/business-requests/blob/master/ui/src/components/base/forms/Dropdown/Dropdown.jsx#L264-L279)** component, i.e. expects the `input` and `meta` props.
And it accepts a list of [options](https://github.com/telus/business-requests/blob/master/ui/src/components/base/forms/Dropdown/Dropdown.jsx#L254-L257) with custom `content`.

**Comment by Christina-Lo** [comment]
This has been backlogged

**Comment by lucylist** [comment]
has been design reviewed and component looks good as is to be modified into tds-core. we will bold the hover state text.

**Comment by varunj90** [comment]
@telus-kyri issue mentioned in community - https://github.com/telus/tds-community/issues/131 needs to be addressed

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
