### ISSUE TITLE
[FlexGrid] - Add support for responsively hiding columns

### ISSUE THREAD

**Issue by Andrew-K-Lam** [telus/tds-core#707]
## Description

* I would like to be able to hide columns on different viewports

## Recommendation

* Add props to FlexGrid.Col that hides the column

## Meta

* TDS version: latest
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

**Comment by jraff** [comment]
Closed with [@tds/core-flex-grid@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-flex-grid%402.2.0)
