### ISSUE TITLE
Steptracker UI Discrepancy

### ISSUE THREAD

**Issue by cherryhung** [telus/tds-core#731]
## Description

* There is a discrepancy between the steptracker UI on DSM and in code. On DSM, there is a grey background while tds.telus.com has a white background and divider line. 

## Reproduction Steps

* N/A

## Reproduction Percentage (if applicable)

* N/A

## Meta

* TDS version: v1.0.5
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

## Screenshots

* Include any relevant screenshots
<img width="717" alt="dsm" src="https://user-images.githubusercontent.com/40604656/45371287-386bd100-b5b8-11e8-8790-c099d5e12035.png">
<img width="1093" alt="tdscom" src="https://user-images.githubusercontent.com/40604656/45371294-3dc91b80-b5b8-11e8-9a85-c892f80101e0.png">

**Comment by lucylist** [comment]
hey @cherryhung thanks for noting this! It looks like the component is able to have a grey background and not.
we will match the tds docs example to match with the DSM component and also provide guidelines on usage

**Comment by theetrain** [comment]
Next steps: determine whether StepTracker should be a full-width component (like Notification), or should optionally pass in a prop to make its background Athens Grey.

**Comment by theetrain** [comment]
We will enhance the StepTracker to be a full-width component with a default background of Athens Grey that can be optionally set to white (not transparent).

**Comment by theetrain** [comment]
Update: this story is being tracked in https://telusdigital.atlassian.net/browse/TDS-985

**Comment by marcod1419** [comment]
This is added in the latest version of StepTracker! @cherryhung
