### ISSUE TITLE
Create checkboxes that are controlled inputs

### ISSUE THREAD

**Issue by aquirkles** [telus/tds-core#736]
## Description

The currently existing checkboxes are not controlled inputs, this makes it very easy for the application state to become misaligned with the input state.

## Recommendation

Remove internal state of form inputs. Allowing inputs to contain internal state that may or may not be in sync with application state violaties the principle of unidirectional data flow and is fundamentally at odds with the philosophy underpinning redux, which is part of RA

## Meta

* TDS version: current
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

**Comment by jraff** [comment]
@simpleimpulse to reach out to @jesdavpet.

**Comment by simpleimpulse** [comment]
We have captured the fix to this issue in this JIRA ticket: https://telusdigital.atlassian.net/browse/TDS-1015

**Comment by theetrain** [comment]
Update:

We plan on re-releasing our various form components (core-input, core-checkbox, core-radio, etc) as stateless React components, as well as a new utility component that can wrap these stateless components and provide self-managed state for them. 

We welcome your feedback as we follow through with these changes.

**Comment by theetrain** [comment]
[Checkbox 2.0.0](https://github.com/telus/tds-core/blob/57abc7ba5ffc8e440cd153eafb777c6c16a01833/packages/Checkbox/CHANGELOG.md#200-2019-05-23) is a functional component that can be controlled or uncontrolled.

[See documentation for Checkbox.](https://github.com/telus/tds-core/blob/57abc7ba5ffc8e440cd153eafb777c6c16a01833/packages/Checkbox/Checkbox.md)
