### ISSUE TITLE
Horizontal content alignment in a Column similar to FlexGrid.Row

### ISSUE THREAD

**Issue by nikaukraine** [telus/tds-core#754]
## Description

* Horizontal content alignment in a Column similar to FlexGrid.Row

## Recommendation

* Ability to align content horizontally in a **column** (Left/Center/Right), similar to FlexGrid.Row

## Designs

n/a

## Meta

* TDS version: latest
* Willing to develop solution: No
* Has workaround: Yes
* High impact: Yes
* Designer/Developer Pair: Nika Karliuchenko

**Comment by jraff** [comment]
@nikaukraine  Can you provide a screen shot of the intended designs.

**Comment by nikaukraine** [comment]
Any block which has image and content: https://telus-site-builder-test-ui-site-builder.c1b9.telusdigital.openshiftapps.com/en/sandbox/layoutgrids-catalogue

In most of the cases the image should be centered, but the text aligned the left/right.

**Comment by nikaukraine** [comment]
Team, do you think it can be done? I am recommending hacky solutions to people for now, it would be super nice if we have it 💘 
If this is logically correct and possible please let me know an ETA (no rush, just planning).

**Comment by jraff** [comment]
@nikaukraine fixed with @tds/core-flex-grid@2.3.0
