### ISSUE TITLE
<ExpandCollapse.Panel header={HEADER_VALUE} /> can accept other types of props other than a simple string

### ISSUE THREAD

**Issue by Jeffrey-Chang** [telus/tds-core#762]
## Description

* The `<ExpandCollapse.Panel header={HEADER_VALUE} />` is expecting only strings. If passed anything else other than a string, it will warn with a propType warning. Due to the strictness of the propType, developers are not able to pass in any other TDS components. One such example would be to add a `<Text.Sup />` or even `<A11yContent />` to the text that will be displayed for their respective purposes.

## Recommendation

* Change <ExpandCollapse.Panel> header prop to accept a node instead of a string. It good also potentially be a good idea to also change `subtext` and `tertiaryText` to also accept a node instead of a string.

## Designs

<img width="892" alt="screen shot 2018-10-18 at 11 37 33 am" src="https://user-images.githubusercontent.com/30445300/47166450-389f7080-d2ca-11e8-90f0-443beb43def0.png">

## Meta

* TDS version: v1.1.2
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes
* Designer/Developer Pair: @Jeffrey-Chang, @Berjesty, @jesdavpet

**Comment by jesdavpet** [comment]
I'd like to add that it seems like some other `TDS Core` components set a precedent that would support the approach of opening up this `propType` validation to include `node` as well as `string`.

One example would be the `label` property of [@tds/core-checkbox](https://tds.telus.com/components/index.html#checkbox)

**Comment by jraff** [comment]
Thanks for reporting this @Jeffrey-Chang, are you still willing to develop a solution to this? If so, we've built a [propTypes](https://github.com/telus/tds-community/tree/master/shared/utils/propTypes) util into TDS community that will help with this. We will need to publish this to npm first.

**Comment by Jeffrey-Chang** [comment]
@jraff I am still willing to develop a solution to this :)

**Comment by theetrain** [comment]
The ability to add superscript text to an ExpandCollapse Panel header is now available in [@tds/core-expand-collapse@1.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%401.2.0).
You can pass a double-caret template to the `header` prop such as `ProductName^^&trade;^^` to render superscripts like so: **ProductName<sup>&trade;</sup>**.

If there is a need to accept `<A11yContent />` within ExpandCollapse, feel free to open a separate issue.
