### ISSUE TITLE
FlexGrid Row looks expanded vertically in IE11

### ISSUE THREAD

**Issue by hamedmam** [telus/tds-core#783]
## Description

- FlexGrid issue with IE 11. When an image is wrapped inside FlexGrid.Col, it causes whitespace to appear above and below the FlexGrid parent.

## Reproduction Steps

- We made a temporary fix to site-builder, I am not able to reproduce at this point but wrapping the image in a `FlexGrid.Col` should reproduce the issue in IE 11

## Meta

- TDS version: v2.2.0
- Willing to develop solution: No, since @theetrain  is aware of fix I would kindly ask TDS team as I am currently overloaded with CPP work
- Has workaround: Yes
- High impact: Yes

**Comment by marcod1419** [comment]
Hey @hamedmam, would you be able to provide more detailed reproduction steps? Specifically naming which image component causes this issue. As it is, I can't reproduce this. Thanks!

**Comment by theetrain** [comment]
@hamedmam and I had a conversation. On IE11, the issue gets resolved when you add `flex-shrink: 0;` to the `<FlexGrid.Row />` component.

The core team will get around to this, though contributions are welcome!

**Comment by hamedmam** [comment]
@marcod1419 I am sorry I missed your ping here, we already discussed the details with Enrico, if you need more details please let me know

**Comment by marcod1419** [comment]
This is fixed on the latest version of FlexGrid! @hamedmam
