### ISSUE TITLE
[Bug][IE11] - ChevronLink appear mis-aligned when used in Notification

### ISSUE THREAD

**Issue by mujtabahasni** [telus/tds-core#793]
## Description

In IE11 ChevronLink appears misaligned with other text when used inside a notification. 

## Reproduction Steps
I've reproduced this within the TDS doc site: 
![image](https://user-images.githubusercontent.com/32303524/48094331-eb833000-e1df-11e8-848b-874e72855aec.png)

## Workarounds: 
I've reported this earlier to #tds-support and a work around was found by applying `display: inline-flex` onto the ChevronLink.   The change doesn't appear to impact other browsers.

## Meta

- TDS version: vX.Y.Z
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: No

**Comment by ah-arch** [comment]
Encountering this issue in our app too, but not just limited to `Notification`:
![ie alignment](https://user-images.githubusercontent.com/4450690/50603254-e3660a80-0e87-11e9-8083-470d16883ff2.png)

Could also apply either `vertical-align: top` or `display: -ms-inline-flexbox` or to fix this.

**Comment by theetrain** [comment]
This has been resolved in [`@tds/core-chevron-link@2.1.8`](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-chevron-link%402.1.8)
