### ISSUE TITLE
Add ability to align items within FlexGrid.Col

### ISSUE THREAD

**Issue by hamedmam** [telus/tds-core#798]
## Description

- Often teams desire to have items aligned in sibling columns or cards

## Recommendation

- Based on the conversation I had with wonderful @theetrain he gave me a code sandbox to achieve this but I believe it would be great to have this embedded into FlexGrid.

## Designs

<img width="1325" alt="screen shot 2018-11-08 at 12 30 36 pm" src="https://user-images.githubusercontent.com/24867760/48216668-54d78000-e353-11e8-8dcd-e0c4bd287f86.png">

## Code Sandbox
https://codepen.io/etrain/pen/rQxwje

**Comment by nikaukraine** [comment]
The other example is the first block on the page: https://www.telus.com/en/deals-and-bundles/black-friday

**Comment by varunj90** [comment]
this is the next item to be picked in our queue now: https://telusdigital.atlassian.net/browse/TDS-1035

**Comment by jraff** [comment]
Fixed in [@tds/core-box@1.1.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-box%401.1.0)
