### ISSUE TITLE
[Image] make height and width optional

### ISSUE THREAD

**Issue by timhysniu** [telus/tds-core#820]
## Description

- Image component currently has a requirement that we pass in a width and a height. Do both these fields need to be required?

https://github.com/telus/tds-core/blob/master/packages/Image/Image.jsx#L55-L59

## Recommendation

- width and height properties are optional

**Comment by jraff** [comment]
@timhysniu Can you please provide a use-case for this ask?

**Comment by hamedmam** [comment]
I can talk about how we do it in site builder. Basically we have a ResponsiveImage component that takes width value as an option but if you dont pass any value for width the image would take the container width so it is responsive.

**Comment by timhysniu** [comment]
The motivation behind creating this issue was the fact that I get PropType warnings if I don't pass in both, `height` and `width`. The use case that we typically deal with is using images with `width` that span its container, so 100%. To preserve aspect ration we don't specify a height at all (which would then be auto). If both are required then almost always I will be seeing PropType warnings.

This isn't a high priority issue.

**Comment by twirlingsky** [comment]
HS ad card images fall into this discussion:
![Screen Shot 2019-03-08 at 13 16 24](https://user-images.githubusercontent.com/22402633/54056320-8d258880-41a4-11e9-87ce-0cc6d3a2051f.png)

**Comment by theetrain** [comment]
Hi @timhysniu,

After discussing with our team, we believe it would be appropriate to no longer make the `width` and `height` props required. By default, the image component implements dynamic width and height CSS, which should fulfil the use case described above.

### Proposal

- make `width` and `height` props optional
- provide usage criteria in the documentation to recommend supplying a `width` or `height` to hold their dimensions on the page before the images are downloaded

Are you willing to make a pull request?

**Comment by Andrew-K-Lam** [comment]
When using Image from core-image, I get a scrollbar at the bottom of the screen:
![image](https://user-images.githubusercontent.com/931411/69761399-49f5b600-1135-11ea-8689-58a868b5daed.png)

The image is large 
Width: 2800 px
Height: 716 px

The image is wrapped in a Flexgrid Row and Col.

**Comment by theetrain** [comment]
This is closed due to low demand. Please keep in mind, the `width` and `height` props are still required since they correspond to the `img` element's width and height attributes. It's good practice to define image proportions so that they load a smooth user experience.
