### ISSUE TITLE
[ExpandCollapse] - code splitting Panels

### ISSUE THREAD

**Issue by ElliottJRo** [telus/tds-core#839]
## Description
Currently the ExpandCollapse component requires direct children to be of type Panel. This is great for making small components that have 1 or 2 basic Panels but when the Panel render logic becomes more and more complicated I would like to be able to split each Panel into its own component.

**This is the recommended way according to the docs:**
```jsx
<ExpandCollapse>
  <ExpandCollapse.Panel id="OptikTV" header="TELUS Optik TV^^&trade;^^">
    <Box between={2}>
      <Heading level="h4">...</Heading>
      ...
    </Box>
  </ExpandCollapse.Panel>
  ...
  ...
</ExpandCollapse>
```

**This is the workaround in place given that we cannot separate the entire panel component:**
```jsx
<ExpandCollapse>
  <ExpandCollapse.Panel id="OptikTV" header="TELUS Optik TV^^&trade;^^">
    <PanelComponent1
      renderProp1={data}
      renderProp2={data2}
    />
  </ExpandCollapse.Panel>
  <ExpandCollapse.Panel id="panel-id-2" header="Another header here">
    <PanelComponent2
      renderProp1={data}
      renderProp2={data2}
    />
  </ExpandCollapse.Panel>
  ...
</ExpandCollapse>
```
## Recommendation

This is the ideal way in my opinion:
```jsx
// ParentComponent.jsx
<ExpandCollapse>
  <PanelComponent1
    renderProp1={data}
    renderProp2={data2}
  />
  ...
  ...
</ExpandCollapse>
```

```jsx
// PanelComponent1.jsx
const Panelcomponent1 = ({ renderProp1 , renderProp2}) => {
  // be able to conditionally render based on props
  if (renderProp2 === 123) return null

  // be able to do its own render logic
  const header = renderProp1 ? `${renderProp1} is the header` : 'Select something'
  const epicPrice = renderProp2 * 100 + 0.03 + 10

  return (
    {/* be able to return ExpandCollapse.Panel */}
    <ExpandCollapse.Panel id="special-id-here" header={header}>
      <Box between={2}>
        <Heading level="h4">Final discout: ${epicPrice}</Heading>
        ...
      </Box>
    </ExpandCollapse.Panel>
  )}
```

## Best workaround based on @theetrain 's feedback
```jsx
// ParentComponent.jsx
<ExpandCollapse>
  { PanelComponent1({
      renderProp1: data,
      renderProp2: data2
    })
  }
  ...
  ...
</ExpandCollapse>
```

```jsx
// PanelComponent1.jsx
const Panelcomponent1 = ({ renderProp1 , renderProp2}, content) => {
  // be able to conditionally render based on props
  if (renderProp2 === 123) return undefined

  // be able to do its own render logic
  const header = renderProp1 ? `${renderProp1} is the header` : 'Select something'
  const epicPrice = renderProp2 * 100 + 0.03 + 10

  return (
    {/* be able to return ExpandCollapse.Panel */}
    <ExpandCollapse.Panel id="special-id-here" header={header}>
      <Box between={2}>
        <Heading level="h4">Final discout: ${epicPrice}</Heading>
        <Text>additional content {content}</Text>
        ...
      </Box>
    </ExpandCollapse.Panel>
  )}
```

## Meta

- TDS version: v1.2.0
- Willing to develop solution: Yes - Would need some help however
- Has workaround: Yes
- High impact: No
- Designer/Developer Pair: N/A ?

**Comment by theetrain** [comment]
I can see how it would be ideal to pass in Panels as children of `<ExpandCollapse />` that render conditionally, but ExpandCollapse's `children` PropType expects components named `ExpandCollapse.Panel`, so a custom component would throw an error.

Rather than passing higher order components to an `<ExpandCollapse />` as children, you could try using functions. For example:

(You can paste the snippet below into the code sandbox found in the [ExpandCollapse documentation](https://tds.telus.com/components/index.html#!/ExpandCollapse/0).)

```jsx
const myPanel = (renderProp, content) => {
  if (!renderProp) {
    return undefined
  }

  return <ExpandCollapse.Panel id="1" header={renderProp}>{content}</ExpandCollapse.Panel>
};

const data = undefined;

<ExpandCollapse tag="h2">
  {myPanel(data, "Hello")}
  <ExpandCollapse.Panel id="2" header="My Panel">Hello</ExpandCollapse.Panel>
</ExpandCollapse>
```

In this way, React would render `<ExpandCollapse.Panel />` as a child component without throwing PropType errors, and you can have more control over its rendering logic.

**Comment by ElliottJRo** [comment]
!! I think the solution you mentioned solves my problem. Best solution so far:
1) Solves the code splitting problem
2) Allows child panel components to be testable on its own

Sure syntax is slightly different from normal functional components:
```jsx
<PanelComponent
  prop1={data}
  prop2={data2
/>

// vs

{ PanelComponent({ prop1: data, prop2: data }) }
```

however, I think this is an acceptable tradeoff given how it solves the main purpose of this feature request

**Comment by simpleimpulse** [comment]
Closing this since it is no longer an issue.
