### ISSUE TITLE
[FlexGrid] Rows wrap offscreen when parent wrapper is too short

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#841]
## Description

Originally reported by @mendoncp and @nateriesling who are willing to contribute.

On all browsers, using `<FlexGrid />` that has two or more `<FlexGrid.Row />` children in a wrapper that has a height smaller than the contents of all Rows causes the rows to wrap towards the right, as is the behaviour of `flex-direction: column; flex-wrap: wrap;`.

## Reproduction Steps

- Set up a container similar to this on https://tds.telus.com/components/index.html#flexgrid

```jsx
<div style={{ height: "10px", display: "flex", flexDirection: "column" }}>
  <FlexGrid>
    <FlexGrid.Row>
      <FlexGrid.Col>Content</FlexGrid.Col>
    </FlexGrid.Row>
    <FlexGrid.Row>
      <FlexGrid.Col>Content</FlexGrid.Col>
    </FlexGrid.Row>
  </FlexGrid>
</div>
```

- Observe the second row wrapping towards the right

## Proposal

Apply `flex-wrap: nowrap` to the `<FlexGrid />` component, so that Rows do not wrap onto the next column.

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS version: v2.2.0
- Willing to develop solution: Yes
- Has workaround: Yes
  - By nesting all content in a single `<FlexGrid.Row />`, the wrapping effect is avoided
  - By making the parent wrapper have a fluid height, the wrapping effect is avoided 
- High impact: Yes

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/49304278-dc6b6700-f499-11e8-8f5c-d9dc72e69f96.png)

**Comment by theetrain** [comment]
Hi @mendoncp @nateriesling, if you are willing to contribute this fix we will support you.

**Comment by marcod1419** [comment]
Going to close this, looks like this is an issue of the container using viewport height. If `vh` is used, this behaviour is expected.
