### ISSUE TITLE
Price Lockup - $ alignment issues

### ISSUE THREAD

**Issue by erichwelz** [telus/tds-core#843]
## Description

In a troubleshooting session with @theetrain : he discovered that our CSS modules are loading in an unexpected order which can result $ alignment issues

No production link currently available. Please reach out directly if test account needed

## Reproduction Steps

- Click this thing
- Now click this
- Observe this happens

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS version: v1.0.1
- Willing to develop solution: No
- Has workaround: No
- High impact: No

## Screenshots

- Include any relevant screenshots
![screen shot 2018-12-03 at 11 59 29](https://user-images.githubusercontent.com/4743553/49388872-f81d7a00-f6f2-11e8-812d-6af8b9b3a8cd.png)

**Comment by marcod1419** [comment]
This is available in the newest version of PriceLockup!
