### ISSUE TITLE
[core-input] error icon flashes when changing feedback prop

### ISSUE THREAD

**Issue by xingbo828** [telus/tds-core#861]
## Description

When changing the Input component's feedback prop from 'success' to undefined. It shows the 'error' state for 100ms and then changes to the `no feedback` mode.

## Reproduction Steps

Set the feedback prop to 'success' and change it to undefined

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS version: latest
- Willing to develop solution: No
- Has workaround: No
- High impact: Yes

## Screenshots

Can't take a screenshot.

**Comment by theetrain** [comment]
Thanks for reporting this. We have backlogged this and will get to it. I managed to reproduce your issue in the animation below:

![screen recording 2018-12-12 at 03 28 pm](https://user-images.githubusercontent.com/12798751/49897087-269e0200-fe23-11e8-9549-30f2f8a8c1d2.gif)

**Comment by marcod1419** [comment]
This is fixed in the latest version of Input!
