### ISSUE TITLE
[UnorderedList] Realign items

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#869]
## Problem statement

The TSD_core library propose a component named ‘LISTS’. 
There is a padding on the left  (green color) of the bullet points. This padding is not flexible and doesn’t permit to create a more structured layout. 

## Recommendation

Description of the proposed solution
I would like to have more flexibility to use this list without padding in front of the bullet points. In that case, we could align all the texts to have a better visual design.

## Designs

- Screenshots
<img width="882" alt="screen shot 2018-12-18 at 4 04 40 pm" src="https://user-images.githubusercontent.com/44266628/50227510-e33c1a00-0373-11e9-9aa6-6c42186b7443.png">

- Sketch file: 
     > what we have currently: https://telus.invisionapp.com/d/main/#/console/16159628/337702564/preview
     > what we would like: https://telus.invisionapp.com/d/main/#/console/16159628/337702563/preview

- TDS website reference: https://tds.telus.com/#lists

## Meta

- Include component name and version: 2.0.2
- Willing to develop solution: No
- Has workaround: Yes
- High impact: No
- Designer/Developer Pair: Marie Fuhrmann / @Berjesty / @Jeffrey-Chang / @invalidred

**Comment by Christina-Lo** [comment]
@Mariefhrmnn will provide design intent and designs for Berjesty to bring to Design Leads meeting to see if this is a design we want to move forward with

**Comment by simpleimpulse** [comment]
@Mariefhrmnn Any updates on this?

**Comment by Mariefhrmnn** [comment]
@simpleimpulse Waiting for the approuval by the design leads with @Berjesty

**Comment by Berjesty** [comment]
Design leads have agreed that the suggested styling is preferred for the visual harmony and legibility of information on the page. As for next steps pls replace the suggested padding in TDS with the current version.

**Comment by theetrain** [comment]
We have decided to issue a patch release for indentations in OrderedLists and UnorderedList. We welcome pull requests for any developers willing to take this on!

**Comment by Mariefhrmnn** [comment]
Maybe someone in the Jackelope's team? @invalidred @jesdavpet @Jeffrey-Chang?

**Comment by theetrain** [comment]
Note to developer: let's reflect these changes on DSM before releasing.

**Comment by theetrain** [comment]
This is being worked on in https://telusdigital.atlassian.net/browse/TDS-1417

**Comment by marcod1419** [comment]
This has been addressed in UnorderedList 3.0.7!
