### ISSUE TITLE
[ExpandCollapse] - calling setState in child component causes re-render

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#879]
## Description

Originally reported by @nicmak 

When a child component within `<ExpandCollapse.Panel />` calls `this.setState()`, the parent `<ExpandCollapse />` component re-renders and returns to its default state, which is collapsed. 

## Reproduction Steps

1. Using the following code sample:

```jsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props)

    this.changeHandler = this.changeHandler.bind(this)
  }

  state = {
    checked: false
  }

  changeHandler() {
    this.setState((previous) => {
      return { checked: !previous.checked }
    })
  }

  render() {
    return (
      <ExpandCollapse tag="h2">
        <ExpandCollapse.Panel id="features" header="Features">
          <Checkbox
            label="Hello"
            name="hello"
            value="Hii"
            checked={this.state.checked}
            onChange={this.changeHandler}
          />
        </ExpandCollapse.Panel>
      </ExpandCollapse>
    )
  }
}
```

2. Render in a React application
3. Click on the `<Checkbox />` component
4. Observe the `<ExpandCollapse.Panel />` collapses

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS version: v1.2.3
- Willing to develop solution: Yes, by @nicmak 
- Has workaround: No
- High impact: No

## Screenshots

![screen recording 2018-12-31 at 02 43 pm](https://user-images.githubusercontent.com/12798751/50566686-7c6f1700-0d0a-11e9-8720-c7be33eb175f.gif)

**Comment by ah-arch** [comment]
ExpandCollapse’s `componentWillReceiveProps` is not triggered by PanelWrapper’s `onClick/togglePanel`, but `this.setState` does. That resets the `openPanels` back to what `props.open` was set to, which was originally nothing:
https://github.com/telus/tds-core/blob/727f5211fabc00554573bf61e5a1863d25462244/packages/ExpandCollapse/ExpandCollapse.jsx#L22-L23

Perhaps if `nextProps.open` differs with  `props.open`, then the `state.openPanels` should be modified to include or exclude the only the **changed** `nextProps.open`'s `panelId`s, e.g.:
https://github.com/telus/tds-core/blob/727f5211fabc00554573bf61e5a1863d25462244/packages/ExpandCollapse/ExpandCollapse.jsx#L37-L41

**Comment by simpleimpulse** [comment]
This is fixed in @tds/core-expand-collapse@1.2.4

**Comment by ah-arch** [comment]
But that modified test is now invalid?
> triggers individual panel callbacks when panels are opened and closed


It becomes the same as:
> triggers a callback when any panel is opened or closed

The user is not able to change the `open` props after a panel's been opened.
https://github.com/telus/tds-core/blob/9bb49001ec4fec28370ae507daa16af22ccbdd4d/packages/ExpandCollapse/__tests__/ExpandCollapse.spec.jsx#L226

**Comment by ah-arch** [comment]
An additional test should also be added to handle this new scenario?

```
it('does not close panels if child component setState is called', () => {
  class TestComponent extends React.Component {
    render() {
      return (
        <button data-testid="button" onClick={() => { this.setState({ a: 'b' }) } }>
          button
        </button>
      )
    }
  }

  const { expandCollapse, findPanel } = doMount(
    <ExpandCollapse>{aPanel({ id: 'panel-1' }, <TestComponent />)}</ExpandCollapse>
  )

  expandCollapse.find(`[data-testid="panel-1"]`).find('Clickable').simulate('click')
  expectPanelToBeOpen(findPanel('panel-1'))

  expandCollapse.find(`[data-testid="button"]`).simulate('click')
  expectPanelToBeOpen(findPanel('panel-1'))
})
```
