### ISSUE TITLE
New pattern for Postal address 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#882]
## Description

The only way to present a postal address on the Billing page is with capital letters.

## Recommendation

I propose to have the possibility to write a postal address with capital and lower case letters.

## Designs

> current writing address pattern
https://telus.invisionapp.com/d/main/#/console/16159628/339181462/preview

> new writing address proposition 
https://telus.invisionapp.com/d/main/#/console/16159628/339181463/preview

## Meta

- TDS version: ...
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: No
- Designer/Developer Pair: Marie Fuhrmann, @Berjesty and @Jeffrey-Chang

**Comment by theetrain** [comment]
Hi Marie,

The TDS core-text component provides the ability to write copy in any case you need. I recommend reaching out to a content representative for My TELUS to find your answer on capitalizing billing addresses.
