### ISSUE TITLE
Optimization of toggle button's padding for a better layout

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#883]
## Description

When the webdevelopper uses our toggle button for the development of a page, there is a padding before and after the toggle button. This padding doesn’t give the flexibility to the developer to follow the layout created by the designer. So it’s impossible to aligne the text with the button on the same side. There will be always a shift.

## Recommendation

I would like that this padding is optional or deleted so that the alignment will be more aesthetic.

## Designs

- Sketch file: https://telus.invisionapp.com/d/main/#/console/16159628/339185023/preview

## Meta

- TDS version: v1.0.1
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: No
- Designer/Developer Pair: Marie Fuhrmann, @Berjesty and @Jeffrey-Chang

**Comment by theetrain** [comment]
Hi @Mariefhrmnn, the toggle-switch component is part of tds-community. Please [open an issue there](https://github.com/telus/tds-community/issues/new/choose) to start a conversation with the Digital Platform Ambassadors. For My TELUS, that would be @Berjesty.
