### ISSUE TITLE
New pattern for an error message block 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#884]
## Description

Our current components library has a pattern for a simple error message but not for an error message block. This error message block will be used for an error message specific to an element on the page. 

## Recommendation

I created a new pattern for this case which uses our components. This pattern will reply to this issue and could be help other designers when they will create new design with specific scenario.

## Designs

> desktop screen: https://telus.invisionapp.com/d/main/#/console/16159628/339187048/preview

> tablet screen: https://telus.invisionapp.com/d/main/#/console/16159628/339187047/preview

> mobile screen: https://telus.invisionapp.com/d/main/#/console/16159628/339187049/preview

## Meta

- TDS version: 1.0.1
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: ...
- Designer/Developer Pair: Marie Fuhrmann, @Berjesty and @Jeffrey-Chang

**Comment by theetrain** [comment]
Hi Marie,

@Christina-Lo will reach out to you to discuss opportunities to solve this using TDS core or community.

**Comment by Christina-Lo** [comment]
Reached out to @Mariefhrmnn on this and she will re-visit design with Berjesty

**Comment by Mariefhrmnn** [comment]
@Christina-Lo 
To follow up the discussion we had yesterday, I changed the design of my error block with the pattern that you showed me (approuved by @Berjesty). So you can close this issue. Thanks
