### ISSUE TITLE
Documentation — Add TELUS Usability Heuristics to Design & Foundational Principles

### ISSUE THREAD

**Issue by DougTelus** [telus/tds-core#888]
## Description

The design system documentation on _tds.telus.digital_ references usability heuristics in the [design principles page](https://tds.telus.com/design/principles.html), however it does not link-to any specific content.

## Recommendation

On _tds.telus.digital_ create a **TELUS usability heuristics** section under Design & Foundational Principles.
- List and explain each heuristic
- Explain the purpose of usability heuristics
- Explain how to use the heuristics to objectively critique

### TELUS Usability Heuristics
Usability heuristics are a list of design principles against which the usability of an interface can be assessed.
Heuristic evaluations are never intended to stand alone. They are an element in a larger UX design process, which provide a quick and standardized means to assess the usability an interface.

### 1. Aesthetic and minimalist design
Every unnecessary element competes with the important ones and diminishes their relative visibility. The TELUS aesthetic is both clear and simple. Less is better.

### 2. Consistency
Customers shouldn’t have to wonder whether different words or design elements mean the same thing. Follow standard conventions – both our internal conventions, and broader web standards.

### 3. Visibility of system status
Provide clear feedback as to what the system is doing and what the customer should do next.

### 4. Recognition rather than recall
Ensure all elements of the design are easy to comprehend and familiar-looking. Never rely on a customer's ability to remember information in order to navigate.

### 5. Match between system and the real world
Speak our customers’ language – with familiar words, phrases and concepts. Avoid technical or insider jargon.

### 6. Efficiency of use
Find ways to do the work for customers. Remember their choices and pre-populate fields where possible.

### 7. Error avoidance and handling
Prevent errors from happening in the first place – through intelligently constraining choice, clear instructions, anticipating customer questions or actions.

Where errors do occur, provide graceful recovery. In plain language, tell customers what went wrong and how to fix it.

### 8. Guiding the user
Ideally, flows should be so simple that instructions aren’t necessary. 

For complex interactions, clearly lay out the steps customers need to take. And make sure the instructions are easy to ignore or dismiss by those who don’t need them.

## Source Content Links

TELUS Usability Heuristics [Link](https://docs.google.com/presentation/d/1sM4ZVbI3fgPngkmKfHQjxCAG2hM_4c9N_xe1gzs4-FQ/edit#slide=id.g21672f9765_0_0)

Douglas Limin’s quiz/presentation [Link](https://docs.google.com/presentation/d/1St7fqwOgBZs9zmVksqqfTnK6S2MPJHScRVkyOBuBxyk/edit#slide=id.p1)

Lucy List’s presentation [Link](https://docs.google.com/presentation/d/1mpO-8XqHXgrfkdZL2OijqGeNnv3Qh53UL-p1NqHT0ic/edit?usp=sharing)

### Considerations

https://asktog.com/atc/principles-of-interaction-design/

**Comment by theetrain** [comment]
This documentation has been published: https://tds.telus.com/design/heuristics.html
