### ISSUE TITLE
[ExpandCollapse] `open` prop behaviour

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#892]
## Why

The ExpandCollapse/Accordion React component is widely used across TELUS applications. In an effort to improve documentation and component behaviour, the TDS core team would like to gather insights on the usage of its `open` prop.

## What

In a recent release, [@tds/core-expand-collapse@1.2.4](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-expand-collapse%401.2.4) (see #879), we patched ExpandCollapse to not have collapsing behaviour when calling `this.setState()` from a component that is a child of `<ExpandCollapse.Panel />`. After calling `this.setState()` it is then no longer possible to change which panels are open within that ExpandCollapse using the `open` prop.

The `open` prop is documented as follows:
> A list of panel identifiers to programmatically open.

From this description, no assumptions can be made about whether the `open` prop:
- A: should only be used for initial opened state of Panels, or
- B: is always able to control the opened state of its Panels.

### The question

As consumers of ExpandCollapse, which of the above behaviours do you expect from the `open` prop?

### Animated examples

<details><summary>Code snippet used in examples below</summary>

```jsx
class MyApp extends React.Component {
  state = {
    checked: false,
    open: []
  }

  changeHandler = () => {
    this.setState((previous) => {
      return { checked: !previous.checked }
    })
  }

  closePanel = () => {
    this.setState({ open: [] })
  }

  openPanel = () => {
    this.setState({ open: ['features'] })
  }

  render() {
    return (
      <React.Fragment>
        <ExpandCollapse tag="h2" open={this.state.open}>
          <ExpandCollapse.Panel id="features" header="Features">
            <Checkbox
              label="Call setState() within onChange handler"
              name="hello"
              value="Hii"
              checked={this.state.checked}
              onChange={this.changeHandler}
            />
            <Button onClick={this.closePanel}>Close panel (via open prop)</Button>
          </ExpandCollapse.Panel>
        </ExpandCollapse>
        <Button onClick={this.openPanel}>Open panel (via open prop)</Button>
      </React.Fragment>
    )
  }
}
```

</details><br>

**ExpandCollapse v1.2.3**
Clicking the Panel heading and then calling `setState` from child component closes the Panel, due to it re-rendering with an empty initial state. The `open` prop can always control Panel state.

![screen recording 2019-01-15 at 02 55 pm](https://user-images.githubusercontent.com/12798751/51206239-9e08fa80-18d5-11e9-95c4-3a59ae8416d4.gif)

**ExpandCollapse v1.2.4**
Clicking the Panel heading and then closing via props does not work. The `open` prop can only be used to control Panel state when the user does not change the state by clicking a Panel heading.

![screen recording 2019-01-15 at 02 42 pm](https://user-images.githubusercontent.com/12798751/51205639-53d34980-18d4-11e9-8f3e-9d22adc0e8b1.gif)

## How

Depending on consumer expectations of ExpandCollapse, we see two potential outcomes:

### A. Keep ExpandCollapse as a class component, use `open` only for initial state

By modifying existing documentation, we can help consumers make the right assumptions over the behaviour of the `open` prop being an initial state setter, and keep ExpandCollapse v.1.2.4 as-is.

### B. Change ExpandCollapse into a functional component, provide an optional state controller

As a future development, we can produce a stateless functional component, which involves the following steps:

1. Revert the 'fix' made to ExpandCollapse 1.2.4, and deploy 1.2.5, which restores functionality as seen in 1.2.3
2. Add documentation to ExpandCollapse to recommend controlling the state of ExpandCollapse manually via the `open` prop. That means when you use Checkbox (or anything inside ExpandCollapse.Panel that calls `this.setState`), your application should then be sure to update the `open` prop. We will also document recommendations.
3. Down the line, we'll release ExpandCollapse 2.0.0 to be a functional component with state being handled by the application, or our forthcoming `WithState` component wrapper that can be used for Sitebuilder/simple applications.

## Who

- @theetrain 
- @ah-arch 
- @nicmak 
- All TDS code consumers

## Meta

- TDS component: @tds/core-expand-collapse@1.2.4
- Willing to develop solution: Yes
- Has workaround: No 
- High impact: ?

**Comment by DJDA** [comment]
☑Option B please !

**Comment by marcod1419** [comment]
We have decided to move forward with Option B! @DJDA

**Comment by theetrain** [comment]
Before moving forward, we will gather a second opinion from @invalidred.

**Comment by invalidred** [comment]
Option B would be cleaner, however there is nothing wrong with `Option A` with slight modification where `open` is a controlled prop and the introduction of an `initialOpen` state initializer prop.

The idea is if the consuming code passes `open` then it controls the state. For existing clients who don't want to control state, they can rename `open` to `initialOpen` and they are good to go.

A good example of `controlled` props can be found here `https://github.com/invalidred/advanced-react-patterns-v2/blob/master/src/exercises-final/10.js` notice the `getState()` func in `line 11`

This will be a breaking change, however the API does not change significantly.

**Comment by theetrain** [comment]
Closing this because we have already implemented new prop behaviour for `open` in ExpandCollapse. Feel free to re-open this issue if a concern related to `open` resurfaces.
