### ISSUE TITLE
FlexGrid.Col adds whitespace under images

### ISSUE THREAD

**Issue by Andrew-K-Lam** [telus/tds-core#895]
## Description

Putting an image inside a FlexGrid.Col adds a small whitespace underneath the image that prevents images from being flush against other elements (i.e. the global footer). 

## Recommendation
The column has a line-height used for text.  For images, line-height should be 0px.

## Reproduction Steps
1. Go to https://tds.telus.com/components/index.html#!/Col/5
2. Replace code with the following:
```
<FlexGrid>
  <FlexGrid.Row>
    <FlexGrid.Col>
		<Text>Text</Text>
    </FlexGrid.Col>
    <FlexGrid.Col>
      <Image
        src="image-example.jpg"
        rounded="corners"
        width={300}
        height={300}
        alt="Image of co-workers collaborating"
        />
    </FlexGrid.Col>
  </FlexGrid.Row>
</FlexGrid>
```

3. Inspect the Column wrapping the image
4. Observe that the column has extra space between the bottom edge of the image and the bottom edge of the column div.
## Reproduction Percentage (if applicable)

- 10/10 times

## Screenshots
![image](https://user-images.githubusercontent.com/931411/51411610-78c6f700-1b36-11e9-8da1-2cd14896e973.png)

**Comment by theetrain** [comment]
It turns out, this behaviour can be remedied by core-image if it could render using `display: block` CSS. This is being addressed internally https://telusdigital.atlassian.net/browse/TDS-1136

**Comment by marcod1419** [comment]
Reopening this because `display: block`, while removing the whitespace, blocks the ability to properly align content using `horizontalAlign`. Opening until a sufficient workaround is found.

**Comment by theetrain** [comment]
Closing due to low demand. If this issue resurfaces for others, feel free to add a comment and we'll re-prioritize.
