### ISSUE TITLE
[Input] should the helper prop be discouraged?

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#896]
## Question

Should the core-input component's `helper` prop be completely discouraged once hint text is able to be displayed below the label (see #893)?

The helper prop produces an Input Feedback component above the Input field, with a grey background (see screenshot below). It is currently possible to have both helper text and error text, which displays two Input Feedback components one after the other.

## Related components

- @tds/core-input 
- all other form components 

## Who

- @Christina-Lo 
- @ah-arch 
- Apurv Ray

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/51349795-700dec80-1a74-11e9-802c-f2f16cf1a741.png)

**Comment by Christina-Lo** [comment]
This is a design pattern that we want to avoid. If an error feedback is to be used with additional text, we encourage the use of hint text

**Comment by simpleimpulse** [comment]
Closing, because we have consensus from designers that this is not necessary/recommended.
