### ISSUE TITLE
CSS specificity issue with horizontalAlign in FlexGrid Column

### ISSUE THREAD

**Issue by affansajid** [telus/tds-core#899]
## Description

FlexGrid Column property horizontalAlign not following mobile-first rule.

Given `<FlexGrid.Col horizontalAlign={{ xs: 'right', sm: 'center', md: 'left' }}>`,
for breakpoints md, lg and xl, the alignment property 'center' for the previous breakpoint 'sm' is taking priority because of CSS specificity. The expected behaviour should be the alignment property 'left' for breakpoints md, lg and xl. 

## Reproduction Steps

Take the following example of code:
```
<FlexGrid>
  <FlexGrid.Row>
    <FlexGrid.Col horizontalAlign={{ xs: 'right', sm: 'center', md: 'left' }}>
      <Box vertical={2}>
        <Text>Right on 'xs'. Center on 'sm'. Left on 'md', 'lg', 'xl'.</Text>
      </Box>
    </FlexGrid.Col>
  </FlexGrid.Row>
</FlexGrid>
```
Now resize the browser window to hit the breakpoints from xs to xl and observe the behaviour of alignment property for each breakpoint

You can test this in the code editor [here](https://tds.telus.com/components/index.html#!/Col/7)

## Meta

- TDS component version: @tds/core-flex-grid@2.3.3
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No

**Comment by theetrain** [comment]
Thanks for the report, @affansajid! We would appreciate your contribution.

**Comment by jraff** [comment]
Fixed with the release of @tds/core-flex-grid@2.3.5.
