### ISSUE TITLE
TDS UnorderedList - Alignment of the icons are off on IE11 / Windows 7

### ISSUE THREAD

**Issue by paultheva** [telus/tds-core#924]
## Description

When using the UnorderedList with the check or error list, the icons are misaligned. It only seems to happen on IE11 / Windows 7 (Windows 10 is fine).

## Reproduction Steps

1. Use IE11 on a Windows 7 machine.
2. View the UnorderedList with either the check or error icons.

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: 2.0.4
- Willing to develop solution: No
- Has workaround: No
- High impact: No

## Screenshots

On tds.telus.com:
![checkmark-alignment](https://user-images.githubusercontent.com/8562738/52448208-2a879100-2b01-11e9-95fc-643bf70b54d8.png)

**Comment by marcod1419** [comment]
This has been addressed in the latest `UnorderedList` release! https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-unordered-list%403.0.6

**Comment by mejsullivan** [comment]
It could be argued this is a fix for accessibility @varunj90 @dewing9 @owestinTelus

**Comment by varunj90** [comment]
hey Beth @mejsullivan according to me it's just a bugfix for IE11 and not a new feature. You could say visual alignment is an accessibility fix, but then we will be marking everything with that label, which isn't the intent.
