### ISSUE TITLE
[Spinner] a11yLabel defaultProp

### ISSUE THREAD

**Issue by umair00** [telus/tds-core#931]
## Description

_Spinner_ accepts as a prop `a11yLabel` which defaults to english copy: https://github.com/telus/tds-core/blob/a94d89d3e3877ebce99b2d7b70e4dc8fe1801bff/packages/Spinner/Spinner.jsx#L68

This text appears under the `title` tag of the `svg` with the spinner graphic: https://github.com/telus/tds-core/blob/e882388000060dc20da3801c34b2468d5b389633/packages/Spinner/SpinnerSvg/SpinnerSvg.jsx#L37

The `title` is shown to clients when they hover over the spinner and it can be a problem. For example, what if the user is using the french version of the site and no french copy has been passed in for the `a11yLabel` prop? The english content would continue to appear in this case. This is current behaviour when logging into telus.com and can be observed by hovering over the spinner in the login button while it's active.

## Reproduction Steps

1. Create a page with a `Spinner` component and do not provide an `a11yLabel` prop
2. Hover over the component to see the default text

## Meta

- TDS component version: 2.1.1
- Willing to develop solution: Yes
- Has workaround: Yes (provide values for the prop depending on locale)
- High impact: No

**Comment by theetrain** [comment]
Thanks for your suggestion. It appears that Spinner makes assumption about language, and we should reconsider its use of `a11yLabel`. Another component, core-step-tracker, makes the same assumptions about language. 

We can use this as an opportunity to refine our principles related to copy. Two patterns come to mind:
1. TDS Components supply English copy by default, but can be overridden (current pattern)
2. TDS Components provide required props where copy is needed, without supplying defaults

Though technically you can resolve your issue today by supplying French copy to core-spinner, this may not be the best developer experience. What are your thoughts on this?

**Comment by simpleimpulse** [comment]
TDS Core team recommends option #2. 
We will move forward with enhancements.

**Comment by varunj90** [comment]
All the JIRA tickets can be found here: https://telusdigital.atlassian.net/browse/TDS-1282

**Comment by theetrain** [comment]
The Spinner component has been updated and now includes accessibility considerations within its documentation.

It covers use cases such as:

- overlaying buttons, links, or other interactive elements
- how to set up your project to announce loaded content
- covering purple or green buttons with higher contrast
- supplying a label to the Spinner using brief, relevant copy in any language

Learn more:

- [@tds/core-spinner@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-spinner%402.2.0)
- [Spinner documentation](https://tds.telus.com/components/index.html#spinner)
- DSM Library version: _TDS_core v.2.1.10
- DSM Release notes: https://telus.invisionapp.com/dsm/telus/tds-core/releases

**Comment by theetrain** [comment]
With the new `label` prop in place, the former `a11yLabel` will be removed at around December 2019, and then the `label` prop will be required in order to accept copy in any language.

**Comment by theetrain** [comment]
Closing this issue now as the underlying request was resolved. You can expect a breaking change to Spinner that removes the deprecated API sometime in December 2019.
