### ISSUE TITLE
New color for cross icon 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#938]
## Description

There is an inconsistency between the color of the cross icon (purple) and the color of the error notification (red) that can be used together.

## Recommendation

I propose to update the color of the cross icon with a red colour. So there will be a better logic for the user to see a red error message linked with a red cross icon.

## Designs

**Current design:**
![screen shot 2019-02-14 at 9 25 47 am](https://user-images.githubusercontent.com/44266628/52792951-98b8e000-303a-11e9-82f7-da7dfef94a6d.png)

**Improved design:**
![screen shot 2019-02-14 at 9 25 58 am](https://user-images.githubusercontent.com/44266628/52792964-9f475780-303a-11e9-8c79-6b11cd08a275.png)

## Meta

- TDS component: 
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No
- Designer/Developer Pair: Marie Fuhrmann / @Berjesty and @invalidred / @jesdavpet / @Jeffrey-Chang

**Comment by theetrain** [comment]
Hi Marie, it is currently possible to have the times icon in the colour red using the Decorative Icon component: 

![image](https://user-images.githubusercontent.com/12798751/52798991-01a65500-3047-11e9-9f0f-d1097074e431.png)

Let me know if this resolves your issue.

**Comment by Mariefhrmnn** [comment]
@theetrain Thanks for your answer I didn't find the component. We can delete this issue!
