### ISSUE TITLE
<Box inline={true}> extra vertical space in IE 11

### ISSUE THREAD

**Issue by kretzm** [telus/tds-core#940]
## Description
Issue is similar to #783
We're running into a scenario where we have <Box inline={true} .. >and there is extra vertical space below the element on IE 11. Adding `flex-shrink: 0` fixes the issue.

our code implementation looks similar to this;
```
<div .. >
  <Box between={5}>
    <Box inline={true} between={4}>
      <div .. > some content </div>
    </Box>
  </Box>
</div>
```

## Meta

- TDS component version: @tds/core-box": "^1.0.1
- Willing to develop solution: Yes
- Has workaround: Yes (we can hardcode `flex-shrink: 0` on the component
- High impact: No

## Screenshots
<img width="1080" alt="ti-ie-bug" src="https://user-images.githubusercontent.com/900447/52887491-e5d5a880-3145-11e9-84be-0702082f3214.PNG">
<img width="1079" alt="ti-ie-bug-2" src="https://user-images.githubusercontent.com/900447/52887500-e9692f80-3145-11e9-8b2e-7e0c2d1dd4f3.PNG">

**Comment by theetrain** [comment]
Hi Mike, thanks for the report! You may contribute a PR to remedy this if you have the cycles.

**Comment by marcod1419** [comment]
@kretzm Hi there! I was just looking into this but can't seem to reproduce this issue with the provided code snippet or otherwise. Could you provide a more detailed code snippet that's close to the one demonstrated in your screenshot? We will then use that one to see if we can reproduce the issue on our end. Thanks!

**Comment by varunj90** [comment]
hey @kretzm any update on this?

**Comment by kretzm** [comment]
@marcod1419 
Looks like this is causing an issue when the direct child element has a css width value using `calc()`. If I hard set the width value (ex. "100px") and remove my `flex-shrink: 0` fix, I don't see the issue. 

```
-- JSS
block: {
    width: 'calc(50% - 1rem)'
}

-- React
<Box between={5}>
  <Box inline={true} between={4}>
    <div className={classes.block} xs={12} lg={6}>
       ... content ... 
    </div>
  </Box>
</Box>
```

Issue is here: https://www.telusinternational.com/careers (in the section just above "Career Opportunities")

**Comment by varunj90** [comment]
Removing label blocked as the next TDS developer looking at this can look at Mike's response and connect with him over slack if any other clarifications are required.

**Comment by jraff** [comment]
Closing this issue, if it arises for anyone please use the `flex-shrink` workaround seen above. @kretzm
