### ISSUE TITLE
[Tooltip] cut off when used in a expand collapse

### ISSUE THREAD

**Issue by alfredctchoi** [telus/tds-core#944]
## Description

When using the ToolTip component within an ExpandCollapse component, if the tool tip text is long, it gets cut off by the ExpandCollapse component.  See attached image.

## Reproduction Steps

```javascript
<ExpandCollapse tag="h2">
  <ExpandCollapse.Panel id="features" header="Features">
    <Box between={3}>
      <Box>
        <Input
          label="Enter your device's IMEI number"
          type="number"
          tooltip={
            <Tooltip direction="left">
              You can find your devices IMEI by typing *#06# on its dialpad. Please enter the complete
              15-digit number, without spaces or characters.
            </Tooltip>
          }
        />
      </Box>
      <Box between={2}>
        <Heading level="h4">Connected GPS</Heading>
        <Paragraph size="medium">Connect to your phones GPS to see real-time run stats.</Paragraph>
      </Box>

      <Box between={2}>
        <Heading level="h4">Notifications</Heading>
        <Paragraph size="medium">See call, text and calendar alerts on your wrist.</Paragraph>
      </Box>
    </Box>
  </ExpandCollapse.Panel>

  <ExpandCollapse.Panel id="specs" header="Specifications">
    <Box between={3}>
      <Box between={2}>
        <Heading level="h4">Display</Heading>
        <Paragraph size="medium">OLED</Paragraph>
      </Box>

      <Box between={2}>
        <Heading level="h4">Battery Life</Heading>
        <Paragraph size="medium">Up to 5 days</Paragraph>
      </Box>
    </Box>
  </ExpandCollapse.Panel>
</ExpandCollapse>
```

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: @tds/core-expand-collapse@1.2.5 & @tds/core-tooltip@2.0.5
- Willing to develop solution: Maybe
- Has workaround: No
- High impact: No

## Screenshots
![image from ios 2](https://user-images.githubusercontent.com/5086190/53060429-84387580-3488-11e9-9254-bf21ae5d255d.png)

**Comment by theetrain** [comment]
Hi Alfed, thanks for the report! This is a defect, and we welcome your contribution. I recommend having the ExpandCollapse.Panel set its css to `overflow: visible;` after it has expanded, and then back to `overflow: hidden` when it has collapsed.

**Comment by alfredctchoi** [comment]
@theetrain Please see https://github.com/telus/tds-core/pull/946.  I am not sure if I did the commitlint correctly

**Comment by marcod1419** [comment]
This has been addressed in the[ latest version](https://github.com/telus/tds-core/releases/tag/%2540tds%252Fshared-animation%25401.1.1) of `shared-animation`. Thanks for the PR @alfredctchoi!
