### ISSUE TITLE
TDS Card without drop-shadow, is it possible?

### ISSUE THREAD

**Issue by karlasamantha** [telus/tds-core#956]
## Question

Hi TDS team, there was a question raised within the Brand Experience team around the possibility of having the flexibility of using the Card component with white background but without the drop-shadow. Currently, we are using BlockTestimonial within Site Builder and @gkychow asked about this possibility.

## Related components

- Component: @tds/core-card@1.0.2

## Screenshots

![screen shot 2019-02-28 at 9 33 56 am](https://user-images.githubusercontent.com/1015398/53586034-279a2200-3b3c-11e9-92fe-8a810b80b015.png)

**Comment by marcod1419** [comment]
Hi there @karlasamantha! It seems that this issue would be more relevant in [tds-community.](https://github.com/telus/tds-community/issues) Could you re-create this over there with their issue template?

Thank you!

**Comment by theetrain** [comment]
Please follow the conversation in https://github.com/telus/tds-community/issues/192
