### ISSUE TITLE
[UnorderedList] Unable to conditionally insert UnorderedList.Item

### ISSUE THREAD

**Issue by ElliottJRo** [telus/tds-core#966]
Note: Not sure if this should be a feature request or bug since technically there is a workaround

## Description
Unable to conditionally insert `UnorderedList.Item` since `UnderedList` renders via `const injectListStyle = (child, listStyle, size) => React.cloneElement(child, { listStyle, size })`

The following will throw a render error from `UnorderedList`

```jsx
<UnorderedList>
  {false && <UnorderedList.Item>test</UnorderedList.Item>}
  <UnorderedList.Item>elem2</UnorderedList.Item>
</UnorderedList>
```

The workaround is to move the conditional insert outside of `UnorderedList`
```jsx
{true ? (
  <UnorderedList>
    <UnorderedList.Item>test</UnorderedList.Item>
    <UnorderedList.Item>elem2</UnorderedList.Item>
  </UnorderedList>
) : (
  <UnorderedList>
    <UnorderedList.Item>elem2</UnorderedList.Item>
  </UnorderedList>
)}
```

## Meta

- TDS component version: @tds/core-unordered-list@2.0.5
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: No

**Comment by theetrain** [comment]
Thank you for reporting this issue! We welcome any pull requests if you are able to put in the time.

**Comment by theetrain** [comment]
Thank you Elliot for your contribution! This has now been resolved in the following packages:

- [@tds/core-unordered-list@2.0.15](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-unordered-list%402.0.15)
- [@tds/core-ordered-list@2.0.15](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-ordered-list%402.0.15)
