### ISSUE TITLE
Form field sizing and spacing

### ISSUE THREAD

**Issue by kittybourne** [telus/tds-core#974]
## Question

I noticed that form input fields are very large and with multiple fields it takes up a lot of spacing on the page. Spacing is inconsistent and not always clear for labels + input field relationship. Can we reconsider how the fields appear when they stack one on top of each other on a sign up or check out page? This spacing issue is more apparent on mobile. 

## Related components

- Component @tds/core-input
- Component @tds/core-select

## Screenshots

![screen shot 2019-03-07 at 3 18 43 pm](https://user-images.githubusercontent.com/6434886/53996265-9e12c300-40ec-11e9-9b89-d75e5320636c.png)

**Comment by donnavitan** [comment]
Currently reviewing form fields and buttons as a whole with CX team; will address vertical spacing as part of it.

**Comment by donnavitan** [comment]
Recently had a workshop with CX, a11y, and TDS to discuss form and form field considerations; spacing/sizing is included. Additional discovery, design, and planning required. Will update when there are any further changes.

**Comment by donnavitan** [comment]
Just adding an update that the TDS team is currently in progress updating the height of `input` and `select` fields. However, vertical spacing is out of scope in being applied to components themselves, as we rely on establishing margins/space between using the [Box component](https://tds.telus.com/components/index.html#box). We will include a recommendation for vertical spacing in the documentation for the upcoming update. Thanks y'all, for your patience.

**Comment by marcod1419** [comment]
This has been addressed in Input 3.0.12 and Select 3.1.2.
