### ISSUE TITLE
Reveal in @tds/shared-animation should close the accordion smoothly, without the text disappearing

### ISSUE THREAD

**Issue by Andrew-K-Lam** [telus/tds-core#980]
## Description
When Closing an accordion using the Reveal component in @tds/shared-animation, text should not disappear when the drawer closes/comes up.

## Reproduction Steps

1. Go to https://tds.telus.com/components/index.html#expandcollapse
2. Close the "Features" menu
3. Observe that the text in the "Features" menu disappears when the menu closes. 

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- TDS component version: @tds/shared-animation@1.1.0
- Willing to develop solution: Yes
- Has workaround: No
- High impact: Not really....

## Screenshots
@Christina-Lo Can you help provide the GIF from Motion Principals?

**Comment by Christina-Lo** [comment]
Here's the example that has been created for Motion Principles 
![accordian](https://user-images.githubusercontent.com/42220619/54155520-ab94b980-441a-11e9-9868-fbad0fe6c138.gif)

**Comment by simpleimpulse** [comment]
TDS Core team will be revisiting this in April/May when we incorporate motion & animation principles defined by CX.

**Comment by theetrain** [comment]
Small update: we will make this fix once we finalize our animation tooling.

**Comment by theetrain** [comment]
Update:

We will improve our animation utilities once we adopt new animation tooling.

**Comment by theetrain** [comment]
Update: this is currently in QA and will be released soon.

**Comment by varunj90** [comment]
This has been released
Release notes: https://github.com/telus/tds-core/releases/tag/@tds%2Fcore-expand-collapse@2.0.17
