### ISSUE TITLE
Large bundled size 

### ISSUE THREAD

**Issue by xingbo828** [telus/tds-core#981]
TDS bundled file size reaches 400KB before gzip.  This is almost half of our app total bundled size. bigger than all other libs combined.

## Screenshots

![Screen Shot 2019-03-12 at 3 03 32 PM](https://user-images.githubusercontent.com/3753196/54239320-1fe16280-44d8-11e9-966d-c6134637f45e.png)

**Comment by varunj90** [comment]
we will release the patch this week @xingbo828

**Comment by theetrain** [comment]
This has been resolved in the following packages:

- [@tds/shared-form-field@2.2.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fshared-form-field%402.2.0)
- [@tds/core-select@2.0.14](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-select%402.0.14)
- [@tds/core-input@2.1.11](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-input%402.1.11)
- [@tds/core-text-area@2.0.12](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-text-area%402.0.12)
