### ISSUE TITLE
[Tooltip][StandaloneIcon] - RFC - WAVE a11y tool false positive - empty button error

### ISSUE THREAD

**Issue by ElliottJRo** [telus/tds-core#985]
## Description
When doing accessibility tests with the WAVE (web accessibility evaluation tool) extension, it marks the tooltip as having an error: empty button (see below). I believe the fix can be done on StandaloneIcon [at this line](https://github.com/telus/tds-core/blob/master/packages/StandaloneIcon/StandaloneIcon.jsx#L41) by adding a hidden text element or similar?

```jsx
    return (
      <Clickable
        {...safeRest(rest)}
        onClick={onClick}
        dangerouslyAddStyle={needsExpandedTouchArea ? touchAreaStyles(size) : undefined}
      >
        {/* <SomeHiddenText>{Label for icon here}</SomeHiddenText> */}
        <Icon {...iconProps} />
      </Clickable>
    )
```

Looks like some people on stackoverflow suggest just [adding text between the icon tags](https://stackoverflow.com/a/34839293) but that defeats the purpose of having clickable icons so not sure where to go.

## Meta

- TDS component version:   core-standalone-icon @ 1.0.2
- Willing to develop solution: No 
- Has workaround: No
- High impact: No

Initially raised by @mejsullivan 

## Screenshots

![Screen Shot 2019-03-13 at 2 04 15 PM](https://user-images.githubusercontent.com/1139851/54314559-3c919f00-4599-11e9-9efe-724cb8b997a5.png)

**Comment by theetrain** [comment]
This is related to #931 

We plan on allowing users to provide their own copy for the button's action text. We can consider also supplied default copy for French and English that the consumer may opt into.

**Comment by mejsullivan** [comment]
Hello Enrico,

My apologies it's been a long week. I'm not quite understanding your messages.

Are you saying that you need assistance to identify why wave is throwing the error?

Or are you saying that this isn't a TDS error but an implementation error?

Is the developer he raised the issue also in this conversation - it might be helpful for them too?

Thanks
Beth

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Mar 15, 2019 at 6:47 AM -0700, "Enrico Sacchetti" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is related to #931<https://github.com/telus/tds-core/issues/931>

We plan on allowing users to provide their own copy for the button's action text. We can consider also supplied default copy for French and English that the consumer may opt into.

**Comment by mejsullivan** [comment]
Hello,

Sorry I'm not sure I understand how this works. I see Elliot is in the conversation?

Sorry .
Beth

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Mar 15, 2019 at 6:47 AM -0700, "Enrico Sacchetti" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is related to #931<https://github.com/telus/tds-core/issues/931>

We plan on allowing users to provide their own copy for the button's action text. We can consider also supplied default copy for French and English that the consumer may opt into.

**Comment by agorovyi** [comment]
The fix has been released: https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-standalone-icon%401.1.1
