### ISSUE TITLE
[Card] can we customize padding?

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#998]
## Question

Original question by @hamedmam 

Can the tds core-card have customized padding? There are some designs that call for reduced padding. Could we also potentially remove default Box spacing within Card, allowing developers to implement their own custom Box spacing?

cc @xingbo828 @ah-arch @elenaverling 

## Related components

- `@tds/core-card`
- `@tds/core-box`

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/54769191-1c846000-4bd7-11e9-943a-0dc1b060bfcf.png)

![image](https://user-images.githubusercontent.com/12798751/54769366-6bca9080-4bd7-11e9-8635-fde00024a2f8.png)

**Comment by Christina-Lo** [comment]
Brought this to the design leads meeting and it was decided that from a design perspective, not customizing padding is what we are moving forward with, mainly to keep consistency. However if a stronger case can be made or perhaps more details/context can be provided then this can be reviewed again.

**Comment by theetrain** [comment]
As per design direction, dense cards will not be permitted at this time. Related: the `@tds/community-preview-card` component is available!

**Comment by KamalShatila** [comment]
@Christina-Lo ![Card Padding - Issue](https://user-images.githubusercontent.com/50418093/66950442-5e1ea180-f026-11e9-9e5e-4a6d10d87a6b.png)

**Comment by theetrain** [comment]
Thanks for the screenshots, @KamalShatila. I see potential in having the card provide multiple padding sizes responsively.

This proposal will be reviewed by CX.

**Comment by KamalShatila** [comment]
Awesome, thank you! @theetrain

**Comment by Christina-Lo** [comment]
@KamalShatila Feed back from CX is that we will move forward allowing customized padding, but with detailed guidelines of when we can use different spaces for Card

**Comment by twirlingsky** [comment]
Can we escalate this issue? Cards in CPP and other production environments are quite different - causing a lot of spacing issues. Here's an example (CPP on the left - bloated looking address component and plan cards):

![Comparison Cards - RL to CATA](https://user-images.githubusercontent.com/22402633/69675422-6c170780-1053-11ea-8dcd-726dec45b661.jpg)

**Comment by twirlingsky** [comment]
When this ticket is completed will the Site builder team be notified (I'm guessing they need to update on their end too?)

**Comment by theetrain** [comment]
Addition Card spacing is now available in the following release:

- DSM v2.3.11
- React component: [@tds/core-card@2.3.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-card%402.3.0)
- Documentation: https://tds.telus.com/components/index.html#!/Card
